### ISSUE TITLE
Multiline Text field sometimes end up with a scrollbar when pasting lots of content in Chrome

### ISSUE THREAD

**Issue by maxime-rainville** [Shopify/polaris#104]
# Issue summary

If you paste a lot of content in a multiline text field, the text field will be displayed with a scrollbar rather than automatically resize to display all the content.

## Expected behavior

When pasting a long string into a Text Field with the `multiline` option enabled, the text field's height should automatically adjust to display all the content without the need to scroll the textarea.

## Actual behavior

The Text field will expand, but not enough to display all the content without a scroll bar. If you add a few extra break lines, the text field height will increase, but not enough to get rid of the scrollbar.

## Steps to Reproduce the Problem
1. Generate about 2500 characters worth of _lorem ipsum_ text.
1. Copy the content in a Text Field with the `multiline` option enabled.

## Specifications

- Polaris version: 1.1.1
- React version: 15.6.1
- Browser: Chrome 54.0.2840.71 (Firefox seems happy)
- Device: Desktop
- Operating System: Ubuntu 17.04

## Potential cause
I think Chrome adds a scrollbar to the textarea before the Resizer attached to the Text Field has a chance to recalculate the height of the text area. The textarea's horizontal display area is therefore cut down by a few pixels because of the scroll bar.

Because the Resizer's DummyInput does not have a scroll bar, it can display slightly more content than the textarea. So when the Resize reports a height change to its parent Text Field, the new height will be a tiny bit too short to display all the content in the textarea with the scroll bar.

**Comment by ry5n** [comment]
Hi Maxime. Thanks for flagging this. I can’t reproduce on Mac OS, and I don’t have an Ubuntu install handy. Any chance you could try this using the latest version of Polaris (1.12.0) or try it in the live example here? https://polaris.shopify.com/components/forms/text-field

I want to determine if this is an OS issue or maybe an issue with an older release.
