### ISSUE TITLE
[a11y] Component accessibility documentation

### ISSUE THREAD

**Issue by dpersing** [Shopify/polaris#1050]
Want to add a quick PR to help improve our documentation? Want to support accessibility work in Polaris? Do I have the project for you.

[Check out the project history](https://unicorn.shopify.io/projects/6177) for more details.

[See all of the drafts including content for guides and patterns](https://docs.google.com/document/d/1ONoa4fUsqG19i5h0h2Kz2w9CvmFSN926YmoNVMsGPgw/edit#heading=h.ypa7651v6ny), for copy.

## How to do it

1. If you want to do some writing, check out components in the *To do* or *Outlined* sections.
1. If you want to do some editing, see *Written*.
1. If a component's documentation has been edited and is ready for a PR, go ahead and open one. Keep an eye out for documentation that references other components; we'll want to make sure those references get released together or are already out.
1. If you want to review open PRs, take a look at *Open PRs*.

### Formatting content

The component docs live in the `README.md` file for the component. To add a section, add this snippet to the end of the `README.me` file:

```
---

## Accessibility

<!-- content-for: android -->

See Material Design and development documentation about accessibility for Android:

- [Accessible design on Android](https://material.io/design/usability/accessibility.html)
- [Accessible development on Android](https://developer.android.com/guide/topics/ui/accessibility/)

<!-- /content-for -->

<!-- content-for: ios -->

See Apple’s Human Interface Guidelines and API documentation about accessibility for iOS:

- [Accessible design on iOS](https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/accessibility/)
- [Accessible development on iOS](https://developer.apple.com/accessibility/ios/)

<!-- /content-for -->

<!-- content-for: web -->

...Your new content...

<!-- /content-for -->
```

Check out the merged PRs for examples.

### Questions?

Ask @dpersing about things in general or ask @sadiesaurus about content/editing specifically.

### To do

- [Button group](https://docs.google.com/document/d/1ONoa4fUsqG19i5h0h2Kz2w9CvmFSN926YmoNVMsGPgw/edit#heading=h.ycampl5nx9n2) (dependent on https://github.com/Shopify/polaris-react/pull/984)
- [Resource picker](https://docs.google.com/document/d/1ONoa4fUsqG19i5h0h2Kz2w9CvmFSN926YmoNVMsGPgw/edit#heading=h.gzqaz3tcqv66)
- [Top bar](https://docs.google.com/document/d/1ONoa4fUsqG19i5h0h2Kz2w9CvmFSN926YmoNVMsGPgw/edit#heading=h.qm6fz1bdcuvq)

### Outlined

- [Form layout](https://docs.google.com/document/d/1ONoa4fUsqG19i5h0h2Kz2w9CvmFSN926YmoNVMsGPgw/edit#heading=h.36wbtebkgnt0)
- [Frame](https://docs.google.com/document/d/1ONoa4fUsqG19i5h0h2Kz2w9CvmFSN926YmoNVMsGPgw/edit#heading=h.dkiciji2pc16)
- [Navigation](https://docs.google.com/document/d/1ONoa4fUsqG19i5h0h2Kz2w9CvmFSN926YmoNVMsGPgw/edit#heading=h.bcucs532quzv)
- [Scrollable](https://docs.google.com/document/d/1ONoa4fUsqG19i5h0h2Kz2w9CvmFSN926YmoNVMsGPgw/edit#heading=h.kumvf98c675)
- [Select](https://docs.google.com/document/d/1ONoa4fUsqG19i5h0h2Kz2w9CvmFSN926YmoNVMsGPgw/edit#heading=h.kqa04xdsnaaq)
- [Skeleton body text](https://docs.google.com/document/d/1ONoa4fUsqG19i5h0h2Kz2w9CvmFSN926YmoNVMsGPgw/edit#heading=h.1hgpeyws3ofv)
- [Skeleton display text](https://docs.google.com/document/d/1ONoa4fUsqG19i5h0h2Kz2w9CvmFSN926YmoNVMsGPgw/edit#heading=h.j710hdlg2toe)
- [Skeleton page](https://docs.google.com/document/d/1ONoa4fUsqG19i5h0h2Kz2w9CvmFSN926YmoNVMsGPgw/edit#heading=h.ut25c3etfuje)

### Written

- [Color picker](https://docs.google.com/document/d/1ONoa4fUsqG19i5h0h2Kz2w9CvmFSN926YmoNVMsGPgw/edit#heading=h.waqstb88bpql)
- [Footer help](https://docs.google.com/document/d/1ONoa4fUsqG19i5h0h2Kz2w9CvmFSN926YmoNVMsGPgw/edit#heading=h.65257u922p9i) (references link)
- [Page](https://docs.google.com/document/d/1ONoa4fUsqG19i5h0h2Kz2w9CvmFSN926YmoNVMsGPgw/edit#heading=h.ea4enqqhkozj)
- [Page actions](https://docs.google.com/document/d/1ONoa4fUsqG19i5h0h2Kz2w9CvmFSN926YmoNVMsGPgw/edit#heading=h.pqlpfjr6ath0)
- [Pagination](https://docs.google.com/document/d/1ONoa4fUsqG19i5h0h2Kz2w9CvmFSN926YmoNVMsGPgw/edit#heading=h.ojibpzo0nf0n) (references button, link, tooltip)
- [Tabs](https://docs.google.com/document/d/1ONoa4fUsqG19i5h0h2Kz2w9CvmFSN926YmoNVMsGPgw/edit#heading=h.4nehgticx26t)
- [Thumbnail](https://docs.google.com/document/d/1ONoa4fUsqG19i5h0h2Kz2w9CvmFSN926YmoNVMsGPgw/edit#heading=h.lyuh2arbxy82)
- [Tooltip](https://docs.google.com/document/d/1ONoa4fUsqG19i5h0h2Kz2w9CvmFSN926YmoNVMsGPgw/edit#heading=h.hwzhamltdlqi)

### Merged

- Account connection (PR #970, released in 3.7.0)
- Action list (PR #1365, released in 3.14.0)
- Autocomplete (PR #968, released in 3.8.0)
- Avatar (PR #973, released in 3.7.0)
- Badge (PR #1364, released in 3.14.0)
- Banner (PR #1071, released in 3.10.0)
- Button (PR #924, released in 3.8.0)
- Callout card (PR #1366, released in 3.14.0)
- Caption (PR #928, released in 3.6.0)
- Card (PR #1366, released in 3.14.0)
- Checkbox (PR #1145, released in 3.11.0)
- Choice list (PR #1145, released in 3.11.0)
- Collapsible (PR #1631, released in 3.17.0)
- Data table (#927, released in 3.6.0)
- Date picker (PR #2242, released in 4.5.0)
- Description list (PR #1634, released in 3.17.0)
- Display text (PR #1354, released in 3.14.0)
- Drop zone (PR #2243, released in 4.6.0)
- Empty state (PR #2244, released in 4.5.0)
- Exception list (PR #1635, released in 3.17.0)
- Form (PR #1636, released in 3.17.0)
- Heading (PR #1351, released in 3.14.0)
- Icon (PR #1404, released in 3.14.0)
- Inline error (PR #1073, released in 3.10.0)
- Keyboard key (PR #1640, released in 3.17.0)
- Link (PR #924, released in 3.8.0)
- List (PR #1353, released in 3.14.0)
- Loading (PR #1075, released in 3.10.0)
- Modal (PR #1648, released in 3.17.0)
- Option list (PR #1365, released in 3.14.0)
- Popover (PR #1408, released in 3.14.0)
- Radio button (PR #1145, released in 3.11.0)
- Range slider (PR #1630, released in 3.17.0)
- Resource list (#927, released in 3.6.0)
- Setting toggle (PR #970, released in 3.7.0)
- Sheet (PR #1250, released with initial component in 3.14.0)
- Stack (PR #1353, released in 3.14.0)
- Spinner (PR #2243, released in 4.6.0)
- Subheading (PR #1351, released in 3.14.0)
- Tag (PR #1647, released in 3.17.0)
- Text style (PR #1350, released in 3.14.0)
- Text field (PR #968, released in 3.8.0)
- Toast (PR #919, released in 3.11.0)
- Visually hidden (PR #1348, released in 3.14.0)

**Comment by alex-page** [comment]
Nice!
