### ISSUE TITLE
Deprecated usage inside Polaris?

### ISSUE THREAD

**Issue by bakura10** [Shopify/polaris#111]
Hi,

When you try to upgrade to last version of React (15.6), a few warnings are appearing in the console:

<img width="1680" alt="capture d ecran 2017-06-28 a 17 55 13" src="https://user-images.githubusercontent.com/1198915/27647166-fc7697b2-5c2a-11e7-9b28-77b4de2503b0.png">

Not sure if it's directly related to Polaris though.

**Comment by kaelig** [comment]
Hey @bakura10, thank you for reporting this. We've recently made a few dependency upgrades, do you still see the warnings?

We are also looking into upgrading to React v16, which should definitely solve both of these.

**Comment by dfmcphee** [comment]
Hey @bakura10. I believe these warnings should be resolved in the latest versions. I am going to close this but feel free to re-open if you are still seeing the issue.
