### ISSUE TITLE
Navigation component (subNavigationItems)

### ISSUE THREAD

**Issue by AndreyYeryomin** [Shopify/polaris#1119]
I have issue with onClick method in sub navigation item. 
link to code sandbox subNavigationItems https://codesandbox.io/s/lyq9joxl3z?fontsize=14

Are you using the React components? (Y/N): Y
Polaris version number: 3.9.0
Browser: Google Chrome Version 72.0.3626.119
Device: iMac
Operating System: OS X El Capitan ver 10.11.4

**Comment by cloneali** [comment]
I need to investigate further but I think the problem is here: https://github.com/Shopify/polaris-react/blob/bb4b8751b7b5b06b08419d7399bb220da34476dd/src/components/Navigation/components/Item/Item.tsx#L247

I can look into this one if no one is already working on it.

**Comment by yourpalsonja** [comment]
Hey @chloerice, assigning this to you since you mentioned there was another ticket about the same issue, feel free to close either one, or just link the PR to them. Thanks! ❤️

**Comment by dantecatalfamo** [comment]
Is there any update on this issue?

**Comment by dantecatalfamo** [comment]
Is there any update on this issue?

**Comment by chloerice** [comment]
> Is there any update on this issue?

Hey Dante, watch #2640 for updates--It's blocked and I haven't had a free cycle to come back to it. I should have some time after Hack Days as the project I'm on is in transition between phases.

**Comment by dantecatalfamo** [comment]
No wait

**Comment by dantecatalfamo** [comment]
@chloerice Any update on this? 😃

**Comment by chloerice** [comment]
Hey Dante, no update--I'd changed teams and never gotten a chance to get another look. Feel free to dive into the blocked PR!

**Comment by dantecatalfamo** [comment]
Any updates on this? 🙂

**Comment by dantecatalfamo** [comment]
e
