### ISSUE TITLE
Message teams the naming changes to components and removal of elements/composed

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris#118]
- [x] Find out where the communication has happened
- [x] Write a message to send out informing people of the change
- [x] Call to action for feedback
- [x] #124

> Hey hey,
> 
> We recently announced that we are going to breaking components into `elements` and `composed` groups. Through feedback and iteration we have decided to keep them under one definition. There is a huge difference between a resource list and a button however we are not confident enough right now to know the value of breaking these components into two different groups.
> 
> What this means for now:
> - One name, less confusion for our users and team
> - We can explore different ways to document the components _(e.g. surfacing total dependencies)_
> - The Polaris foundations are meant to be owned and maintained by everyone. This encourages this approach.
>
> If you have any feedback or thoughts please jump into our [discussion](https://github.com/Shopify/polaris/discussions/90).

**Comment by alex-page** [comment]
@jjgali I have a draft message here. I am unsure what teams we have messaged or if this message would resonate.

**Comment by jjgali** [comment]
Here are the original posts in Slack:
- [#design-systems-guild](https://shopify.slack.com/archives/C01GMDSTKCP/p1623081391028900)
- [#polaris](https://shopify.slack.com/archives/C4Y8N30KD/p1623081536302600)
- @sarahill any other channels?

We were pretty vague about the terms we added, just confirming that we've put together a glossary around shared terminology, and that we wanted more feedback. I think if we threaded your message, @alex-page , but sent it to the whole channel, that'd be a great way to show we're listening to feedback, and also connect the conversation. 

Making a few tweaks to your draft so it lines up with our original messaging:
>Thanks so much to everyone for your feedback and suggestions! When we first published the glossary, we broke components into `elements` (single components) and `composed components` (groups of components). 
>
>Through feedback and iteration, we've decided to temporarily scale back to one umbrella term—`components`. We understand that there can be a big difference in simple and complex components (for example, a button vs a resource list). However, we're currently not confident in the value of distinguishing these components, nor are we aligned on the best language to use.
>
>What this means for now:
>- One umbrella term, hopefully leading to less confusion for our users and teams
>- We can explore different ways to document components (e.g., surfacing total dependencies)
>
>The Polaris foundations are meant to be owned and maintained by everyone, and your feedback has helped encourage that approach. If you have any additional feedback or thoughts, please jump into our [GitHub discussion](https://github.com/Shopify/polaris/discussions/90)!

Of course make it your own, @alex-page , but those would be my suggestions. 

PS - added an action item to remove `elements` and `composed` from the glossary. Will assign that task to myself.

**Comment by jjgali** [comment]
Replied to @sarahill 's original posts, and sent to the whole channel for greater visibility.
