### ISSUE TITLE
Stack distribution option 'equalSpacing' missing from the doc

### ISSUE THREAD

**Issue by nerfologist** [Shopify/polaris#120]
# Issue summary

The `equalSpacing` option for the Stack elemen't `distribution` prop is not mentioned in the online doc.

## Expected behavior

This option should be mentioned in the online doc, as it allows to fulfill a common layout need.

## Actual behavior

In order to know about this option, one has to inspect the source code.

## Steps to Reproduce the Problem

1. Create a `<Stack />` component with two children (buttons)
2. Look for a way to push one button to the extreme left and the other to the extreme right
3. Inspect the source code for the `<Stack />` component and find [the equalSpacing option](https://github.com/Shopify/polaris/blob/master/src/components/Stack/Stack.tsx#L10).

## Specifications

- Polaris version: 1.1.1
- React version: 15.6.1
- Browser: Version 59.0.3071.115 (Official Build) (64-bit)
- Device: MacBook Pro (Retina, 15-inch, Late 2013)
- Operating System: macOS Sierra version 10.12.5 (16F73)

**Comment by nerfologist** [comment]
Also, the `baseline`option is mentioned in the doc, but not mentioned in the `Distribution` type.

**Comment by lemonmade** [comment]
Thanks for the issue @nerfologist, confirmed that this is the case. We'll get a fix out ASAP!

**Comment by dfmcphee** [comment]
Thanks for the issue @nerfologist. We resolved this a while back but forgot to close the issue. Closing now.
