### ISSUE TITLE
Within an EmbeddedApp tag, a Page won't show breadcrumbs. 

### ISSUE THREAD

**Issue by Taphood** [Shopify/polaris#126]
# Issue Summary

Within `<EmbeddedApp></EmbeddedApp>` tag, a `<Page />` won't show breadcrumbs. 
MyComponent class is nested within EmbeddedApp > Provider > BrowserRouter > Switch tags.
Summary of the code is below. 

```jsx
class MyComponent extends Component {
render () {
  return (
   <Page
       title="Polaris"
       breadcrumbs={breadcrumbs}
       primaryAction={primaryAction}
       secondaryActions={secondaryActions}
   >
   </Page>
 )
}
```
```jsx
<EmbeddedApp
    apiKey={apiKey}
    shopOrigin={shopOrigin}
    debug={true}
>
      <Provider store={store}>
           <BrowserRouter>
                <Switch>
                     <Route path='/mycomp/:number' component={MyComponent}/>
                     <Route exact path='/mycomp' component={MyComponent}/>
                </Switch>
           </BrowserRouter>
      </Provider>
</EmbeddedApp>
```

## Expected behavior
Should show breadcrumbs.

- Polaris version: 1.1.1
- React version:15.5.4
- React DOM:15.5.4
- React Redux version:5.0.5
- React Router version: 4.1.1
- React Router DOM version: 4.1.1
- Browser: any
- Device: any
- Operating System: Mac OS 10.12.5

**NOTE:** 
Without wrapping within `<EmbeddedApp></EmbeddedApp>` tag, breadcrumbs work

**Comment by dfmcphee** [comment]
Hi @Taphood. Thanks for reporting the issue. Can I get some more details here? When wrapped in an `<EmbeddedApp>` component, the header of the page component isn't displayed and instead forwards the information to the EASDK to display outside of the iframe. Are you saying the breadcrumbs don't display at all? Or just not inside the iframe?

**Comment by Taphood** [comment]
hi, team,

I’m on vacation right now outside of the U.S. timezone and limited the internet access. I will come back on Oct/3rd will send you a details.
On Sep 22, 2017, at 2:27 AM, Dominic McPhee <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @Taphood<https://github.com/taphood>. Thanks for reporting the issue. Can I get some more details here? When wrapped in an <EmbeddedApp> component, the header of the page component isn't displayed and instead forwards the information to the EASDK to display outside of the iframe. Are you saying the breadcrumbs don't display at all? Or just not inside the iframe?

**Comment by dfmcphee** [comment]
Hi @Taphood. I'm going to close this but please re-open with more information if this is still an issue.

**Comment by Taphood** [comment]
Hi Dominic

sorry for late reply.  I’m not currently actively developing Shopify app.  I will re-open this when I have more info.
yes go ahead and close this case for now.

Taphood

On Nov 21, 2017, at 7:13 AM, Dominic McPhee <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @Taphood<https://github.com/taphood>. I'm going to close this but please re-open with more information if this is still an issue.
