### ISSUE TITLE
[AutoComplete/TextField][v1] Cursor moves to front and back of input when using up and down arrows for selection 

### ISSUE THREAD

**Issue by adamcarchibald** [Shopify/polaris#1264]
# Issue summary
When using up and down arrows during selection process, the cursor moves to the front and back of the input found in the TextField 

## Expected behaviour 
Cursor should never move when using up and down arrows for selection.

## Actual behaviour

![](https://screenshot.click/2019-03-28_13-13-44.gif)

This is can be replicated at https://polaris.shopify.com/components/forms/autocomplete

**Comment by ry5n** [comment]
Bug confirmed. This may be related to #789.

**Comment by dleroux** [comment]
Autocomplete is currently being reworked as a part of the [AutoComplete component project](https://github.com/Shopify/polaris-react/projects/3). Once we address this problem in the reworked component, we’ll close this issue.
