### ISSUE TITLE
secondaryActions in Page should be disabled by adding 'disabled': true

### ISSUE THREAD

**Issue by Taphood** [Shopify/polaris#127]
# Issue Summary
```javascript
const primaryAction = {content: 'New product', onAction: ()=>{alert("test")}, 'disabled': true };
const secondaryActions = [{content: 'Import', icon: 'import', onAction: ()=>{alert("test")}, 'disabled': true}];
```
```jsx
<Page
  title="Polaris"
  primaryAction={primaryAction}
  secondaryActions={secondaryActions}
>
```
## Expected behavior

The secondaryActions should be disabled by adding 'disabled': true property.

## Specifications

- Polaris version:1.0.1
- React version:15.4.2

**Comment by ry5n** [comment]
Thanks for pointing this out @Taphood. I’ve opened an issue in our internal tracker. I don’t think there are any UX reasons we wouldn’t support this. I’ll keep you posted.

**Comment by mbaumbach** [comment]
Just to add some color to this, the secondary actions currently do disable for the Page component when it's a child of an EmbeddedApp component and you use the `disabled` prop. It's only true when the actions are pulled into the parent frame.

Making those consistent can be factored into any UX debates. :)

**Comment by ry5n** [comment]
This is now fixed 🎉
