### ISSUE TITLE
Page title and a primary action aren't aligned

### ISSUE THREAD

**Issue by molefrog** [Shopify/polaris#128]
# Issue summary
I tried using the `<Page>` component without a breadcrumb and a pagination and it looks a bit odd:
<img width="1130" alt="2" src="https://user-images.githubusercontent.com/671276/28163256-0d95232a-67d3-11e7-9d48-708a91ad45de.png">

It would be nice to have "Pages" title and the primary action button aligned vertically. However, when I add a breadcrumb it looks better:
<img width="985" alt="3" src="https://user-images.githubusercontent.com/671276/28163297-379fccf6-67d3-11e7-8fbd-51e16e0977ee.png">

By the way, we've been able to launch our new dashboard made entirely in Polaris and it's live in Shopify app store now! Great job and thanks for constant updates. For now I ended up using my own component for the page layout, but I would love to switch to Polaris one (even though it doesn't support a subtitle).

<img width="1344" alt="1" src="https://user-images.githubusercontent.com/671276/28163187-be8a57a0-67d2-11e7-8dfb-41ed6d1408a0.png">

## Expected behavior
When breadcrumbs aren't provided the a title and a primary action button are centered vertically.

## Actual behavior
Page title and a primary action go one after another.

## Specifications

- Polaris version: v1.1.1
- React version: v15.5.4
- Browser: Google Chrome 59.0.3071.115
- Device: Mac
- Operating System: OS X

**Comment by ry5n** [comment]
Hey @molefrog! We’ve had this one on our to-do list too 😄. We just finished fixing up several layout issues with `Page` that will be in the next release, due shortly. I’ll leave this issue open until the next release, at which point you should be able to switch back to Polaris’ `Page`.

By the way, Shogun looks really beautiful; great work 🎉

**Comment by ry5n** [comment]
Over a number of releases we’ve made improvements to the alignment of items in the Page component header. I’m going to close this for now, but please re-open if you find a combination of elements that continues to have alignment issues.
