### ISSUE TITLE
Popover content shows under an HTML form field layer

### ISSUE THREAD

**Issue by Taphood** [Shopify/polaris#130]
# Issue Summary

Popover content shows under an HTML form field layer.

## Expected behavior

Popover content should show on the layer above any form field

## Actual behavior

Popover content shows under the layer of a form field

![popover-bug](https://user-images.githubusercontent.com/10623996/28181205-97d8cfc6-67bc-11e7-88e0-ac412b49d434.png)

## Expected behavior

Popover content should show the above layer of a form field

![popover-expected](https://user-images.githubusercontent.com/10623996/28181215-9fb859b4-67bc-11e7-893b-1bda5db9a80e.png)

## Steps to Reproduce the Problem

1. Please use below code.
```jsx
<Stack
  vertical
  spacing="tight"
>
      <Popover
        active=true
        preferredPosition="above"
        activator={
          <Button plain>
          <Stack alignment="leading" spacing="tight">
          <p>{title}</p>
          <img 
            alt={`${title} description`}
            src={require("./../../../images/what.png")} 
            width="16" 
            height="16"
          />
        </Stack>
        </Button>
      }
      sectioned
      >
        <p>this is Popover content. This should be the above layer of any form feild.</p>
      </Popover>
      <TextField
       value={value}
       maxLength="20"
       placeholder="Prod select help"
       onChange={this.valueUpdater('name')}
      />
</Stack>
```

## Specifications

-Polaris version: 1.1.1
-React version:15.5.4
-React DOM:15.5.4
-React Redux version:5.0.5
-React Router version: 4.1.1
-React Router DOM version: 4.1.1
-Browser: any
-Device: any
-Operating System: Mac OS 10.12.5

**Comment by cargix1** [comment]
Hey @Taphood a couple of us had similar issues with the DatePicker and Tooltip, you can view the issue here: https://github.com/Shopify/polaris/issues/107. 

@lemonmade recommended wrapping your elements with:

`<div data-polaris-layer style={{position: relative, z-index: 1}}>`

Hope that helps :)

**Comment by lemonmade** [comment]
I’m going to close this for now. Well make the default behaviour for this better in the future, but for now you can follow the direction in the linked issue.

**Comment by Taphood** [comment]
Thanks cargix1 for your note on #107.  I've tried with z-index div but for some reason, I still couldn't get the Popover content to be shown in a right position.  

yes lemonmade. you can close this issue since I decided to use ESDK Modal window instead.  I'm looking forward to seeing the stacking order default behavior enhancement in a future release
