### ISSUE TITLE
Basic form validation

### ISSUE THREAD

**Issue by bakura10** [Shopify/polaris#131]
Hi !

Polaris provides a lot of validators on form elements that map with native HTML5 element, such as min, max, minLength, pattern...

However it would be useful (especially form pattern), if Polaris could automatically adds listener to the invalid event, and automatically adds an error if a field does not match the given pattern or any other rules. According to the spec, if a validation using "pattern" fails, it should use the error message defined in the "title" attribute.

This alone should be enough to provide 80% of the basic validation stuff, withotu writing boilerplate code.

What do you think ? :)

**Comment by bakura10** [comment]
I've tried to summarize a few ideas that would make basic validations must easier in Polaris:

* Adding a new onInvalid event to all form fields. That would allow to easily add a callback to validate. This only would allows to provide much more flexibility, as we could now add a form element, use "form.checkValidity()" which automatically triggers the validation on all form elements and, for invalid fields, trigger the "invalid" event.

* As said, in addition to that, Polaris could have a basic invalid callback for all input, that would automatically display an error for all fields whose checkValidity returns false.

Do not hesitate to ask me if you need any additional details for our use case :)

**Comment by wub** [comment]
For more complex cases, I'm using Polaris with [Formik](https://github.com/jaredpalmer/formik) and [Yup](https://github.com/jquense/yup), it works great.

**Comment by ry5n** [comment]
Polaris form components are opinionated about how they handle state, in that they don’t—they expect to be controlled components, where you manage the state of the form higher up in the component tree.

This means you’ll need to do validation with your own logic (or separate library) and pass error messages down to the fields in their `error` prop.

We’ve recently added some guidelines around form validation interactions here: https://polaris.shopify.com/patterns/error-messages#section-form-validation

**Comment by daniosTran202** [comment]
> Đối với những trường hợp phức tạp hơn, tôi đang sử dụng Polaris với [Formik](https://github.com/jaredpalmer/formik) và [Yup](https://github.com/jquense/yup) , nó hoạt động rất tốt.

i have any problem from that , how can i get your code or example ? thanks bro so much
