### ISSUE TITLE
Checkbox and checkbox label do not have cursor pointer

### ISSUE THREAD

**Issue by bakura10** [Shopify/polaris#132]
# Issue Summary

Hi,

When using the checkbox component, I would expect the checkbox and associated label to have a cursor: pointer rule to indicate it's clickable. Currently it displays the standard cursor.

Thanks!

EDIT: the same thing happen for select element, which I would expect to have the correct cursor option :).

**Comment by mike-eason** [comment]
Should be a simple fix by adding a `cursor` style on the `.Checkbox` class:

`polaris\src\components\Checkbox\Checkbox.scss`

```css
.Checkbox {
  position: relative;
  cursor: pointer;
}
```

**Comment by ry5n** [comment]
Thanks for the detailed feedback @bakura10. We’re currently reflecting the browser defaults for these elements. Choosing a different cursor is a specific design decision we’ll need to evaluate and decide if we want to implement. I’ve logged this for consideration in our internal queue, but the current behavior isn’t necessarily a bug.

For now, I would recommend _not_ changing this as an override in your apps, to ensure merchants have a consistent experience with using interfaces built with Polaris.

We’ll consider the cursor styling holistically and post back to this issue when we’ve decided on something.

**Comment by babenzele** [comment]
`cursor: pointer` on a checkbox isn't standard. Gmail has `pointer` on the entire email item _except_ for the checkbox. This very site we're on now doesn't use it for their checkboxes. Instagram, Yelp, Reddit...

**Comment by Tiendq** [comment]
@ry5n @babenzele but actually `cursor: pointer` is used in Shopify's apps e.g. Product Reviews

**Comment by ry5n** [comment]
We’re not always perfectly consistent. As Polaris continues to be applied across the ecosystem (including our own apps), we’ll get closer.

Closing this, as the original issue is now closed.

**Comment by babenzele** [comment]
@ry5n you're right! I didn't think to check shopify.

**Comment by ry5n** [comment]
@Tiendq no worries. Thanks for bringing it up!
