### ISSUE TITLE
DatePicker appearing in the worng location on long pages

### ISSUE THREAD

**Issue by cargix1** [Shopify/polaris#143]
# Issue summary

When having to scroll to activate a DatePicker component it appears in the wrong place. 

## Expected behavior

I'd expect the DatePicker to appear just above/below the field that was clicked to activate it. 

## Actual behavior

When I click to activate the DatePicker component the browser shoots upwards causing the DatePicker to display in the wrong location. I'm thinking a simple call to e.preventDefault() would solve this, but it doesn't appear that we are getting the click event passed through the component. I'm wondering if this is similar to what @bakura10 described in https://github.com/Shopify/polaris/issues/135?

<img width="1495" alt="screen shot 2017-07-19 at 21 17 42" src="https://user-images.githubusercontent.com/9730290/28388127-86edee3c-6cc9-11e7-877e-4b1d59282031.png">

<img width="1559" alt="screen shot 2017-07-19 at 21 17 16" src="https://user-images.githubusercontent.com/9730290/28388134-8a591218-6cc9-11e7-9a31-69305614cad1.png">

## Steps to Reproduce the Problem

1. Within an AnnotatedSection create a sectioned Card and push the DatePicker component down the page so you have to scroll to see it. In this example I created an empty DIV with a height of 1000px to simulate this.  

```
<Layout.AnnotatedSection title="Store Pickup">
        
        <Card sectioned>
          <div style={{height: "1000px"}}></div>
          <p>Prevent customers from selecting pickups from this outlet on specific dates of the year.</p><br/>
          <div data-polaris-layer style={{position: 'relative', zIndex: 1}}>
            <Popover
              preferredPosition="below"
              activator={
                <TextField
                  type="text"
                  label="Date"
                  connectedRight={<Button icon="add">Add blackout date</Button>}
                />
              }
            >
              <DatePicker
                month={5}
                year={2017}
              />
            </Popover>
          </div>
        </Card>

      </Layout.AnnotatedSection>
```

2. Scroll down the page, activate the DatePicker and notice how the page jumps to the top and the DatePicker appears in the wrong place. 

## Specifications

- Polaris version: 1.1.1
- React version: 15.6.1
- Browser: Chrome
- Device: Macbook Pro
- Operating System: Sierra 

**NOTE:** This repo is only used for reporting issues and new feature requests. We are not accepting pull requests at this point in time.

**Comment by lemonmade** [comment]
@cargix1 thanks for the issue. I was able to reproduce, and we'll get a fix in for this ASAP.

**Comment by bakura10** [comment]
Hi,

I have a somewhat similar issue with Tooltip:

<img width="1391" alt="capture d ecran 2017-07-21 a 22 09 44" src="https://user-images.githubusercontent.com/1198915/28480526-5da1e3be-6e61-11e7-86e2-23c03bfe2107.png">

**Comment by cgenevier** [comment]
I'm having this same issue. Any updates?

**Comment by dfmcphee** [comment]
@cargix1 can you confirm if this is still happening in the latest version of Polaris?

**Comment by cargix1** [comment]
Hey @dfmcphee it seems to be working great this end now thanks :)

**Comment by dfmcphee** [comment]
Great, thanks!
