### ISSUE TITLE
Version 1.2.0-beta.2 is missing in public GitHub repo

### ISSUE THREAD

**Issue by nerfologist** [Shopify/polaris#144]
# Issue summary

The 1.2.0-beta.2 release is published on npmjs.com, but missing on this public repo.

## Expected behavior

The latest published release should be visible.

## Actual behavior

The latest published release is not visible.

## Steps to Reproduce the Problem

Check [latest published version on npmjs](https://www.npmjs.com/package/@shopify/polaris). It is currently **1.2.0-beta.2**.
Check [latest release on the public GitHub repo](https://github.com/Shopify/polaris/releases). It is currently **1.1.1**.
Latest npmjs release is missing from the GitHub repo.

## Specifications

- Polaris version: 1.2.0-beta.2

**Comment by lemonmade** [comment]
Hey @nerfologist, sorry for the confusion. We accidentally published the beta as `latest`. I've made it so `1.1.1` is the latest again. We'll add the new code to this repo once we ship a stable version of 1.2.0.
