### ISSUE TITLE
Checkbox error message to be aligned with form checkbox element instead of label

### ISSUE THREAD

**Issue by Taphood** [Shopify/polaris#146]
# Issue summary

```jsx

<Checkbox 
	label="Go to next panel"
	checked={this.props.button.action === 'next'}
	onChange={this.valueUpdater('action')}
	disabled={ this.delCheckBoxDisabled(this.props.button) && true}
	error={this.props.buttonError.label}
/>
```

## Expected behavior
It is nice if I can vertical align the error message with the checkbox as shown in the picture.
If the default behavior is to align the error message with the label, then can we have an option property to support the alignment with the form checkbox element (see the picture below)?

<img width="274" alt="screen shot 2017-07-21 at 11 16 05 am" src="https://user-images.githubusercontent.com/10623996/28485462-9eb548ce-6e2e-11e7-9c07-eb11410c5659.png">

## Actual behavior
Error message is aligned with Checkbox label instead of the form checkbox

<img width="350" alt="screen shot 2017-07-21 at 11 15 51 am" src="https://user-images.githubusercontent.com/10623996/28485465-a2a9cef0-6e2e-11e7-9b08-63a55580ef51.png">

## Steps to Reproduce the Problem
use the code above to see the output

## Specifications

- Polaris version:1.1.1
- React version:15.5.4
- React DOM version:15.5.4
- Browser: Any
- Device: Any
- Operating System: Mac OS 10.12.5

**Comment by ry5n** [comment]
The help text for the checkbox and radio buttons is intended to align with the label, for cases like this:
![screen shot 2017-08-01 at 11 58 34 am](https://user-images.githubusercontent.com/804014/28834646-d65fdda4-76b0-11e7-8469-4b6569536415.png)

The error message is in turn aligned with the help text. In your case it does feel a bit off, I agree, but I’m not sure how to resolve the two. We’ll keep this in mind and return to it at some point, but we don’t have plans to revisit this particular detail right now.

**Comment by Taphood** [comment]
How about adding a property for the error message alignment position, either alignment with the label or the radio/checkbox?

-Yukari
