### ISSUE TITLE
EmptyState does not work if no action

### ISSUE THREAD

**Issue by bakura10** [Shopify/polaris#150]
# Issue summary

Hi,

I'd like to use the EmptyState as a way to provide a visual dashboard, similar to what Shopify does in its home page. I do not want to have a main action button.

## Expected behavior

Empty State should work if no "action" is defined.

## Actual behavior

It throws an exception if no action is defined.

## Specifications

- Polaris version: 1.1.1
- React version: 15.6
- Browser: Chrome

**Comment by ry5n** [comment]
Hey @bakura10. EmptyState isn’t really meant for something like the Shopify admin home screen. EmptyState is intended to be used on pages where content would normally appear (like a product or customer list) but where there are no items yet. (In such a case, the action is really important to provide merchants with next steps.)

Depending on your merchants’ specific needs, you might be best served by creating some new components and/or layouts (perhaps based on existing Polaris components).

**Comment by bakura10** [comment]
Thanks for the info, definitely will do that :).

**Comment by ry5n** [comment]
Awesome. Let us know if you have more questions. Always happy to help.

**Comment by bakura10** [comment]
Actually, after giving it a bit more thought, I would like to use the EmptyState as the on-boarding when the app is first installed and where nothing has been configured. However in this context, the EmptyState adds a top border:

<img width="1105" alt="capture d ecran 2017-07-26 a 15 34 36" src="https://user-images.githubusercontent.com/1198915/28623997-f9ad4d48-7217-11e7-94f5-6ea1320cb632.png">

I think this border should be removed if the Empty state is the only child of the parent.

What do you think ?

**Comment by ry5n** [comment]
Ah, yes. We’ve fixed that border in our pre-release build and it will be gone in the next release, available very shortly.
