### ISSUE TITLE
ResourceList does not render item as per doc

### ISSUE THREAD

**Issue by bakura10** [Shopify/polaris#152]
# Issue summary

Hi,

If I follow the documentation of ResourceList (https://polaris.shopify.com/components/lists/resource-list#navigation) the code should display the list item as per the example.

## Actual behavior

Instead, because of the render function being empty, nothing is rendered. If I remove the renderFunction (hoping it would default to some sane defaults), it throws an exception due to missing render item function.

## Specifications

- Polaris version: 1.1.1
- React version: 15.6

**Comment by bakura10** [comment]
EDIT : got it, the doc is not up to date with this document: https://github.com/Shopify/polaris/tree/master/src/components/ResourceList

I leave this issue open for now :).

**Comment by ry5n** [comment]
Hey @bakura10, you’re right. Looks like an issue with the polaris site—the example code is loaded directly from that readme file, so something must be displaying wrong. We’re looking into it.

**Comment by recio862** [comment]
It looks like the renderItem function needs to be updated from:

`renderItem={() => {}}`

to 

```
  renderItem={(item, index) => {
    return <ResourceList.Item key={index} {...item} />;
  }}
```

**Comment by ry5n** [comment]
You’re totally right.

The content for each component page on polaris.shopify.com is parsed from the README in the codebase. [The one for ResourceList is correct](https://github.com/Shopify/polaris/blob/master/src/components/ResourceList/README.md#simple-resource-list), so it looks like it’s not getting parsed correctly.

We’ll get this fixed. Thanks for flagging it!

**Comment by dfmcphee** [comment]
This is resolved in the latest resource list documentation: https://polaris.shopify.com/components/lists/resource-list
