### ISSUE TITLE
Demonstrate layout through video demo

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris#152]
Goals:
- Show current limitations of our layout today
- Show new approach
- Call to action for feedback, ideas

How we'll do it:
- [x] Write the story (Jose (everyone else as needed))
- [x] Design the layout (Sara and Jose)
- [x] Create 2 code demos (Aveline)
  - [x] using existing Polaris
  - [x] using new layout approach
- [x] (stretch goal) set up a sandbox that people can play with the demo directly
- [x] Build out/finish layout components needed for the demo
- [x] Edit demo video

**Comment by zecarlostorre** [comment]
First draft of the story[ in here](https://docs.google.com/document/d/1Zd_o48FyHHiTGH5WJKlRj-1U9Obn7MVeOSaovyGfwr8/edit#)

**Comment by aveline** [comment]
<img width="400" alt="Screen Shot 2021-07-14 at 4 43 10 PM" src="https://user-images.githubusercontent.com/3474483/125706455-25e32755-4fb1-414f-9a70-881b2e71627b.png">

Here is the in progress screenshot of the latest design built with existing Polaris components. I am trying to see how far I can get without writing any custom CSS whatsoever, but it's looking a bit grim! Any suggestions on existing components I may not have thought to use would be very welcome.

**Comment by alex-page** [comment]
Did a quick iteration using `<Page>` component:
![Screen Shot 2021-07-14 at 8 01 48 PM](https://user-images.githubusercontent.com/19199063/125721244-b150f4f2-8fcc-45b5-9111-591ef347a1e8.png)

**Comment by aveline** [comment]
Paired with @lgriffee and got some feedback from @zecarlostorre and we settled on this for the existing Polaris version

<img width="405" alt="Screen Shot 2021-07-15 at 10 05 22 AM" src="https://user-images.githubusercontent.com/3474483/125828420-43dff785-2c55-4435-8956-71724238129b.png">

**Comment by aveline** [comment]
This is the first pass with the foundation components, focusing on just getting the content in, no writing any custom CSS. Compare the difference with the same first pass with the Polaris components.

<img width="430" alt="Screen Shot 2021-07-15 at 1 00 45 PM" src="https://user-images.githubusercontent.com/3474483/125850393-ab9cd835-456f-4648-9583-bbc0e05ce9ad.png">|<img width="400" alt="Screen Shot 2021-07-14 at 4 43 10 PM" src="https://user-images.githubusercontent.com/3474483/125706455-25e32755-4fb1-414f-9a70-881b2e71627b.png">
:----:|:----:
Foundations | Polaris

**Comment by aveline** [comment]
Just wanted to post the in progress screen before wrapping up for the day. It's getting closer! Thanks for pairing with me to get it to this point @yurm04!

<img width="400" alt="Screen Shot 2021-07-15 at 4 08 22 PM" src="https://user-images.githubusercontent.com/3474483/125869167-49507de9-84e5-438c-b38e-0f6d1e0e1e2f.png">

**Comment by sarahill** [comment]
We created a comms plan with some text to share out along with the video and are planning to share it out on Monday https://docs.google.com/document/d/12gNxeqvpQndtdtoCUzftnKauyzuuRFHn-6M0ZJ1_RqE/edit#
