### ISSUE TITLE
Resource list pointer-events

### ISSUE THREAD

**Issue by bakura10** [Shopify/polaris#155]
# Issue summary

If a resource list contains a link it should be clickable.

## Expected behavior

I have the following code:

```jsx
<ResourceList
                    items={[
                      {
                        media: <Thumbnail
                          source="https://burst.shopifycdn.com/photos/black-leather-choker-necklace_373x@2x.jpg"
                          size="small"
                          alt="Black Choker Necklace"
                        />,
                        attributeOne: <Link to="#">Black Choker Necklace</Link>,
                        attributeThree: <TextStyle variation="subdued">Scheduled 3 times</TextStyle>,
                      },
                    ]}
                    renderItem={(item, index) => {
                      return <ResourceList.Item key={index} {...item} />;
                    }}
                  />
```

I would expect the cursor to become a pointer when I hover the attribute one.

## Actual behavior

Due to the pointer-events: none set on the Polaris-ResourceList__Container class, the link behaves like if it was not a link.

## Specifications

- Polaris version: 1.1.1
- React version: 15.6

**Comment by ry5n** [comment]
It turns out that `Resource.Item` takes a `url` prop, in which case the entire list item will be clickable (and will have `cursor: pointer`. You can do something like:

```

<ResourceList
  items={[
    {
      url: 'path/to/product',
      media: <Thumbnail
        source="https://burst.shopifycdn.com/photos/black-leather-choker-necklace_373x@2x.jpg"
        alt="Black choker necklace"
      />,
      attributeOne: 'Elegant necklace',
      attributeTwo: 'Accessory by Marcuse',
      attributeThree: '12 in stock',
    },
  ]}
  renderItem={(item, index) => {
    return <ResourceList.Item key={index} {...item} />;
  }}
/>
```

This is the basic intended behavior, to have the whole item link to the resource in question. The way this is currently implemented it’s not possible to embed additional clickable elements inside the item. We’re working on a fix for this.

**Comment by ry5n** [comment]
@bakura10 Did this help resolve the issue for you?

**Comment by bakura10** [comment]
Hi,
Kinda, but if would definitely be nice to remove the whole like clickable behaviour and specify it for a specific property. But I'm closing this for now as it can be work around.

**Comment by jagthedrummer** [comment]
I need to put a destructive button inside a resource list item and we don't want the entire item to trigger the destructive action. I can work around this with custom CSS but it would be nice to have a "blessed" way of doing this.

**Comment by ry5n** [comment]
@jagthedrummer `Resource.Item` has an `actions` prop that displays actions on hover. These are intended as shortcuts for things users can already do on the detail view for each resource, and so aren’t available on small/touch screens. If a resource doesn’t have a detail view (the item doesn’t have a URL/not clickable) then you can set the `persistActions` prop to true and the actions will be visible all the time (and roll up to an overflow menu on small/touch screens).

We’re working on better documentation for this. For now, here’s one of the examples from the Polaris site:

```jsx
<ResourceList
  items={[
    {
      url: 'path/to/item',
      media: <Thumbnail source="path/to/image" alt="Black choker necklace" />,
      attributeOne: 'Elegant necklace',
      attributeTwo: <TextStyle variation="subdued">No variants</TextStyle>,
      actions: [{content: 'View listing'}],
      persistActions: true,
    },
  ]}
  renderItem={(item, index) => {
    return <ResourceList.Item key={index} {...item} />;
  }}
/>
```

The individual actions you can pass accept these props: `content`, `accessibilityLabel`, `url`, `onAction` and `disabled` (actions are of [type `DisableableAction`](https://github.com/Shopify/polaris/blob/master/src/types.ts#L24)).

**Comment by jagthedrummer** [comment]
@ry5n, thanks for the info, but unfortunately I'm using the HTML version of stuff. Is there an easy translation to it?

**Comment by ry5n** [comment]
On of the examples (available via the dropdown) on the Polaris site will have markup close to what you want. It’s the third one, that says “for channels”. You can always tweak the React code to get closer to what you want and then switch to the HTML to see the output.

**Comment by jagthedrummer** [comment]
Ah-ha! I thought I had checked all the available options there, but I obviously missed it. Thanks again, @ry5n! The quick response is much appreciated.

**Comment by embedded1** [comment]
@ry5n can I mark that the URL should be opened in new tab?
I need to use external URL.

**Comment by ry5n** [comment]
@embedded1 I’m curious about your use case—Resource List items should be either core Shopify objects (Orders, Customers, etc), or something in your app, in which case they shouldn’t need to open in a new tab. In any case, that option isn’t provided by the standard resource item.

However, the design of ResourceList is extensible. For now I’d recommend making a new component based on [the standard resource item](https://github.com/Shopify/polaris/blob/master/src/components/ResourceList/Item.tsx) that has the behaviour you want, and use it in `renderitem`.

**Comment by embedded1** [comment]
@ry5n we're developing a unique app that requires to show external data (tracking data)
We're using the html version, can you show me how to make a click open a URL on new tab?

**Comment by ry5n** [comment]
Ideally resource list items should link to a separate detail page within your app. If that makes sense for your app, you could link to an external site using the item’s secondary actions. Try pasting this example into one of the playgrounds on the [Polaris site](https://polaris.shopify.com/components/lists/resource-list#navigation) to see what I mean:

```
<ResourceList
  items={[{
      url: '#',
      media: <Thumbnail
        source="https://burst.shopifycdn.com/photos/black-leather-choker-necklace_373x@2x.jpg"
        alt="Black choker necklace"
      />,
      attributeOne: 'Elegant necklace',
      attributeTwo: 'Accessory by Marcuse',
      attributeThree: '12 in stock',
      actions: [{content: 'View tracking data'}],
      persistActions: true,
    }]}
  renderItem={() => {}}
/>
```

Since you’re not using React, you’d need to implement the behavior where the actions roll up to an ellipsis menu on small screens.

If you just want to make the main resource item open in a new tab you can add `target` and `rel` attributes to the anchor tag within the item (some attributes omitted for clarity):

```
<a class="Polaris-ResourceList__Link" href="http://example.com" target="_blank" rel="noopener noreferrer">
  …
</a>
```

The `rel="noopener noreferrer"` avoids [a security issue](https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/) where the target gains some access to your page, so make sure to include it.
