### ISSUE TITLE
TextStyle strong uses 700 instead of 600

### ISSUE THREAD

**Issue by bakura10** [Shopify/polaris#156]
# Issue summary

Hi,

Polaris seems to use the incorrect font weight when the TextStyle is used.

## Expected behavior

Polaris seems to use mostly the font-weight 600 for most "bolded" element. I'd expect this:

```jsx
<TextStyle variation="strong">Hello</TextStyle>
```

to use the font weight 600.

## Actual behavior

Instead, this leads to font-weight 700, which caused strange visual when compared to other bold elements:

<img width="643" alt="capture d ecran 2017-07-27 a 12 54 44" src="https://user-images.githubusercontent.com/1198915/28667196-c9e3e53c-72ca-11e7-8d63-e669c7d1c630.png">

## Specifications

- Polaris version: 1.1.1
- React version: 15.6

**Comment by dfmcphee** [comment]
Thanks for the issue @bakura10. I have created a ticket on our internal issue tracker to have this updated. I will close this once it has been released.

**Comment by dfmcphee** [comment]
This is fixed in v1.2.1
