### ISSUE TITLE
PageActions after a list of sectioned layout

### ISSUE THREAD

**Issue by bakura10** [Shopify/polaris#157]
# Issue summary

Shopify sometimes have two consecutive sectioned layout followed by page actions:

<img width="1150" alt="capture d ecran 2017-07-27 a 14 29 03" src="https://user-images.githubusercontent.com/1198915/28670211-f80ab762-72d7-11e7-84bd-f070cdc3f4b2.png">

## Expected behavior

The following code should display something similar:

```jsx
<Page>
  <Layout>
    <Layout.AnnotatedSection/>
    <Layout.AnnotatedSection/>
  </Layout>

  <PageActions
      primaryAction={{content: 'Save'}}
  />
</Page>
```

## Actual behavior

When used this way, the page actions does not apply margin top:

<img width="1037" alt="capture d ecran 2017-07-27 a 14 30 33" src="https://user-images.githubusercontent.com/1198915/28670259-2c553056-72d8-11e7-8a5a-1781f8c1fc0d.png">

## Specifications

- Polaris version: 1.1.1
- React version: 15.6

**Comment by dfmcphee** [comment]
Hey @bakura10. Thanks for the issue. The proper way to do this is to include the `<PageActions>` within a `<Layout.Section>` inside of the same layout component.

```
<Page>
  <Layout>
    <Layout.AnnotatedSection/>
    <Layout.AnnotatedSection/>
    <Layout.Section>
       <PageActions
          primaryAction={{content: 'Save'}}
       />
    </Layout.Section>
  </Layout>
</Page>
```

This should give you the correct margins and layout on the page actions as well.
