### ISSUE TITLE
Usage of resource list and subdued section within a card

### ISSUE THREAD

**Issue by bakura10** [Shopify/polaris#158]
# Issue summary

Hi, it's me again for more reports ^^.

We are looking to use the resource list inside a card, with a subdued footer card section.

## Expected behavior

Considering the following code:

```jsx
<Card title="Variants">
              <Card.Section>
                <ResourceList
                  items={[
                    {
                      url: '#',
                      media: <Thumbnail
                        source="https://burst.shopifycdn.com/photos/black-leather-choker-necklace_373x@2x.jpg"
                        alt="Black choker necklace"
                      />,
                      attributeOne: 'Elegant necklace',
                      attributeTwo: 'Accessory by Marcuse',
                      attributeThree: '12 in stock',
                    },
                  ]}
                  renderItem={(item, index) => {
                    return <ResourceList.Item key={index} {...item} />;
                  }}
                />
              </Card.Section>

              <Card.Section subdued>
                <p>
                  This is a text
                </p>
              </Card.Section>
            </Card>
```

The resource list is unfortunately incorrectly padded due to the fact it's within a card section:

<img width="664" alt="capture d ecran 2017-07-28 a 14 48 51" src="https://user-images.githubusercontent.com/1198915/28717888-e40770bc-73a3-11e7-8246-1674c4ec9425.png">

Moving the ResourceList outside the card section:

```jsx
<Card title="Variants">
                <ResourceList
                  items={[
                    {
                      url: '#',
                      media: <Thumbnail
                        source="https://burst.shopifycdn.com/photos/black-leather-choker-necklace_373x@2x.jpg"
                        alt="Black choker necklace"
                      />,
                      attributeOne: 'Elegant necklace',
                      attributeTwo: 'Accessory by Marcuse',
                      attributeThree: '12 in stock',
                    },
                  ]}
                  renderItem={(item, index) => {
                    return <ResourceList.Item key={index} {...item} />;
                  }}
                />

              <Card.Section subdued>
                <p>
                  This is a text
                </p>
              </Card.Section>
            </Card>
```

Properly fixes the padding issue, but now the subdued card section lacks the top border to create the proper separation and lacks top padding between card title and resource list:

<img width="662" alt="capture d ecran 2017-07-28 a 14 50 05" src="https://user-images.githubusercontent.com/1198915/28717939-15b33830-73a4-11e7-91f5-739310665be3.png">

**Comment by amythibodeau** [comment]
CC @ry5n

**Comment by ry5n** [comment]
This is an interesting problem. We definitely need a fix for this—I’ll log an issue in our internal bug tracker and I’ll let you know what the fix is. As a workaround, your best bet might be to create a `Separator` component that has the same border style.

**Comment by dfmcphee** [comment]
Hey @bakura10. We now accept a `fullWidth` prop on `Card.Section` that will allow for these layouts as of `v2.0.0-beta.8`. You can find the documentation for it here: https://polaris-v2.shopify.com/components/structure/card.

Let us know what you think. If there's something missing for your needs, or otherwise have feedback, feel free to re-open this issue and add a comment, or create a new issue in the repo. Thanks!
