### ISSUE TITLE
Page alignment broke in Polaris 1.2.1

### ISSUE THREAD

**Issue by bakura10** [Shopify/polaris#160]
# Issue summary

Page with layout does not display appropriate padding.

## Expected behavior

In Polaris 1.1.1, the page content had both a top and bottom margin:

<img width="1635" alt="capture d ecran 2017-07-29 a 14 53 55" src="https://user-images.githubusercontent.com/1198915/28744973-cfd3c8be-746d-11e7-8246-0cc7d12202a6.png">

After the switch to 1.2.1, the top margin has been removed, which introduce the whole content to be stuck to the top:

<img width="1573" alt="capture d ecran 2017-07-29 a 14 54 27" src="https://user-images.githubusercontent.com/1198915/28744975-e58254dc-746d-11e7-8583-52f0a6f9d8f3.png">

## Specifications

- Polaris version: 1.2.1
- React version: 15.6

**Comment by dfmcphee** [comment]
Thanks for the issue @bakura10. I have added this to our internal issue tracker and will update here when we have a fix.

**Comment by dfmcphee** [comment]
This should be fixed in `1.4.0`.
