### ISSUE TITLE
Two "hidden" groups in Title and text

### ISSUE THREAD

**Issue by KevinGutowski** [Shopify/polaris#161]
# Issue summary
In Web.UIKit.sketch There are two groups that are behind the grey background that are just copies of _Ink_ and _Subdued_. 

![hidden groups](https://user-images.githubusercontent.com/4199296/28845145-e2c71fde-76bb-11e7-9436-d6190117bb96.png)

## Expected behavior

For clarity, it would be nice to have them removed. Cheers!

**Comment by jessebc** [comment]
Thanks for catching that. I've just created an internal issue to get that fixed up for the next release.

**Comment by sarahill** [comment]
Removed the hidden layers! This will be in the next release of the Web UI Kit.
