### ISSUE TITLE
TextInput number type disabled setting bug, inc/dec arrows are still enabled

### ISSUE THREAD

**Issue by kguller** [Shopify/polaris#163]
# Issue summary

> TextInput type="number" disabled does disable the input text box, but it fails to restrict the increment/decrement arrow buttons on the right side.  I am able to alter the value

Provide a high-level summary of your issue or feature request.

## Expected behavior

The arrow buttons should be disabled to prevent a value change.

## Actual behavior
The arrow buttons are enabled regardless of the disabled property setting and change the text value.

## Steps to Reproduce the Problem
<TextField type="number"
                         label="X Position"
                         placeholder="Enter X position"
                         disabled={true}
                         suffix="px"
                         error={this.state.errors[name]}
                         value={media.draw.x}
                         onChange={(newValue) => this.handleValidate({name:'option.view.x',value:newValue})}/>          
         

## Specifications

- Polaris version:  @shopify/polaris@1.2.1
- React version:  react@15.6.1
- Browser: All
- Device: Any
- Operating System: All

![image](https://user-images.githubusercontent.com/1985853/29054924-28e591b6-7bae-11e7-85ba-bc8d3d64b512.png)

**Comment by ry5n** [comment]
Wooops, thanks for catching this @kguller! I’ve logged this in our bug tracker and we’re already working on a fix. Look for that in the next release.

**Comment by dfmcphee** [comment]
Fixed in 1.3.0
