### ISSUE TITLE
Sketch UI Kit - No symbols are rotated

### ISSUE THREAD

**Issue by heyneff** [Shopify/polaris#165]
# Issue summary
No symbols are rotated

## Expected behavior
The No symbol's cross bar should be from upper left to lower right. 
https://en.wikipedia.org/wiki/No_symbol
![150px-prohibitionsign2 svg](https://user-images.githubusercontent.com/3827051/29097916-5edb23e6-7c51-11e7-8a0e-dd0d98233a0f.png)

## Actual behavior
![current](https://user-images.githubusercontent.com/3827051/29097868-13188016-7c51-11e7-8f0e-f41f2535d449.png)
In v1.2.1 of the Web.UIKit.sketch the symbol is rotated 90° from how it should be displayed. It appears this way on these artboards:
Components > 🖥 Feedback indicators - Banners
Components > 📱 Feedback indicators - Banners
Examples  - Core > Order Show 1
Examples  - Core > Order Show 2
Examples  - Core > Order Show 3
Examples  - Core > Order Show 4
Symbols > Components/Banner/Title & CTA/Red
Symbols > Components/Banner/Title/Red

## Specifications

- Polaris version: v1.2.1

**Comment by heyneff** [comment]
👍  Keep up the good work!

**Comment by jessebc** [comment]
This has been fixed in an internal build.
