### ISSUE TITLE
Icon examples only show "Default Icon"

### ISSUE THREAD

**Issue by pbojinov** [Shopify/polaris#167]
# Issue summary

The Icon "Examples" section only shows one example icon, the "Default Icon". 

It is currently not possible to see what available icons there through the documentation - https://polaris.shopify.com/components/images-and-icons/icon#examples

## Expected behavior

The "Examples" section dropdown list should have all available icons listed, with the visual example below updating when a new icon is selected from the dropdown list.

## Actual behavior

Only one icon is listed in the dropdown, "Default Icon". The icons from the repo should be listed somewhere in the examples - https://github.com/Shopify/polaris/tree/master/src/icons

## Steps to Reproduce the Problem

1. Go to Icon Examples section - https://polaris.shopify.com/components/images-and-icons/icon#examples
2. Only "Default Icon" example is available. 

## Specifications

- Polaris version: 1.3.1
- React version: 15.5.3
- Browser: Chrome Version 60.0.3112.90 
- Device: MBPR
- Operating System: macOS Sierra 10.12.6

**Comment by ry5n** [comment]
@pbojinov Thanks for bringing this up. I know it’s a pain for the moment. We have this on our todo list. For the moment, you can take a look at [the source icons](https://github.com/Shopify/polaris/tree/master/src/icons) for what’s available. The prop names are camelCase, where the filenames are snake-case, so for `arrow-left.svg` you’d use `<Icon source="arrowLeft" />`

**Comment by bodaz** [comment]
+1, also are plans to add more icons in the near future? Or plans to support/integrate with another icons library?

**Comment by ry5n** [comment]
There are plans to add more icons in future. That’s a good call to add a link to the source folder in the docs.

**Comment by dfmcphee** [comment]
The icon examples now show all possible options in the playground: https://polaris.shopify.com/components/images-and-icons/icon

**Comment by roark** [comment]
This still seems to be an issue. 

I don't see all Icons available in the docs or the playground. Yes, you can try out different icons in the playground but nowhere does it list ALL available icons.

In fact even all the SVGs present in the folder mentioned in the original post are not all available. For example `menu` and `ellipsis` are not available.

To find the actual list I had to dig into the Icon component itself. 
https://github.com/Shopify/polaris/blob/master/src/components/Icon/Icon.tsx

I believe this list should be added to the docs. As of writing this the list is:
```
  add,
  alert,
  arrowDown,
  arrowLeft,
  arrowRight,
  arrowUp,
  arrowUpDown,
  calendar,
  cancel,
  cancelSmall,
  caretDown,
  caretUp,
  checkmark,
  chevronDown,
  chevronLeft,
  chevronRight,
  chevronUp,
  circleCancel,
  circleChevronDown,
  circleChevronLeft,
  circleChevronRight,
  circleChevronUp,
  circlePlus,
  conversation,
  deleteIcon,
  disable,
  dispute,
  duplicate,
  embed,
  exportIcon,
  external,
  help,
  horizontalDots,
  importIcon,
  notes,
  notification,
  print,
  refresh,
  risk,
  save,
  search,
  subtract,
  view
```

**Comment by lemonmade** [comment]
This list is available in the properties pane of the link Dominic posted above.

**Comment by roark** [comment]
Wow, you are right. Not sure how I missed that. My apologies, thanks!

I also see the `ellipsis` icon can be found as `horizontalDots`... Any chance that the `menu` icon or a `handle` icon will be added sometime in the not so distant future? Cheers.

**Comment by kaelig** [comment]
Polaris icons are now all available via a new npm package called `@shopify/polaris-icons`. Find them alongside usage instructions at https://polaris-icons.shopify.com 💟
