### ISSUE TITLE
[a11y] Drop zone error has low contrast

### ISSUE THREAD

**Issue by dpersing** [Shopify/polaris#1675]
_Copying over from https://github.com/Shopify/polaris-ux/issues/245_

# Update drop zone error text

## Problem

Error text in a drop zone does not quite pass accessibility standards.

https://github.com/Shopify/polaris-ux/issues/214#issuecomment-475351050

Related to: https://github.com/Shopify/polaris-ux/issues/162

## Solution

Use `red dark` for the error text here instead.

## Examples

<img width="327" alt="Screen Shot 2019-03-21 at 1 40 05 PM" src="https://user-images.githubusercontent.com/8629173/54775981-8441a780-4be5-11e9-952a-296ccc419f1d.png">

<img width="508" alt="Screen Shot 2019-03-21 at 11 21 21 AM" src="https://user-images.githubusercontent.com/8629173/54775982-84da3e00-4be5-11e9-9435-e1de89b3b3ad.png">

**Comment by tjonx** [comment]
Resolved in Polaris v6
