### ISSUE TITLE
ResourceList shift-click multiselect does not work in Firefox when clicking checkbox square

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris#1691]
## Issue summary

When you click a checkbox then hold shift and click in another checkbox it doesn't select anything in firefox. Clicking the area outside of the square seems to work.

## Expected behavior

Clicking the checkbox when in multiselect should select the element and the items between.

## Actual behavior

Clicking the checkbox when in multiselect does not select the item and the items between.

## Steps to reproduce the problem

1. Firefox -> Multiselect
1. Select first item
1. Hold shift and click inside third checkbox

**Comment by carysmills** [comment]
Fyi this is my fix on our forked version: https://github.com/Shopify/web/pull/15228/files

**Comment by alex-page** [comment]
@carysmills nice we have a PR here as well:
https://github.com/Shopify/polaris-react/pull/1706

**Comment by alex-page** [comment]
Can confirm this is still broken.
