### ISSUE TITLE
Typings for ResourceList.Item actions do not match actual functionality

### ISSUE THREAD

**Issue by Anveio** [Shopify/polaris#171]
# Issue summary

The [Props interface for a ResourceList.Item](https://github.com/Shopify/polaris/blob/master/src/components/ResourceList/Item.tsx#L42) specifies that `actions` is a `DisableableAction[]`. However you can pass valid properties for a `Button` component to change the functionality of the `ResourceList.Item` such as `primary={true}` or  `icon='add'`. I believe this is [because `Item` calls the function `buttonsFrom`](https://github.com/Shopify/polaris/blob/master/src/components/ResourceList/Item.tsx#L152) with the passed in `actions`. `buttonsFrom` [then spreads the passed in action into a `Button` component](https://github.com/Shopify/polaris/blob/master/src/components/Button/Button.tsx#L140).

## Expected behavior

The documentation should match this functionality. I've personally found this functionality desirable so I would like to not see it removed, but I would expect to be able to do this without type casting or some other workaround.

## Actual behavior

Attempting to render a `ResourceList.Item` with custom button properties throws a compiler error with the current typings because TypeScript expects a `DisableableAction[]`.

## Steps to Reproduce the Problem

1. Render a ResourceList.Item with the expected props and compile with no errors and get the expected button component.  e.g 
```TypeScript
<ResourceList.Item
      actions={[{
        content: 'Accept',
        accessibilityLabel: 'Accept',
      }]}
      attributeOne={"Choker"}
      attributeTwo={"4 varieties"}
/>
```
might yield something like this: 

![defaultitem](https://user-images.githubusercontent.com/8881711/29489612-237e8d88-84f3-11e7-82f2-2ef89cf0a872.png)

2. Add button properties (in this case `primary: true` and `icon: 'add'`) to an action and observe compiler errors. e.g.
```TypeScript
<ResourceList.Item
      actions={[
        {
          content: 'Accept',
          accessibilityLabel: 'Accept',
          icon: 'add',
          primary: true
        }
      ]}
      attributeOne={"Choker"}
      attributeTwo={"4 varieties"}
    />
```
3. Typecast the action as a DisableableAction to bypass the compile errors and observe the added properties changing the rendered button.
```TypeScript
<ResourceList.Item
      actions={[
        {
          content: 'Accept',
          accessibilityLabel: 'Accept',
          icon: 'add',
          primary: true
        } as DisableableAction
      ]}
      attributeOne={"Choker"}
      attributeTwo={"4 varieties"}
    />
```

Now looks like this: 
![extendeditem](https://user-images.githubusercontent.com/8881711/29489647-ed87e188-84f3-11e7-9006-f08e04ccdfda.png)

## Specifications

- Polaris version: 1.3.1
- React version: 15.6.1
- Browser: Chrome 60.0.3112.101
- Device: Desktop
- Operating System: Windows 10

**Comment by lemonmade** [comment]
Hi @Anveio. We did select the type deliberately as these are the only properties on buttons we want to support for the moment. Using primary buttons in particular is something we generally want people to avoid; as noted in the “Primary buttons” example of https://polaris.shopify.com/components/actions/button#navigation, we don’t recommend using more than one primary button on a given page, and this is usually one of the page actions.

As you noted, the current implementation means this works, and we are unlikely to change that, but the current design is built to assume the subset of properties noted in the type.

**Comment by Anveio** [comment]
Gotcha. Didn't know I was treading on unsupported ground, and a monkey patch was easy enough to mold it to my use case.
