### ISSUE TITLE
Badge "progress" prop is not documented

### ISSUE THREAD

**Issue by sp4cecat** [Shopify/polaris#172]
# Issue summary

There's an undocumented <Badge/> Parameter called "progress", not shown on the docs page

https://polaris.shopify.com/components/images-and-icons/badge#navigation

## Expected behavior

Something like ..

[progress](url) **enum**	_Add a small circle in the badge displaying the completion status. [ 'incomplete' | 'partiallyComplete' | 'complete']_

## Actual behavior

Mysteriously absent from docs

## Specifications

- Polaris version: 1.3.1
- React version: 15.6.1
- Browser: Chrome
- Device: Desktop
- Operating System: Mac OS

**Comment by dfmcphee** [comment]
This is documented as part of 1.6.0
