### ISSUE TITLE
Sketch UI Kit - App title bar missing

### ISSUE THREAD

**Issue by ButsAndCats** [Shopify/polaris#173]
# Issue summary
The title bar that appears at the top of apps and on the buy button channel, does not exist in the UI kit

![image](https://user-images.githubusercontent.com/930712/29566602-b29ad458-878d-11e7-9ac2-8b5853b2d39f.png)
![image](https://user-images.githubusercontent.com/930712/29566633-cad42524-878d-11e7-890c-4a5cb1b18378.png)

## Expected behavior
A component for this, and an example of it in use would be great.

## Specifications
- Polaris version: 1.3.1

**Comment by ry5n** [comment]
@ButsAndCats You’re right. Our goal has been to unify the apps title bar with the new [Page header](https://polaris.shopify.com/components/page). In the meantime we’ll update the Sketch kit to reflect the current implementation.

**Comment by amythibodeau** [comment]
@andreygargul any thoughts on who could look at this from the AP UX team? (Or whether this is currently on anyone's plate?)

**Comment by ButsAndCats** [comment]
@ry5n Thanks Ryan!

**Comment by dfmcphee** [comment]
This was updated as part of 1.7.0.
