### ISSUE TITLE
Popover docs examples seem to be broken

### ISSUE THREAD

**Issue by sheats** [Shopify/polaris#175]
# Issue summary
Clicking on the More actions button on the popover examples in the docs doesn't work.   When I click the button nothing shows and there are no errors in console.

## Expected behavior
I'm expecting to seem some sort of dialog/window. 

## Actual behavior
Nothing happens.

## Steps to Reproduce the Problem

1. Go to https://polaris.shopify.com/components/overlays/popover#navigation 
1. Click More actions
1.

## Specifications

- Polaris version: latest
- React version:
- Browser: Chrome
- Device: Macbook Pro
- Operating System: macOS Sierra

**NOTE:** This repo is only used for reporting issues and new feature requests. We are not accepting pull requests at this point in time.

**Comment by tmlayton** [comment]
Thanks @sheats! This is a known issue (tracking internally) and we are currently working on a fix.

**Comment by sp4cecat** [comment]
FYI, fixed

**Comment by dfmcphee** [comment]
This is resolved now.
