### ISSUE TITLE
Secondary actions within the Page component don't display correctly on mobile.

### ISSUE THREAD

**Issue by cargix1** [Shopify/polaris#177]
# Issue summary

If you have more then three secondary actions in the Page component and view on a smaller screen they overflow outside of the view. It's not possible to scroll horizontally to view the buttons that overflow.

## Expected behavior

I'd expect to either be able to scroll horizontally through the buttons, or possibly they should automatically collapse into an ActionList. 

## Actual behavior

The buttons run off to the lefthand side of the screen and are inaccessible. 

![example](https://user-images.githubusercontent.com/9730290/29881001-3d989068-8da1-11e7-8b24-00ac4f48b61f.png)

## Steps to Reproduce the Problem

1. Add 4 or more secondaryActions to the Page component. 
2. View the result on a mobile or small screen. 

## Specifications

- Polaris version: 1.5.0
- React version: 15.4.2
- Browser: Chrome
- Device: Macbook Pro
- Operating System: Sierra

**NOTE:** This repo is only used for reporting issues and new feature requests. We are not accepting pull requests at this point in time.

**Comment by chloerice** [comment]
Hey @cargix1 thanks for pointing this out. Currently, the Page component does roll up secondary actions into an ActionList for small screens. Unfortunately this doesn't currently happen within embedded app pages. I've added an issue to our internal project board and will be sure to ping you when the fix is released!

**Comment by tmlayton** [comment]
Hi @cargix1, we will be updating the Embedded App Bar UI to match what is seen [here](https://polaris.shopify.com/components/structure/page) and used throughout Shopify admin, but it will still be a while.

In the meantime, you can use `actionGroups` to create your own `Popover` + `ActionList`:

```jsx
<Page
  title="Page with actionGroups"
  actionGroups={[{
    title: 'Group 1',
    actions: [{
      content: 'Action 1',
      onAction: null,
    },
    {
      content: 'Action 2',
      onAction: null,
    }],
  },
  {
    title: 'Group 2',
    actions: [{
      content: 'Another action 1',
      onAction: null,
    },
    {
      content: 'Another action 2',
      onAction: null,
    }],
  }]}
>
  ...
</Page>
```

Result:

<img src="https://user-images.githubusercontent.com/344839/32863024-f3a2e0c6-ca0e-11e7-8694-aa947be19fb2.png" width="319" />

**Comment by cargix1** [comment]
Thanks for the update and suggestion @tmlayton! Can't wait until you have the Embedded App Bar UI updated. It's going to look beautiful! I'll use your suggestion for now :)

**Comment by tmlayton** [comment]
The UI treatment for the embedded app bar will be going a slightly different direction, although is improved for mobile.
