### ISSUE TITLE
Inconsistent behavior of Actions' url attribute

### ISSUE THREAD

**Issue by tophattom** [Shopify/polaris#179]
# Issue summary

The url attribute behaves differently depending on where the action is. For example when used in Card component's `primaryFooterAction` the url links relative to the embedded app. When used in Page component's `primaryAction` it links to `[shopify_url]/admin/[url value]`.

## Expected behavior

Expected both of the examples to link to within the embedded app.

## Actual behavior

Action in the Page header links to Shopify admin, not the embedded app.

## Specifications

- Polaris version: 1.4.1
- React version: 15.6.1
- Browser: Chrome 59.0.3071.115
- Operating System: OS X 10.11.6

**NOTE:** This repo is only used for reporting issues and new feature requests. We are not accepting pull requests at this point in time.

**Comment by dfmcphee** [comment]
Thanks for reaching out @tophattom. I have added an issues to our internal tracker to look into this. We will update with findings when we do.

**Comment by tmlayton** [comment]
Hi @tophattom, this is intended behavior. `Page` actions are delegated to the EASDK's [`ShopifyApp.Bar.initialize(config)` method](https://help.shopify.com/api/sdks/shopify-apps/embedded-app-sdk/methods#shopifyapp-bar-initialize-config) and rendered within Shopify's Admin. We try to determine the target window based on the URL. URLs beginning with `/` will open within Shopify, omitting the leading `/` will target your app. [More details about how we determine a target can be found in this comment](https://github.com/Shopify/polaris/issues/116#issuecomment-334229120). As of 1.7.0, you will be able to override this by providing your own `target`. 

Any other action rendered within your app will navigate relative to your app. I hope this helps to clarify!
