### ISSUE TITLE
[Badge] Improve localization of visually hidden text

### ISSUE THREAD

**Issue by francinen** [Shopify/polaris#1791]
## Issue summary
The way we're currently concatenating visually hidden text with the children passed to a Badge component doesn't output the most comprehensible sentence to people using screenreaders.

A Badge component can contain up to 2 instances of visually hidden text: one to convey the `status` prop (if it's defined), and another to convey the `progress` prop (if it's defined). These provide more information about the action/type communicated by the string or nodes passed as `children` to the Badge component:

![image](https://user-images.githubusercontent.com/8534230/60742772-a107ae00-9f3c-11e9-9f7c-faa553700731.png)

## Actual behavior
Each string is rendered one after the other in the following order: status, progress, children:
```jsx
  return (
    <span className={className}>
      {statusLabelMarkup}
      {pipMarkup}
      {children}
    </span>
  );
```

When the Banner content is picked up by a screenreader, it reads it aloud as a single string that might be difficult to interpret since it doesn't allow translators to implement any of the standards governing word order, grammar, or punctuation in a given locale:
```
SuccessCompleteFulfilled
```

## Expected behavior
The 1-3 pieces of information rendered in the Badge component should communicate a coherent sentence to screenreader users when they're concatenated. The children passed to a Badge component could be interpolated into an externalized string that concatenates it with the status and progress indicators to form a meaningful sentence, such as:
```js
// en.json
{
   "success": "Success: {task}" // when the progress prop is not defined
   "successWithProgress": " Success: {task} is {completenessState}"
}
```

If we're concerned that colons (`:`) are not supported in all languages, formatting the externalized string in this way will allow translators to replace the colon (as well as the whitespace between words) with whatever convention makes sense for a given locale.

This example shouldn't be taken as the recommended solution. Maybe we could consult content strategists to provide some guidance?

## Steps to reproduce the problem

1. Set the `status` prop and/or the `progress ` prop on the Badge component in the Playground or in the Polaris documentation. 
2. Inspect the Badge component to see the rendered HTML in your Dev Tools.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number: Current
- Browser: All
- Device: All
- Operating System: All

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by dpersing** [comment]
Adding the "Content" tag for our lovely and charming content folks. @francinen and I also chatted a bit about how we'll need to be careful about constructing a sentence-case string for people using screen readers, since it might get weird for sighted users. A good thing to workshop as a group!
