### ISSUE TITLE
Rename the package!

### ISSUE THREAD

**Issue by cbepxpa3ym** [Shopify/polaris#180]
It is not real to install it with composer. None of  fxpio-asset-plugin or asset-packagist repo can cover that WRONG naming. Just normalize its name to something like "shopify-polaris", please. Here is the problem: https://github.com/yiisoft/yii2-app-advanced/issues/300

**Comment by schmunk42** [comment]
This can be closed, I think. I've also just learned about npm-scope support in fxpio-asset-plugin today.

**Comment by lemonmade** [comment]
Yeah, I'm sorry if this causes issues with some tools, but I don't know that it makes sense for us to change it on our end. Many popular libraries, including some as big as Angular, use namespaced packages, and any tool that does not support them will fail at some point when a dependency of a dependency is namespaced.
