### ISSUE TITLE
Modifying styles of components - React

### ISSUE THREAD

**Issue by nomanali-dev** [Shopify/polaris#181]
# Issue summary

I want to modify few button colors, but when i try to edit **styles.css** file, it does not effect on button color. 

`node_modules/@shopify/polaris/styles.css`

Is there any other way to modify styles?

## Expected behavior

Modifying styles.css should effect components.

## Actual behavior

Modifying styles.css do not effect components.

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Polaris version: 
- React version:
- Browser:
- Device:
- Operating System:

**NOTE:** This repo is only used for reporting issues and new feature requests. We are not accepting pull requests at this point in time.

**Comment by dfmcphee** [comment]
Thanks for the reaching out @nomanali-dev.

One of the goals of Polaris is to unify all of the product design work that's being done on Shopify, both internally and by our partners. We recommend using the colors that have been supplied as part of Polaris and we don't support changing them.
