### ISSUE TITLE
Can you make Shopify themes with Polaris? 

### ISSUE THREAD

**Issue by brandonpowell** [Shopify/polaris#183]
I want to know is it possible to build a custom Shopify template with Polaris or do I have to use  [Timber](https://github.com/Shopify/Timber), If I can create a theme with Polaris use.

How can I upload the theme to Shopify Developer Sit?

**Comment by dfmcphee** [comment]
Hey @brandonpowell, thanks for reaching out. Although it would be possible, Polaris is meant for building merchant facing applications (admin, apps), and not for building customer facing storefronts.

We recommend using [slate](https://shopify.github.io/slate/) to get started building your own theme.
