### ISSUE TITLE
Build with yarn fails

### ISSUE THREAD

**Issue by mikeyhew** [Shopify/polaris#184]
# Issue summary

I tried building polaris on my machine, and since there is a `yarn.lock` file, I assume the way install dependencies and build is with `yarn`. Unfortunately, I get an error because I don't have access to a certain git repository.

## Expected behavior

That it would install and build without error.

## Actual behavior

```
polaris(master) mikeyhew$ yarn
yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: clone ssh://git@github.com/Shopify/js-uploader.git /Users/mikeyhew/Library/Caches/Yarn/v1/.tmp/74afd5bd502652853dcb8a9fbb429196
Directory: /Users/mikeyhew/Desktop/resistor-software/polaris
Output:
Cloning into '/Users/mikeyhew/Library/Caches/Yarn/v1/.tmp/74afd5bd502652853dcb8a9fbb429196'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
## Steps to Reproduce the Problem

1. `git clone https://github.com/Shopify/polaris`
2. `cd polaris`
1. `yarn`

## Specifications

- Polaris version: master
- Device: Apple Macbook Air
- Operating System: Mac OS X 10.11

**Comment by kaelig** [comment]
Thanks for reporting this! One of the project's dependencies unnecessarily requires the user to be authenticated on GitHub over SSH.

A fix is on the way. In the mean time, the workaround is [to authenticate on GitHub over SSH](https://help.github.com/articles/about-ssh/). Hope this helps!
