### ISSUE TITLE
Discuss and document any decisions made so far missing from the repo’s decision log

### ISSUE THREAD

**Issue by chloerice** [Shopify/polaris#185]

**Comment by chloerice** [comment]
I'd love to see us leverage both: 
  - Discussions for arriving at and archiving how we reached a decision
  - A decision log for centralizing and summarizing the decisions, linking back to the relevant discussion(s) or other context
 
> We could have a meta Discussion as to serve as a "log". This would just note a summary statement of the primary decisions made and a reference to the discussion.

Using a discussion to log decisions sounds good to me! It wouldn't require PR to update and lives closer to where the decisions themselves are made 👍🏽

**Comment by samrose3** [comment]
@chloerice I've started [this meta-discussion](https://github.com/Shopify/polaris/discussions/206) to group and track our technical decisions. Please feel free to edit, revise, or even delete if you think we need something different for logging 🗒️ ✍️
