### ISSUE TITLE
Feature Request: Allow breadcrumbs to receive an onClick handler

### ISSUE THREAD

**Issue by arypbatista** [Shopify/polaris#188]
# Issue summary

When interacting through breadcrums some scripted behavior is commonly needed, such as redirecting to a shopify section using the Embedded App SDK (e.g. `ShopifyApp.redirect("/orders"))`, this can be done by setting a URL like `javascript:<function call>` , but it would be better to assign an onClick handler.

## Expected behavior

Breadcrums to optionally receive an onClick handler.

## Actual behavior

Breadcrums don't allow an onClick handler. 

## Specifications

- Polaris version: v1.0.1
- React version: Any version
- Browser: Anyone
- Device: Anyone
- Operating System: Anyone

**Comment by tmlayton** [comment]
Hey @arypbatista, this is now possible as of v1.7.0 which was just released. Note that the callback is set via `onAction`. Thanks for bringing this up!

**Comment by arypbatista** [comment]
Thanks!

**Comment by iampeter** [comment]
Could this be added to the docs?
