### ISSUE TITLE
Retain subdomain when using EASDK and forceRedirect

### ISSUE THREAD

**Issue by cargix1** [Shopify/polaris#189]
# Issue summary

When using the EASDK with forceRedirect enabled Shopify automatically rewrites the subdomain back to the App Url listed within our Partners app settings page. For example: https://app-polaris.myshopifyapp.com/dashboard would redirect back to https://legacy.myshopifyapp.com/dashboard. 

## Expected behavior

I'd expect after the initial Authentication process that the EASDK would retain the subdomain provided provided so that we can run different builds on different servers at the same time. This way we can gradually migrate merchants over to our Polaris version.  

## Actual behavior

No matter what url I pass through to the EASDK, Shopify will always redirect merchants to our App Url and not the subdomain provided.

<img width="693" alt="screen shot 2017-09-27 at 18 39 09" src="https://user-images.githubusercontent.com/9730290/30928337-3a53ee16-a3b3-11e7-9ceb-8d0dd7e7e290.png">

## Steps to Reproduce the Problem

1. Set your App Url in app settings to something like `https://legacy.myshopifyapp.com` 
2. Carry out your auth process and return customers to a valid callback url for example `https://polaris.myshopify.com`
3. View the src of the EASDKs iframe and it will be `https://legacy.myshopifyapp.com` not `https://polaris.myshopifyapp.com` like i'd expect.

## Specifications

- Polaris version: v1.6.0
- React version: 15.6.1
- Browser: Chrome
- Device: MacBook Pro
- Operating System: Sierra

**Comment by cargix1** [comment]
With debug mode enabled on the EASDK i've been able to get the following warning:

> received message null from unexpected origin https://polaris.storepickup.dev ; expecting https://www.storepickup.dev or subdomain thereof

<img width="1421" alt="screen shot 2017-10-05 at 00 00 36" src="https://user-images.githubusercontent.com/9730290/31201777-3c148dde-a960-11e7-99c9-9656398ee23e.png">

Obviously https://polaris.storepickup.dev is a subdomain of https://www.storepickup.dev. So I do believe we have a bug in the SDK. Can you confirm?

**Comment by tmlayton** [comment]
Hi @cargix1, this isn't currently possible with the app platform. For security reasons, Shopify expects the app origin to match the App URL defined in the Partners dashboard and the host of any whitelisted URL must match the App URL host. Inversely, the app expects the `shopOrigin` to match the shop host. If either is mismatched, you will see warnings like the ones posted in the previous commment.

> This way we can gradually migrate merchants over to our Polaris version.

For now, this will need to be handled on the app side, conditionally serving the current version or the Polaris version from the url listed as the App URL in the partners dashboard.

I have forwarded this request to the App Platform team.
