### ISSUE TITLE
React Embedded App apiKey url parameter null

### ISSUE THREAD

**Issue by celsowhite** [Shopify/polaris#190]
# Issue summary

When loading an embedded react app that has already been authenticated and installed in a shop, the apiKey parameter returns null. 

## Expected behavior

When accessing my app via a shops dashboard then the apiKey variable as shown in [the example](https://github.com/Shopify/polaris/blob/master/examples/react-embedded/src/App.js#L8) setup should return the apiKey to pass into my app.

## Actual behavior

Only the below parameters are accessible from the embedded apps iframe URL. No apiKey parameter is shown.

?hmac=''&locale=en&protocol=https%3A%2F%2F&shop=''&timestamp=''

I expect to use the apiKey from the url params to pass into my EmbeddedApp component.

```
<EmbeddedApp
   apiKey={apiKey}
   shopOrigin={shopOrigin}
   forceRedirect
>
```

## Understandings

I understand that if you access this url directly http://localhost:3000/login?shop=.myshopify.com&apiKey= you can pull the api key. I also understand that during the authentication process we can redirect to our apps url and include our apiKey as a parameter. Using those methods I am able to pull the apiKey into my app.

The issue occurs when you are just loading the app page via the shops dashboard.

## Steps to Reproduce the Problem

1. Authenticate and install the React embedded app into a shop using the [Create Embedded React App](https://github.com/Shopify/polaris/tree/master/examples/react-embedded) example structure as a scaffold for the client.
2. Add a console.log(apiKey) in the react apps App.js below the apiKey variable definition.
3. Go to the shops dashboard apps section and click on the app to load it and see the null output in the console.

## Potential Solutions

1. Add the apiKey parameter to the iframe url of an embedded app.
2. In the embedded react app example refine the method of getting the apiKey if a user has already authenticated and installed their app.

## Specifications

- Polaris version: 1.4.1
- React version: 15.4.2
- Browser: Chrome 61
- Device: MacBook Pro
- Operating System: OS 10.12.5

**Comment by tmlayton** [comment]
Hi @celsowhite, the `apiKey` is not intended to be pulled from URL params. It is being done in the example app as a convenient way to demo the example. You will want to copy and paste your API key from the Partners dashboard (shown below) to your app.

<img src="https://user-images.githubusercontent.com/344839/31206326-f79c619c-a92b-11e7-9d1d-95782bb68238.png" />
