### ISSUE TITLE
Public Figma UI Kit

### ISSUE THREAD

**Issue by Tobjoern** [Shopify/polaris#1901]
## Feature request summary

I'm not sure if this is the right place to post this, but it would be very cool if more integration possibilities concerning the Ui kit (e.g Figma) existed.

## Rationale

Currently the Ui kit is only available for sketch, a programm only installable on Mac OS. This means a quite significant portion of the community is excluded from using the Ui kit. I'm not a sketch expert, but it also seems like Sketch actually costs money, Figma in contrast is totally free. Moreover figma is available on all Platforms, as it can be used via the browser.

**Comment by HYPD** [comment]
@Tobjoern you've mentioned some really good points, thanks for the feedback. We've been testing Figma internally at Shopify, and we're currently planning and exploring construction of a new UI kit for Figma. You should hear more about this within the next month or two.

**Comment by Tobjoern** [comment]
Great to hear!

**Comment by PixelsCommander** [comment]
@HYPD any updates on this?

**Comment by tahabahaji** [comment]
@HYPD any updates on this?

**Comment by HYPD** [comment]
@PixelsCommander Thanks for asking! It's not on our immediate roadmap but we're looking into it.

**Comment by alexander-potemkin** [comment]
@HYPD , wondering if it's so if the ticket is in a Closed state?

**Comment by HYPD** [comment]
Hey @alexander-potemkin working on it right now 😉

**Comment by shubham-kaushal** [comment]
Is the new Polaris Figma UI Kit now available to the public?

**Comment by Mancerrss** [comment]
If you're gonna make a Figma file, make sure to submit it on Figma sa Figma Community file, so it's easily discoverable and updatable. 

Please don't host a .fig file export.

**Comment by ofergpr** [comment]
I really need access to the new Polrais UI in Figma, would love to get updated if anyone has a solution

**Comment by heyjoethomas** [comment]
Here is a link to our community [Figma file ](https://www.figma.com/community/file/1111360433678236702)
