### ISSUE TITLE
Audit atomic styles in our atoms.css.ts

### ISSUE THREAD

**Issue by samrose3** [Shopify/polaris#191]
Consider adding these properties/styles to our atoms:

- ...

Audit our current atomic styles and assess an acceptable CSS output size. See Braid's sprinkles as size and property comparison. Our atomic styles should NOT be any larger than Tailwind's default (~700kb).

- [x] Split up responsive and unresponsive properties

**Comment by lgriffee** [comment]
### Tailwind Comparison
**Properties We Could Consider Adding**

- alignContent
- appearance
- backgroundAttachment
- backgroundBlendMode
- backgroundClip
- backgroundImage
- backgroundOrigin
- backgroundPosition
- backgroundRepeat
- backgroundSize
- borderCollapse
- borderOpacity
- boxDecorationBreak
- boxSizing
- clear
- cursor
- float
- fontFamily
- fontStyle
- isolation
- justifyItems
- letterSpacing
- lineHeight
- listStylePosition
- listStyleType
- mixBlendMode
- objectFit [images]
- objectPosition
- opacity
- order
- outline
- overscrollBehavior
- placeItems
- placeSelf
- pointerEvents
- resize
- rotate
- scale
- skew
- tableLayout
- textTransform
- transform
- transition
- translate
- userSelect
- verticalAlign
- visibility
- whitespace
- wordBreak
- z-index

**Properties We've Included That Tailwind Doesn't** 

- Nothing 😅

**Comment by lgriffee** [comment]
### Properties for Us to Consider 

- userSelect
- outline
- opacity
- [ z-index](https://github.com/Shopify/polaris/discussions/75#discussioncomment-1121003) (existing discussion) 
- cursor
- pointerEvents
- transition
- whitespace
- wordBreak

**Comment by kyledurand** [comment]
> Our atomic styles should NOT be any larger than Tailwind's default (~700kb).

You mean ~700b? Right 😓 ? I wonder if we should try for a more aggressive goal since tailwind doesn't ship unused styles to production but we might have to

This is an awesome audit, thanks @lgriffee & @aveline

**Comment by samrose3** [comment]
> Our atomic styles should NOT be any larger than Tailwind's default (~700kb).

I don't know where I got 700kb 😅 Looking at the [Tailwind docs](https://tailwindcss.com/docs/optimizing-for-production), I think we should be aiming to beat the minified size for sure (`2872.2kB`). Gziped, it is (`289.2kB`) which seems like a reasonable goal. I don't think we'll every reach `2872.2kb` 😱 

Excellent audit, very helpful! 

Something else we might consider is understanding which should be [responsive](https://github.com/seek-oss/braid-design-system/blob/34ac35771d/lib/css/atoms/atomicProperties.ts#L73) vs [unresponsive](https://github.com/seek-oss/braid-design-system/blob/34ac35771d/lib/css/atoms/atomicProperties.ts#L38). Making it unresponsive will save a lot in terms of reducing the number of generated atomic styles for those particular properties.
