### ISSUE TITLE
Overlay is not opening or closing

### ISSUE THREAD

**Issue by mush20** [Shopify/polaris#195]
# Issue summary

> **Note**: If you work at Shopify, post your issue on our internal repo instead of this one.

Provide a high-level summary of your issue or feature request.
The overlay component is opening or closing

## Expected behavior
The overlay should open when the activator is clicked
For issues, what do you think should have happened? For feature requests, why do you believe this feature is necessary?

## Actual behavior

For issues, what actually happens? Include an error message (in a `<details></details>` tag) if your issue is related to an error while running Polaris.

## Steps to Reproduce the Problem
```
<Popover
    active
    activator={<Button >April 20–21, 2017</Button>}
    sectioned
    onClose={()=>{
        console.log('close2 ');

    }}
>
    <FormLayout>
        <Select
            label="Date range"
            options={['Custom']}
        />
        <FormLayout.Group condensed>
            <TextField
                label="Starting"
                value="2017-04-20"
            />
            <TextField
                label="Ending"
                value="2017-04-21"
            />
        </FormLayout.Group>
    </FormLayout>
</Popover>
```
![screen shot 2017-10-11 at 1 07 53 am](https://user-images.githubusercontent.com/11493552/31391564-a8f5a49e-ae22-11e7-9a6a-34ac61b8031c.png)

## Specifications

- Polaris version: 1.7.0
- React version: 16.0.0
- Browser: Chorme
- Device: mac
- Operating System: Sierra

**NOTE:** This repo is only used for reporting issues and new feature requests. We are not accepting pull requests at this point in time.

**Comment by dfmcphee** [comment]
Hi @mush20. Thanks for the issue.

I think you are missing a bit of code to get this working correctly. You will have to wrap the popover in a component that can track state and pass the `active` prop based on that state.

Here is a working example:

```
export default class PopoverExample extends React.Component {
  constructor(props) {
    super(props);

    this.showPopover = this.showPopover.bind(this);
    this.hidePopover = this.hidePopover.bind(this);

    this.state = {
      visible: false,
    }
  }

  showPopover() {
    this.setState({
      visible: true,
    });
  }

  hidePopover() {
    this.setState({
      visible: false,
    })
  }

  render() {
    const activator = (
      <Button onClick={this.showPopover}>
        April 20–21, 2017
      </Button>
    );

    return (
      <Page title="Playground">
        <Popover
          active={this.state.visible}
          activator={activator}
          sectioned
          onClose={this.hidePopover}
        >
          <FormLayout>
            <Select
              label="Date range"
              options={['Custom']}
            />
            <FormLayout.Group condensed>
              <TextField
                label="Starting"
                value="2017-04-20"
              />
              <TextField
                label="Ending"
                value="2017-04-21"
              />
            </FormLayout.Group>
          </FormLayout>
        </Popover>
      </Page>
    );
  }
}
```

**Comment by mush20** [comment]
legend!! thanks @dfmcphee

**Comment by benbonnet** [comment]
Encountered the same problem; can we say the example [from the presentation](https://polaris.shopify.com/components/overlays/popover#navigation) is a bit misleading ? One could think at first looking at the code from this page that the state management is handled by default
