### ISSUE TITLE
PopoverLayer div isn't deleted after corresponding component unmounts.

### ISSUE THREAD

**Issue by Anveio** [Shopify/polaris#196]
# Issue summary
When mounting and unmounting Popover components (including ResourceList.Items with persistedActions={true}) PopoverLayer divs are produced infinitely.

![issueexample](https://user-images.githubusercontent.com/8881711/31409459-f8370c9e-add9-11e7-85d6-de30bf40942b.gif)

Demo: https://treasurer-cleansers-12248.netlify.com/

Source Code: https://github.com/Anveio/popover-issue-example/blob/master/src/App.tsx

## Expected behavior
The PopoverLayer node corresponding to the component should be deleted to prevent the DOM tree from growing infinitely.

## Actual behavior
The PopoverLayer node corresponding to the component isn't deleted, causing the DOM tree to grow infinitely.

## Steps to Reproduce the Problem

1. Switch between tabs in the live demo link https://treasurer-cleansers-12248.netlify.com/
2. Observe divs being created and not deleted when corresponding component unmounts.

## Specifications

- Polaris version: 1.7.0
- React version: 16
- Browser: Chrome
- Device: Desktop
- Operating System: Windows

**Comment by chloerice** [comment]
Thanks for bringing this to our attention @Anveio, looking into this now.

**Comment by dlindenkreuz** [comment]
@chloerice What's the status of this?

**Comment by dlindenkreuz** [comment]
Dirty hack for those who cannot wait:

```ts
// use this instead of the polaris popover

import * as React from "react"
import { Popover as PolarisPopover } from "@shopify/polaris"
import { Props } from "@shopify/polaris/types/components/Popover"

class Popover extends React.Component<Props> {
  private _popover: PolarisPopover | null = null

  public componentWillUnmount() {
    const p = this._popover as any
    if (p == null) return
    p.layerNode.parentNode.removeChild(p.layerNode)
  }

  protected setRef = (r: PolarisPopover) => (this._popover = r)

  public render() {
    return <PolarisPopover {...this.props} ref={this.setRef} />
  }
}

export default Popover
```

**Comment by dfmcphee** [comment]
This is something we're addressing in Polaris v2.0. We now use React `Portals` to manage these overlay components. You can have a look at the beta documentation at https://polaris-v2.shopify.com and start trying it out.

Let us know what you think. If there's something missing for your needs, or otherwise have feedback, feel free to re-open this issue and add a comment, or create a new issue in the repo. Thanks!
