### ISSUE TITLE
building with React 16

### ISSUE THREAD

**Issue by davit-khaburdzania** [Shopify/polaris#197]
# Issue summary
After upgrading to `react16` i get multiple errors when compiling my project
```
ERROR in ./~/css-loader?{"minimize":false}!./~/postcss-loader/lib?{"sourceMap":true}!./~/resolve-url-loader!./~/sass-loader/lib/loader.js?{"sourceMap":true}!./~/import-glob-loader!./frontend/dashboard/styles/editor.scss
Module build failed: 
@import "~@shopify/polaris/src/styles/foundation.scss";
^
      File to import not found or unreadable: ~@shopify/polaris/src/styles/foundation.scss.
Parent style sheet: stdin
      in /Users/davit/work/shogun-web/frontend/dashboard/styles/editor.scss (line 1, column 1)
 @ ./frontend/dashboard/styles/editor.scss 4:14-310
 @ ./frontend/packs/editor.jsx

ERROR in ./~/react-addons-transition-group/index.js
Module not found: Error: Can't resolve 'react/lib/ReactTransitionGroup' in '/Users/davit/work/shogun-web/node_modules/react-addons-transition-group'
 @ ./~/react-addons-transition-group/index.js 1:17-58
 @ ./~/@shopify/react-utilities/animation/TransitionGroup.js
 @ ./~/@shopify/react-utilities/animation/index.js
 @ ./~/@shopify/polaris/index.es.js
 @ ./frontend/dashboard/components/layout/TopBar.js
 @ ./frontend/dashboard/components/layout/DashboardLayout.js
 @ ./frontend/dashboard/components/Dashboard.js
 @ ./frontend/dashboard/index.js
```

## Specifications

- Polaris version: `1.7.0`
- React version: `16.0.0`
- Webpack: `^2.6.1`

**Comment by iJaniashvili** [comment]
@davit-khaburdzania First error is not about react 16, it's about importing `scss` file

use:
`@import "~@shopify/polaris/styles/foundation.scss";`
instead of:
`@import "~@shopify/polaris/src/styles/foundation.scss";`

**Comment by Tiendq** [comment]
Actually there are 2 file not found errors here and nothing relates with React itself. Issue title must be changed.

**Comment by davit-khaburdzania** [comment]
@Tiendq well this errors happened after upgrading React version

**Comment by aherriot** [comment]
The second issue is regarding `react-addons-transition-group` You should now use this project instead: https://github.com/reactjs/react-transition-group

**Comment by dfmcphee** [comment]
Are you still having issues with this @davit-khaburdzania? This should have been fixed as of `1.8`.

**Comment by davit-khaburdzania** [comment]
@dfmcphee not anymore

**Comment by dfmcphee** [comment]
Great, thanks. 👍
