### ISSUE TITLE
Spinner causing React Error

### ISSUE THREAD

**Issue by fighella** [Shopify/polaris#198]
# Issue summary

Spinner Component from example returning React Minified Error

## Expected behavior

Should return Spinner.

## Actual behavior

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of ...

## Steps to Reproduce the Problem

1. Add Spinner Component from example: 

```

return 
<p><Spinner  size="large"  color="teal" /></p>

```

## Specifications

- Polaris version: 1.0.2
- React version: 15.6.1
- Browser: Chome
- Device: MacBook Pro

**Comment by dfmcphee** [comment]
Hi @fighella. Thanks for the issue. That looks like invalid syntax. Can you try putting that all on one line or wrapping in `(` `)`? 

```
return <p><Spinner size="large" color="teal" /></p>
```

```
return (
  <p>
    <Spinner size="large" color="teal" />
  </p>
);
```

**Comment by fighella** [comment]
Yes tried that. No joy.

ReactDOMComponentTree.js?f714:113 Uncaught TypeError: Cannot read property '__reactInternalInstance$fy02evcdhn' of null
    at Object.getClosestInstanceFromNode (eval at <anonymous...  etc

**Comment by fighella** [comment]
Hey look I updated to the latest version of the package and we're good. Thanks for your help.
