### ISSUE TITLE
Action List not works ! When clicking on it nothing happened

### ISSUE THREAD

**Issue by miranos** [Shopify/polaris#199]
Hi,
I want to use Action List component but do not work when i click on it.

Here is the example from the documentation:

```
<div style="height: 200px;">
  <div><button aria-expanded="true" aria-haspopup="true" aria-owns="Popover1" aria-controls="Popover1" tabindex="0" class="Polaris-Button" type="button"><span class="Polaris-Button__Content"><span>More actions</span><span class="Polaris-Button__Icon"><span class="Polaris-Icon"><svg viewBox="0 0 20 20" class="Polaris-Icon__Svg"><path d="M5 8l5 5 5-5z" fill-rule="evenodd"></path></svg></span></span></span></button></div>
</div>
```

How to add options on it please ?

Thank you.

**Specifications**
    Polaris version: 1.7.0
    React version: No (HTML)
    Browser: Chrome / Firefox
    Device: Windows
    Operating System: Windows 7

**Comment by rkbhochalya** [comment]
@miranos if you're not using React component then you will need to write your own JavaScript to toggle the action dropdown.

**Comment by dfmcphee** [comment]
Hi @miranos, thanks for the issue. @rkbhochalya is correct. If you are using the static HTML and CSS you are responsible for wiring up your own JS to make it interactive. We recommend using the react package for these components.

**Comment by miranos** [comment]
I can't add options to be able to get it work !

Is there any example on how doing it please ?

**Comment by dfmcphee** [comment]
Sorry, we don't have any examples for doing something like this. I would suggest changing to the React components if you want that functionality.

**Comment by miranos** [comment]
I am looking for HTML dropdown menu with Shopify !

You have to add an example of this sine it's present in your documentation.

**Comment by dfmcphee** [comment]
We mention in our setup that we provide the CSS for static components, but if you use it you are responsible for generating your own markup and toggling classes and states as needed. https://github.com/Shopify/polaris#using-the-css-components

You can use the examples in the style guide to figure out what markup you should be using for each state, but you will have to write the JavaScript to toggle that markup within your app.

**Comment by isaac** [comment]
@dfmcphee I think the problem here is that the Polaris docs don't show all the generated HTML here: https://polaris.shopify.com/components/actions/action-list#navigation

They show the HTML generated for the "More actions" button, but they don't show the HTML for the popover ("Import file" & "Export file").

Popover docs have the same issue: https://polaris.shopify.com/components/overlays/popover#navigation

Is this something you would consider adding to the docs?

**Comment by dfmcphee** [comment]
> @dfmcphee I think the problem here is that the Polaris docs don't show all the generated HTML here: https://polaris.shopify.com/components/actions/action-list#navigation

Great point @isaac. I created #228 to track this.
