### ISSUE TITLE
Action List Keys Bug

### ISSUE THREAD

**Issue by bitbleach** [Shopify/polaris#200]
# Issue summary

I was trying to create an ActionList that had links to two different locations only one of them would display because I ran into the following warning: 
`Warning: flattenChildren(...): Encountered two children with the same key, [object Object]. Child keys must be unique; when two children share a key, only the first child will be used. `

And it won't allow me to give a key to the individual items.

My code:
```
              <Popover
                active={settings_toggle}
                activator={<Button onClick={props.handleSettingsToggle}>Settings</Button>}
              >
                <ActionList
                  items={[
                    {content: <Link key={1} url='/configurations'>Account</Link>},
                    {content: <Link key={2} url='/configurations'>Configuration</Link>},
                  ]}
                />
              </Popover>
```
Internal Shopify Code Snippet for the ActionList Component:
```
function renderSection(section: Section, hasMultipleSections: boolean, index: number) {
  const SectionElement: string = hasMultipleSections ? 'li' : 'div';
  const actionMarkup = section.items.map(({content, ...item}) => (
    <Item key={content} content={content} {...item} />
  ));
```

## Expected behavior

I expected to be able to give keys to my items so they would render properly.

## Actual behavior

Only one item in a list renders

## Steps to Reproduce the Problem

Create an ActionList with two links

## Specifications

- Polaris version: v1.7.0
- React version: React v16.0
- Browser: Chrome
- Device: MacOS
- Operating System: Ubuntu

**NOTE:** This repo is only used for reporting issues and new feature requests. We are not accepting pull requests at this point in time.

**Comment by bitbleach** [comment]
I can use two ActionLists as a workaround, but I feel like that's not how it was intended to be used.

`              <Popover
                active={settings_toggle}
                activator={<Button onClick={props.handleSettingsToggle}>Settings</Button>}
              >
                <ActionList
                  items={[
                    {content: <Link url='/configurations'>Account</Link>},
                  ]}
                />
                <ActionList
                  items={[
                    {content: <Link url='/configurations'>Configuration</Link>}
                  ]}
                />
              </Popover>`

**Comment by rkbhochalya** [comment]
It should be fixed as it doesn't allows components as action content. In my case I want to use icons in action content.

**Comment by rkbhochalya** [comment]
Using `index` instead of `content` as value of the key attribute of <Item /> in renderSection function will fix the issue:

```
const actionMarkup = section.items.map(({content, ...item}, index) => (
  <Item key={index} content={content} {...item} />
));
```

**Comment by bitbleach** [comment]
rkbhochalya that's Shopify's code, so if they want to change that then it's up to them.

**Comment by rkbhochalya** [comment]
Yes,  and my comments is for them actually :)

**Comment by dleroux** [comment]
Hi @bitbleach, the intention here is that your above code would look like this:

```
<ActionList
 items={[
     {content: 'Account', url: '/recurring_charges'},
     {content: 'Configuration', url: '/configurations'},
 ]}
/>
```

Does this work for you?

@rkbhochalya, the items do have an `image` and an `icon` prop. Are trying to achieve something different?

**Comment by bitbleach** [comment]
dleroux, that solved the problem. Thanks for your answer!
