### ISSUE TITLE
Embedded app support for SkeletonPage

### ISSUE THREAD

**Issue by rkbhochalya** [Shopify/polaris#202]
# Issue summary

If you use SkeletonPage in an embedded app it shows the loading version of the page title and secondary actions below the app bar.

## Expected behavior

SkeletonPage should not show the loading version of the page title and secondary actions when used in embedded apps. The value for title and actions in the bar can be discussed.

## Actual behavior

SkeletonPage when used in an embedded app, shows the loading version of the page title and secondary actions below the app bar.

## Steps to Reproduce the Problem

1. Use SkeletonPage in an embedded app.

## Specifications

- Polaris version: 1.7.0
- React version: 15.6.1

**Comment by dleroux** [comment]
Thanks @rkbhochalya for pointing out this issue. A fix is currently under review in a internal repo.

**Comment by dleroux** [comment]
@rkbhochalya closing this as it is now fixed in the latest 1.8 release.
