### ISSUE TITLE
ActionList can't open a link in a new tab

### ISSUE THREAD

**Issue by dansundy** [Shopify/polaris#203]
# Issue summary

I have an `ActionList` component in a `Popover` and for one of the items I would like to explicitly open the link in a new tab. 

I am using the EASDK and am using `useLinkComponent` to intercept and convert all the urls to `react-router-dom` links. To complicate things further, I want the link to have the same domain (it is a preview link).

Am I missing something here?

Here's an example:

```
<ActionList 
    sections={[{
        items: [
            {
                 content: 'Example 1',
                 onAction: () => {...}
            }
        ]
    },
    {
        items: [
             {
                 content: 'Example 2',
                 url: `https://${env.shop_domain}/?preview_theme_id=${themeID}`,
                 external: true
             },
             {
                 content: Example 3,
                 url: `/some-internal-link`
             }
         ]
     }]} 
/>
```

## Expected behavior

In the example above I would expect the `Example 2` action to create a link with a `target="_blank"` attribute.

## Actual behavior

A link without a target is created. When clicked, the link appears but is embedded in the Shopify admin. Or if `useLinkComponent` is used it redirects back to the app.

## Steps to Reproduce the Problem

1. Create an `ActionList` and try to create a link that opens in a new tab.

## Specifications

- Polaris version: 1.7.0
- React version: 15.6.2
- Browser: Chrome
- Device: MacBook Pro
- Operating System: OSX

**Comment by chloerice** [comment]
Hi @dansundy, thanks for bringing this bug to our attention! I've created an issue in our internal project board, and will update you once the bug fix has been released.

**Comment by dansundy** [comment]
Great, @chloerice. Thanks?

**Comment by ry5n** [comment]
This has been fixed in the latest version. Please let us know if you run into any trouble. Thanks for your patience 💜
