### ISSUE TITLE
Data Table component

### ISSUE THREAD

**Issue by babenzele** [Shopify/polaris#204]
I cannot find the `Table` component in the Polaris component library, even though it is used under the Components tab in `Sketch.UI.Kit/Web UI Kit 1.7.0.sketch`. Am I missing something?

<img width="672" alt="screen shot 2017-10-19 at 5 19 14 pm" src="https://user-images.githubusercontent.com/3578574/31799875-b8e67934-b4f1-11e7-8f71-76f045b3bf1f.png">

**Comment by chaddjohnson** [comment]
I ended up importing styling from Uptown CSS (with some modifications) for now until Shopify implements this in Polaris.

**Comment by Cam** [comment]
Isn't this essentially ResourceList with some minor additions?

**Comment by babenzele** [comment]
Coming back to this, I also can't find what is called `Order Index`:

<img width="727" alt="screen shot 2017-11-08 at 12 16 09 pm" src="https://user-images.githubusercontent.com/3578574/32572279-ed29ac56-c47e-11e7-872e-b489e448e528.png">

This would be a useful component to allow filtering a list of things, otherwise I'm just putting tabs on top of a dropdown button next to an input on top of some headers above a resource list with checkboxes and then developing my own filtering and pagination.

**Comment by chloerice** [comment]
Hey @babenzele! We are currently finishing up a nice enhancement to the ResourceList component, but for your tabular data needs you are correct that it's currently missing from Polaris. Right now we're getting starting with extracting the best parts of the different table implementations we are using under the hood across the Shopify admin into the forthcoming DataTable component that will be in Polaris in the next big release. I'll keep you posted!

**Comment by babenzele** [comment]
Thanks @chloerice! Looking forward to that release.

**Comment by superwhykz** [comment]
hi @chloerice do you have ETA when 2.0 will be released? I am looking forward for that component.

**Comment by Cam** [comment]
Basic table support exists in the current version hosted on the CDN. You can use them right now by creating a table inside a `<div class="table-wrapper">` wrapper.

**Comment by superwhykz** [comment]
@cam thanks!  i will give a try to wrap my table.

**Comment by sbstnmsch** [comment]
@Cam you don't mean the current 1.10.1 version? There is no `.table-wrapper` class in

**Comment by Cam** [comment]
@sbstnmsch Yeah, you're 100% right. Sorry @superwhykz. I was using an additional resource I had totally forgotten about 🤭

**Comment by sbstnmsch** [comment]
@Cam fair enough. Could u point us to it? ;-)

**Comment by babenzele** [comment]
Some info from Shopify regarding v2 beta: https://github.com/Shopify/polaris/issues/254#issuecomment-359893991

**Comment by dfmcphee** [comment]
The `DataTable` component is now included in the latest beta of v2 we shipped. You can find the documentation on our beta version of the style guide here: https://polaris-v2.shopify.com/components/lists/data-table#navigation

**Comment by sbstnmsch** [comment]
@dfmcphee we love you all! 👍

**Comment by babenzele** [comment]
`ResourceList` is the one.

https://polaris-v2.shopify.com/components/lists/resource-list#navigation

**Comment by chaddjohnson** [comment]
A `ResourceList` combined with a `DataTable` would be fantastic. This is what Shopify has on its built-in Orders page (/admin/orders).

**Comment by Arvind6353** [comment]
Hi Team , Any update on the above mentioned functionality ?

**Comment by chloerice** [comment]
Hey Arvin, adding column headers to the `ResourceList` isn't in our plans right now, but the  [`Filters`](https://polaris.shopify.com/components/lists-and-tables/filters) component has been separated from `ResourceList` so you can compose a filtering experience with `DataTable` now.

**Comment by adventuretocode** [comment]
@chaddjohnson  I have same issue with datatable I have refer the shopify Polaris document demo code on sandbox it it also not working.

**Comment by chloerice** [comment]
Hey @adventuretocode 👋🏽 Check out the "With datatable" example in the [Filters docs](https://polaris.shopify.com/components/selection-and-input/alpha-filters) as well as the [`IndexTable`](https://polaris.shopify.com/components/tables/index-table) component 😁
