### ISSUE TITLE
Downloadable Color Palettes (ASE / CLR)

### ISSUE THREAD

**Issue by vilav** [Shopify/polaris#205]
Hello

Is there a set of downloadable palettes for the [colors](https://polaris.shopify.com/visuals/colors#color-palette) in CLR / ASE formats?

Thanks

**Comment by chloerice** [comment]
Hi @vilav, currently we have a [UI Kit for Sketch](https://github.com/Shopify/polaris/releases/download/v1.7.0/Sketch.UI.Kit.zip) as well as a [Sass bundle](https://github.com/Shopify/polaris/releases/download/v1.7.0/Sass.zip) which has a colors.scss file, but no .clr or .ase bundles at this time.

**Comment by kaelig** [comment]
Hi @vilav, thank you for your patience! These palette formats will soon be available on polaris.shopify.com

In the mean time, here's a zip file containing:

- Polaris.sketchpalette
- Polaris.clr
- Polaris.ase

**📦 [Polaris palettes.zip](https://github.com/Shopify/polaris/files/1808476/Polaris.palettes.zip)**

Hope this helps!

**Comment by vilav** [comment]
@kaelig just downloaded them! Thanks a ton
