### ISSUE TITLE
Popover is broken in Polaris 1.8.x

### ISSUE THREAD

**Issue by rkbhochalya** [Shopify/polaris#208]
# Issue summary

The Popover component has stopped rendering after upgrading to version 1.8.0. We also tried upgrading to 1.8.2 but no luck.

![screen shot 2017-10-25 at 6 24 07 am](https://user-images.githubusercontent.com/12229032/31975594-ff410d60-b94f-11e7-9b3d-9e5ba137e8f8.png)

## Expected behavior

Popover should render without any issues.

## Actual behavior

Popover does not render and we get following error:

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

Check the render method of `PopoverOverlay`.
```

## Steps to reproduce the problem

1. Create a new app using `create-react-app`
2. Replace the code in App.js with following
```JSX
import React, { Component } from 'react';
import {
  Page,
  Layout,
  Card,
  Popover,
  ActionList,
  Button,
} from '@shopify/polaris';
import '@shopify/polaris/styles.css';
import './App.css';

class App extends Component {
  render() {
    return (
      <Page>
        <Layout sectioned>
          <Card sectioned>
            <Popover
              active
              activator={<Button>More actions</Button>}
            >
              <ActionList
                items={[
                  {content: 'Import'},
                  {content: 'Export'},
                ]}
              />
            </Popover>
          </Card>
        </Layout>
      </Page>
    );
  }
}

export default App;

```
3. Use command `npm start` or `yarn start` to run the app

## Specifications

- Polaris version: 1.8.2
- React version: 16.0.0
- Browser: Chrome (Version 61.0.3163.100)
- Device: Macbook
- Operating System: macOS High Sierra

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 This repo is for reporting issues and feature requests only

**Comment by cgenevier** [comment]
+1. Having exactly the same problem in my app after upgrading to 1.8.2.

**Comment by cargix1** [comment]
+1

**Comment by dleroux** [comment]
We're looking into this now. Thanks for reporting this.

**Comment by dleroux** [comment]
We have dependency issues. For me adding 

`"react-transition-group”: “^2.2.1"`

to my package.json fixed the issue for now. We are actively working to solve the real issue.

**Comment by dleroux** [comment]
We just release 1.8.3 which should resolve this. Let us know if you still have issues.

**Comment by cgenevier** [comment]
Appears to have fixed my issues. Thanks for the quick solutions!

**Comment by chaddjohnson** [comment]
Nice! Thanks @dleroux, this issue was present for the Tabs component, and now it's fixed as well :)
