### ISSUE TITLE
Is there code or examples of how data visualization is handled?

### ISSUE THREAD

**Issue by joshbedo** [Shopify/polaris#212]
Is it possible to do data visualization with Polaris? For example, if I have a Shopify app display revenue for yearly, monthly, daily or other data on charts matching the Shopify style guide but injecting my own data segments.

**Comment by joshbedo** [comment]
Alright, It just wasn't clear to me if any react components were released. Alright I'll give HighCharts or D3 a shot. Thanks!

I skimmed the design guidelines last time but I'll be sure to read through it again more closely as I'm building the component(s) out.

**Comment by ry5n** [comment]
It’s worth noting for others that there are some other reasons we haven’t yet shipped data visualization components:

- Dependencies: dataviz can be pretty complex, and we’re reluctant to include a whole dataviz library with Polaris React. If we did decide to release something, it might well be as a separate library.
- Licensing: HighCharts is a commercial product. If Shopify chose it to power the dataviz for any of our apps, that would prevent us from sharing those components as part of a Polaris library.
