### ISSUE TITLE
Split components package into components, atoms, and themes

### ISSUE THREAD

**Issue by aveline** [Shopify/polaris#213]
@samrose3

> Explore splitting the components package from the atoms (perhaps a css or atoms package) and also maybe a themes package?
> components => {components, css, themes}
> Some pros:
> - Allow non-React uses to leverage atoms
> - Split concerns of atomic styles and React component
> - House themes in separately for easier code-splitting and not to be bundled with the atoms
> - Improve versioning perhaps… I can see the React components maybe updating a lot, but atoms and themes updating on a different cadence
> Cons:
> - More packages

@chloerice 

> Coming from a perspective of developing in  web , importing from a several packages feels normal and actually helpful in finding what I need (quilt packages and the symlinked packages built and used within the web repo itself are both really modular in this way).

**Comment by samrose3** [comment]
Closing based on comments in #216
