### ISSUE TITLE
Breadcrumbs not accepting onAction

### ISSUE THREAD

**Issue by jayknott** [Shopify/polaris#214]
# Issue summary

For breadcrumbs, it seemsthat onAction is no longer working.  In the 1.7 release notes it says that it was added.  I am now running 1.8.3 and it is not executing my onAction function.

## Expected behavior

onAction functions execute on click.

## Actual behavior

Nothing happens.  If url is not used, the breadcrumb doesn't even render as clickable.

## Steps to reproduce the problem

Crate a page with a breadcrumb that has an onAction prop and no url prop.

## Specifications

- Polaris version: 1.8.3
- React version: 15.6.1
- Browser: Chrome 61.0.3163.100 
- Device: PC
- Operating System: Windows 10 1703

**Comment by tmlayton** [comment]
Hi @jayknott, an `onAction` callback will only work if being used as a child of `<EmbeddedApp>`. In this example, the breadcrumb will trigger an alert:

```jsx
<EmbeddedApp>
  <Page 
    title="Page title"
    breadcrumbs={[
      {content: 'Breadcrumb', onAction: () => alert()},
    ]}
  >
    <p>Page content</p>
  </Page>
<EmbeddedApp>
```

If both `url` and `onAction` are provided, the `url` will be used and the callback will be ignored. In this example, clicking the breadcrumb will direct to `path/to/page`:

```jsx
<EmbeddedApp>
  <Page 
    title="Page title"
    breadcrumbs={[
      {content: 'Breadcrumb', url: 'path/to/page', onAction: () => alert()},
    ]}
  >
    <p>Page content</p>
  </Page>
<EmbeddedApp>
```

**Comment by tmlayton** [comment]
I have opened an internal issue to update the release notes to clarify this applies to `<EmbeddedApps>` only.
