### ISSUE TITLE
Feature Request: Add onAction for breadcrumbs in non-embedded apps

### ISSUE THREAD

**Issue by jayknott** [Shopify/polaris#216]
# Issue summary

onAction only works for breadcrumbs in embedded apps.

## Expected behavior

Allow onAction to be used for non-embedded apps.  For example, I would like to use react router to navigate and that is not possible with a simple link.

**Comment by tmlayton** [comment]
Thanks for creating the issue @jayknott. We will post back here with an update soon.

**Comment by jayknott** [comment]
Since you added the ability for OnClick in UnstyledLinks, it would be super simple to add OnAction to breadcrumbs:

`import * as React from 'react';

import Icon from '../Icon';
import UnstyledLink from '../UnstyledLink';
import {LinkAction} from '../../types';
import {handleMouseUpByBlurring} from '../../utilities/focus';

import * as styles from './Breadcrumbs.scss';

export interface Props {
  breadcrumbs: Action[],
}

export default class Breadcrumbs extends React.PureComponent<Props, never> {
  render() {
    const {breadcrumbs} = this.props;
    const breadcrumb = breadcrumbs[breadcrumbs.length - 1];
    if (breadcrumb == null) { return null; }

    const {content, url, onAction} = breadcrumb;

    const control = url
      ? <UnstyledLink url={url} onClick={onAction} className={styles.Item}>
          <span className={styles.Icon}><Icon source="chevronLeft" /></span>
          <span className={styles.Content}>{content}</span>
        </UnstyledLink>
      : <UnstyledLink onClick={onAction} className={styles.Item}>
          <span className={styles.Icon}><Icon source="chevronLeft" /></span>
          <span className={styles.Content}>{content}</span>
        </UnstyledLink>

    return (
      <nav role="navigation">
        {control}
      </nav>
    );
  }
}`

**Comment by ry5n** [comment]
@jayknott We’re still tracking this as an idea to explore in our internal backlog. However, I can’t commit to a timeline, so what I’d like to do is close this for now.

We definitely **encourage everyone who’s passionate about this feature to add a 👍 to the issue summary**. It will help us to prioritize what to work on next.

Thanks! 💜
