### ISSUE TITLE
Select components cannot be marked as required

### ISSUE THREAD

**Issue by chaddjohnson** [Shopify/polaris#222]
# Issue summary

Is it not possible to mark a `<Select>` component as `required`. Without this, select list elements cannot be validated in forms using standard HTML5 form validations.

## Expected behavior

It should be possible to mark a `<Select>` component as required, and this attribute should be passed down to the resulting HTML. Please see [w3schools](https://www.w3schools.com/tags/att_select_required.asp).

I believe it is important to note that the placeholder being selected does not count as the select list having a value. The expression `document.getElementById('selectId').value` yields `__placeholder__` when the placeholder is selected; I believe this should be accounted for.

## Actual behavior

The `required` attribute is ignored on `<Select>` component instances.

## Steps to reproduce the problem

1. Create a `<Select>` component.
1. Add the `required` attribute to the component.
1. Inspect the resulting HTML, and there is no `required` attribute on the element.

## Specifications

- Polaris version: 1.8.3
- React version: 16
- Browser: Chrome
- Device: MacBook
- Operating System: Mac OS High Sierra

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 This repo is for reporting issues and feature requests only

**Comment by chloerice** [comment]
Hey @chaddjohnson, definitely agree that Select should be passing that prop along. I'll audit the other form fields to make sure they're requirable as well and get that out for 1.9.0!

**Comment by chloerice** [comment]
@chaddjohnson after discussing this issue with the team, I've learned that we chose custom form validation over supporting `required` and other HTML5 native validation attributes in order to ensure forms across Shopify are consistent and accessible.

By utilizing the optional `error` prop when using select, text field, or checkbox components, your custom error messages are both visually displayed and announced on focus via the `aria-describedby`, `aria-required`, and `aria-invalid` attributes to convey the current state to folks who use a screen reader.

<details>

<summary>
    Click to see a full example of how you can use the `error` prop to validate form fields
</summary>

```jsx
import React, {Component} from 'react';
import {Page, Card, FormLayout, Select, TextField} from '@shopify/polaris';

export default class CustomDiscountForm extends Component {
  constructor(props) {
    super(props)
    this.state = {
      // initially set to null (vs an empty string) so the placeholder works as expected
      discountType: null,
      discountCode: '',
    }
  }

  handleChange = (type) => (value) => {
    this.setState({[type]: value, [`${type}Error`]: false});
  }

  validate = (type, message) => () => {
    const value = this.state[type];
    if (!value || (type === 'discountCode' && value.length < 4)) {
      return this.setState({[`${type}Error`]: message});
    }
    this.setState({[`${type}Error`]: false})
  }

  render() {
    return (
      <Page title="Create a custom discount">
        <Card>
          <Card.Section>
            <form>
              <FormLayout>
                <Select
                  label="Type of discount"
                  options={[
                    'Percent',
                    'Dollar amount',
                  ]}
                  value={this.state.discountType}
                  placeholder="Select a discount type"
                  onChange={this.handleChange('discountType')}
                  onBlur={this.validate('discountType', 'Discount type is required.')}
                  error={this.state.discountTypeError}
                />
                <TextField
                  label="Discount code"
                  value={this.state.discountCode}
                  onChange={this.handleChange('discountCode')}
                  onBlur={this.validate('discountCode', 'Discount codes must be at least 4 characters long.')}
                  error={this.state.discountCodeError}
                />
              </FormLayout>
            </form>
          </Card.Section>
        </Card>
      </Page>
    );
  }
}
```

</details>
<br/>

![formvalidation](https://user-images.githubusercontent.com/18447883/33968698-5d101176-e037-11e7-8171-f7e27801f941.gif)

**Comment by chaddjohnson** [comment]
@chloerice `required` not being passed down to a `<select>` element poses a big problem as `document.getElementById('formId').checkValidity()` returns true even when the select has no value. There is no way to enforce a `<select>` field being required if `required` is not passed down. It's great that we have the `error` prop, but it is only useful insofar as showing an error; it is totally useless in regards to native HTML5 form validation, which is why `required` needs to be passed down.

**Comment by chloerice** [comment]
@chaddjohnson There's no need to use a DOM method to validate the field. You'll have more fine-grained control and better performance utilizing custom validation. I've updated the example above to include how to declaratively block form submittal when a form field is invalid.

**Comment by chaddjohnson** [comment]
@chloerice I appreciate the Polaris toolkit, but I strongly disagree with this solution, and I don't like that this form validation approach is being forced on users.

HTML5 form validation provides [many different validity checks](https://www.w3schools.com/js/js_validation_api.asp) in addition to required...patterns, min, max, type, and others.

I specifically want to tie validation rules to the elements themselves by defining them as attributes of components/elements. For example, I have this:

```html
<TextField
    id="newCreditCard-cardNumber"
    label="Card number"
    value={this.state.newCreditCard.cardNumber}
    minLength={13}
    maxLength={19}
    pattern="\d+"
    inputMode="numeric"
    onChange={this.handleNewCreditCardFieldChange}
    onFocus={this.handleNewCreditCardFieldFocus}
    onBlur={this.handleNewCreditCardFieldBlur}
    error={this.state.validationErrors['newCreditCard-cardNumber'] || false}
    required
/>
```

If I were to move validity checks for this and all other form fields to the `isInvalid()` function, this function would be **huge** and unruly. It's not how I want to do it.

I don't imagine it is difficult to simply pass down the `required` flag for a `<select>` field. I wish the team would reconsider.

**Comment by chaddjohnson** [comment]
Here is a workaround for anyone interested:

```javascript
componentDidUpdate(prevProps, prevState) {
    const creditCardCountryElement = document.querySelector('#newCreditCard-country');

    if (creditCardCountryElement) {
        creditCardCountryElement.required = true;
    }
}
```

Ideally I would use a `ref`, but that doesn't work either :-/
