### ISSUE TITLE
Not able to found table component in https://polaris.shopify.com/

### ISSUE THREAD

**Issue by NirajSavaliya** [Shopify/polaris#223]
I not able to found table component in https://polaris.shopify.com/

**Comment by ry5n** [comment]
Thanks for voicing this. We’re in the process of building a table component and plan to include it in a release as soon as possible. 

In the meantime there are a couple of options.

You may be able to use a different component. Tables are great when the merchant goal is to understand a set of data. It’s a data visualization really. On the other hand, If the merchant is managing a set of objects (like a list of orders) we have the [ResourceList component](https://polaris.shopify.com/components/lists/resource-list). There’s a major update to that component on the way as well, which adds row selection and other features.

If the merchant goal you’re supporting is data analysis, your best bet for now is to use a basic HTML `<table>` styled like as in our Sketch UI kit, available on [the resources page](https://polaris.shopify.com/resources/resources). It looks like so:

![screen shot 2017-11-17 at 9 38 08 am](https://user-images.githubusercontent.com/804014/32952364-0fed6cac-cb7b-11e7-8308-16ef03a48996.png)

Finally, figuring out how to improve our communication and share our roadmap with you. Stay tuned.

**Comment by chloerice** [comment]
Hey @NirajSavaliya, DataTable component is available in v2.0.0-beta.10! Check out the documentation on the [beta version of the style guide](https://polaris-v2.shopify.com/components/lists/data-table#navigation).

**Comment by NirajSavaliya** [comment]
@chloerice 
thanks for update 
we will change this in our shopify plugins
