### ISSUE TITLE
when we use `onChange` callback function, the value is not updating on the UI.

### ISSUE THREAD

**Issue by derekmorin** [Shopify/polaris#226]
# Issue summary

When we use `onChange` callback function, the value is not updating on the UI.

`<Select label="Store Fields" options={$this.state.fields} onChange={ function(val, id){console.log(val);} } labelHidden placeholder="Select" />`
This is what we're trying.
When we use `onChange`, it doesn't change value from placeholder.

## Steps to reproduce the problem

1.
1.
1.

## Specifications

- Polaris version:
- React version:
- Browser:
- Device:
- Operating System:

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 This repo is for reporting issues and feature requests only

**Comment by lemonmade** [comment]
You’ll need to provide a little more information here. What component are you trying to use? Do you have some example code we could take a look at?

**Comment by chloerice** [comment]
Hey @derekmorin, from the code you provided it looks like you're missing the value prop that Select requires. Here's what that looks like using your example code: 

```jsx
import * as React from 'react';
import {Page, Select, FormLayout} from '@shopify/polaris';

export default class Playground extends React.Component<never, State> {
  constructor(props) {
    super(props);
    this.state = {
      store: ''
    }
  }

  handleChange = (newValue, id) => {
    console.log(`Selected store: ${newValue}`)
    this.setState({store: newValue})
  }

  render() {
    return (
      <Page title="Playground">
        <FormLayout>
          <Select
            labelHidden
            label="Store"
            options={[
              'Ottawa',
              'Toronto',
              'Montreal'
            ]}
            value={this.state.store}
            onChange={this.handleChange}
            placeholder="Select a store"
          />
        </FormLayout>
      </Page>
    );
  }
}
```

**Comment by elitedan0401** [comment]
Is there way to set the value directly without state or similar variable?

**Comment by chloerice** [comment]
@elitedan0401, while this would defeat the purpose of using React, you could resort to using a ref, but as the input itself is wrapped in other elements it would be unnecessarily complicated to reach down the DOM tree to grab the value. In general state is the easiest, most performant way to handle forms.
