### ISSUE TITLE
Help online store ship new icons to Polaris

### ISSUE THREAD

**Issue by kyledurand** [Shopify/polaris#226]

**Comment by sarahill** [comment]
Paired with Rozina today on some ideation and questions about icons. She's going to do some more iteration / clean up and reach back out with what she wants to contribute back.

- explored variations of what a icon for "button" could look like
- cleaned up stroke widths on some of the other icons

<img width="503" alt="Screen Shot 2021-08-17 at 7 50 33 PM" src="https://user-images.githubusercontent.com/8629173/129829408-379097aa-394f-4e75-8236-2172af6d3427.png">
