### ISSUE TITLE
Fullscreen embedded youtube/vimeo videos not possible 

### ISSUE THREAD

**Issue by cargix1** [Shopify/polaris#231]
# Issue summary

When embedding Youtube or Vimeo videos within the EmbeddedApp component fullscreen mode is disabled as the parent app iframe does not include a "allowFullScreen" param.

## Expected behavior

I'd hope to allow merchants to view my on-boarding/instructional videos in fullscreen directly from within my app.
 
## Actual behavior

At the moment the fullscreen buttons on both Youtube and Vimeo are disabled because the parent iframe of the app does not include the "allowFullScreen" param. 

## Steps to reproduce the problem

1. Add the following code within an EmbeddedApp component.  

```
<iframe src="https://player.vimeo.com/video/237551523?color=bf5915&portrait=0" width="640" height="268" frameborder="0" allowFullScreen></iframe>
```

2. Notice you will not see the fullscreen button. 

<img width="606" alt="screen shot 2017-11-23 at 23 38 04" src="https://user-images.githubusercontent.com/9730290/33190717-d6f04bfe-d0a7-11e7-960c-8b15696aa8eb.png">

3. Copy and paste the same code in an empty html file without using the EASDK and notice the fullscreen button appears. 

## Possbile solution 

Would it be possible to add an allowFullScreen attribute to the EmbeddedApp iframe so that we can allow fullscreen video playback?

## Specifications

- Polaris version: 1.8.3
- React version: 15.6.1
- Browser: Chrome (latest)
- Device: MacBook Pro
- Operating System: Sierra

**Comment by nwtn** [comment]
Thanks for your suggestion! We’ve added this to our backlog and are keeping it in mind as we build out our roadmaps. I’ll leave this issue open for the time-being so we can update it when we’re able to share more concrete plans.

**Comment by ry5n** [comment]
Quick update: we’re adjusting out approach to issues a little bit, to keep things focused on bugs and fixes. Like Dave mentioned, w have this issue in our backlog to tackle in the future and we’ll share concrete plans in the future.

**We encourage everyone who wants this feature to add a 👍** to the original issue report. We’ll take everyone’s interest into account when we look at what to work on next.

💜
