### ISSUE TITLE
Incorrect validation error style with TextField type=url in Firefox Quantum

### ISSUE THREAD

**Issue by Tiendq** [Shopify/polaris#233]
# Issue summary

Validation error style is incorrect if `TextField` `type` is `url`

## Expected behavior

It must be same as `TextField` `type` is `text` (default).

## Actual behavior
<img width="873" alt="screen shot 2017-11-28 at 8 59 45 am" src="https://user-images.githubusercontent.com/815910/33298881-7cb6f1e8-d41b-11e7-85b6-4afb50850a96.png">

Wrong padding, see attached image.

## Steps to reproduce the problem

https://polaris.shopify.com/components/forms/text-field#navigation

## Specifications

- Polaris version: current
- Browser: Firefox Quantum 57.0
- Operating System: macOS

**Comment by chloerice** [comment]
Hi @Tiendq, thanks for taking the time to bring this to our attention! This problem has been fixed and will roll out with the 1.9.0 release We hold off on releases around Black Friday/Cyber Monday to ensure stability for our merchants, so stay tuned for the next release at the beginning of December.
