### ISSUE TITLE
Icons: request for svg report icon

### ISSUE THREAD

**Issue by helloneele** [Shopify/polaris#234]
# Issue summary

There is no SVG `report` icon included with the Shopify Polaris SVG icons.
I am currently working on rebuilding Home in `Shopify/web` and struggling to rebuild this toggle sidebar button (View summary).

Current Home:
![image](https://user-images.githubusercontent.com/6950534/33447201-9094ae4c-d5d0-11e7-923a-5da5b7c83ec0.png)

**Comment by CameronGorrie** [comment]
Neele also pointed out a previous icon request. The [suggestion there](https://github.com/Shopify/polaris/issues/211#issuecomment-344295070) was to add our own icon for the time being until it was officially added to Polaris. Is this still the suggested approach @dfmcphee, @tmlayton?

**Comment by dfmcphee** [comment]
Yep, that is correct @CameronGorrie. I would just add the icon to your project folder and import it from there.

**Comment by dfmcphee** [comment]
Going to close this as we won't be adding the icon here.
