### ISSUE TITLE
[ResourceList] / ResourceItem do not re-render when updated and selected

### ISSUE THREAD

**Issue by loic-d** [Shopify/polaris#2357]
## Issue summary

`ResourceItem` in a `ResourceList` won't re-render when updated and selected.

Example on the Product Details page > Multilocation variants card.

![Oct-24-2019 12-53-27](https://user-images.githubusercontent.com/3925905/67523317-72911880-f67c-11e9-96b5-8c3273bb86e3.gif)

You can also look at this [Codesanbox](https://codesandbox.io/s/spring-mountain-g4ynz).

## Expected behavior

Items should re-render even when they are selected.

## Steps to reproduce the problem

1. Select items in a resource list
1. Find a way to update the items (see provided Codesanbox)
1. Items don't re-render until they are unselected

## Reduced test case

I was able to [repro the problem in this Codesandbox](https://codesandbox.io/s/spring-mountain-g4ynz). 

## Specifications
```bash
System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 2.44 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.11.0 - ~/.nvm/versions/node/v10.11.0/bin/node
    Yarn: 1.12.3 - ~/.dev/yarn/1.12.3/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.11.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 78.0.3904.70
    Firefox: 69.0.3
    Safari: 12.1.1
  npmPackages:
    @shopify/polaris: 4.7.1 => 4.7.1 
    react: 16.9.0-alpha.0 => 16.9.0-alpha.0 
    react-dom: 16.9.0-alpha.0 => 16.9.0-alpha.0 
```

**Comment by nyze2oo9** [comment]
I'm facing this issue as well. Is there any workaround to rerender ResourceItem without unselecting it?

**Comment by loic-d** [comment]
We are currently re-rendering by updating the `key` prop on the element.

**Comment by ivosabev** [comment]
+1

**Comment by mako10110** [comment]
+1 can't believe this isn't solved yet

**Comment by codemicky** [comment]
Thank you, @mako10110 !

**Comment by brightraudona** [comment]
doesn't work, only if you change the key on the whole list, not the element, but it looks really bad.

**Comment by pieperz** [comment]
Found something that is working as I expect.

In all the docs a `key` prop is never shown. But in my component, I'm paginating and doing multi-select across those pages.

This was broken down to 2 issues, first was adding the `key` prop, to fix the pagination and correctly render new data.

```
function renderItem(item) {
    const {id, url, name, location} = item;
    const media = <Avatar customer size="medium" name={name} />;

    return (
      <ResourceItem
        id={id}
        key={id} // Missing from docs
        url={url}
        media={media}
        accessibilityLabel={`View details for ${name}`}
      >
        <Text variant="bodyMd" fontWeight="bold" as="h3">
          {name}
        </Text>
        <div>{location}</div>
      </ResourceItem>
    );
  }
```

The second issue is on pagination new data is fetched and all selected item data is lost. To fix this I created another useState where I accumulate and sync the ResourceList selected items as they are select. 

```
const [selectedItems, setSelectedItems] = useState([abc])
const [selectedItemsData, setSelectedItemsData] = useState([{id: abc, name:"something", url: "google.com"}]) 
```

Now a user can go to several pages select an item on each page, then when the selected data is needed I have everything in the `selectedItemsData` array.

Hope this helps 🤷
