### ISSUE TITLE
Yarn does not have the most recent release

### ISSUE THREAD

**Issue by jasonbuehler** [Shopify/polaris#238]
Yarn does not have any version of Polaris higher than 1.2.1. I am trying to use the Skeleton components but they aren't present. I am using yarn 0.24.6, tried using yarn upgrade and also yarn upgrade polaris@1.8.3 to no avail. Any advice?

**Comment by kaelig** [comment]
Thank you for asking, @jasonbuehler. The `polaris` package is pointing to another project. To install and upgrade this project, you'll need to prefix it with the `@shopify/` scope:

```
yarn upgrade @shopify/polaris@1.8.3
```

Let us know if this works for you!

**Comment by jasonbuehler** [comment]
Thanks @kaelig ! I guess I should rtfm since it's top center on the README. :D
