### ISSUE TITLE
easdk.pushState('') adds '/' to the end of the url

### ISSUE THREAD

**Issue by tim-phillips** [Shopify/polaris#239]
# Issue summary

Calling `this.context.easdk.pushState('')` adds `/` to the end of the url in the address bar. I know this seems small, but it is strange to see the url change by a character on page load. 

## Expected behavior

When using `pushState` to reset the address bar back to the root of the app, an empty `location` string in `pushState` should render the address bar as `https://my-store.myshopify.com/admin/apps/app-name`.

## Actual behavior

Calling `this.context.easdk.pushState('')` changes the url in the address bar to `https://my-store.myshopify.com/admin/apps/app-name/` (note the trailing `/`).

## Steps to reproduce the problem

Call `this.context.easdk.pushState('')` in `componentDidMount()`.

## Specifications

- Polaris version: 1.8.3
- React version: 16
- Browser: Chrome latest
- Device: Desktop
- Operating System: macOS

**Comment by nwtn** [comment]
Thanks for your suggestion!

Is this causing any unwanted behaviour other than the visual representation of the URL in the address bar?

**Comment by tim-phillips** [comment]
@nwtn just the visual

**Comment by ry5n** [comment]
I love the care for the details, especially when it comes to URLs. A lost art, some might say 😔. However, since this doesn’t affect functionality or URL readability, we’re not going to be able to prioritize this.
