### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/polaris#240]
Polaris Page object has no concept of a footer to place information. Please add a footer to complement the header. 

Polaris has nothing to support displaying images beyond the odd thumbnail or avatar. Please add a basic container where images can be displayed without too much trouble.

**Comment by ry5n** [comment]
The [PageActions component](https://polaris.shopify.com/components/structure/page-actions) is the standard footer for actions on an individual product/order/customer page. We should probably link to it from the Page component though, hey? 🙃 

If you need something else, like a custom page footer, you should be able to build what you need and place it as the last child of the Page component. Let us know if you have something else in mind.

For images, are you looking for something with more features than the basic `img` tag? There might be some use cases (deferred loading maybe, or specific sizes) but we haven’t seen them come up much. Again, let us know if you’re needing something more than `img`.

**Comment by resistorsoftware** [comment]
I added a custom <footer> to <Page>. Ok on the use of the old <img> tag.

PageActions is not a footer in the sense I requested, it is merely a button at the bottom of a form.
