### ISSUE TITLE
resource list can put more than 3 columns by text and button?

### ISSUE THREAD

**Issue by munloong** [Shopify/polaris#241]
# Issue summary

was trying to put more than 3 columns by text and button

## Expected behavior
Hope it can work

## Actual behavior
if cannot by using resource list, might to make table tag 

## Steps to reproduce the problem

  items={[
    {
      url: '#',
      attributeOne: 'How to Get Value from Wireframes',
      attributeTwo: 'by Jonathan Mangrove',
      attributeThree: <TextStyle variation="subdued">Today, 7:14pm</TextStyle>,
     <-- can be more column?-->
    },
    {
      url: '#',
      attributeOne: 'Test blog post',
      attributeTwo: 'by Jonathan Mangrove',
      attributeThree: <TextStyle variation="subdued">Jan 14, 2016, 8:24am</TextStyle>,
      badges: [{content: 'Hidden'}],
     <-- can be more column?-->
    },
  ]}

## Specifications

- Polaris version:1.8.3
- React version:16
- Browser:Latest Google Chrome
- Device:Laptop
- Operating System:Latest Mac OS

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 This repo is for reporting issues and feature requests only

**Comment by dfmcphee** [comment]
Hi @munloong. The generic `ResourceList.Item` only supports three custom attributes, but you can also use your own custom item component in the `renderItem` function. This allows you to use whatever data and layout you want for the items within a resource list.

I should mention we have some big improvements coming to ResourceList in v2.0, so stay tuned.

**Comment by munloong** [comment]
interesting, can't wait for it
