### ISSUE TITLE
TextField with the type of `number` is not showing the correct value

### ISSUE THREAD

**Issue by cargix1** [Shopify/polaris#243]
# Issue summary

TextField with the type of `number` is not showing the correct value. 

## Expected behavior

I'd expect that when I pass a value to the TextField it would reflect the exact value provided. 

## Actual behavior

No matter what value I pass to the TextField when the `type` property is set to `number` the value is always prepended with 0. Unless the merchant clicks into the field first and presses backspace to delete the default value of 0. 

## Steps to reproduce the problem

1. Create a TextField component with the type set to `number`. 
```
 <TextField
    placeholder="0.00"
    type="number"
    min="0"
    onChange={value => this.handleChange('min_value', parseInt(value, 10))}
    value={props.min_value}
  />
```

2. The field will contain the value of `0` by default. Place the cursor after the `0` and enter `123`. The parseInt function should remove the initial zero and update the value to `123`. Feel free to use your own method of stripping the initial 0, but no matter what you try the component always display the value of `0123`.

If you remove the `type` property the same code will work as expected and remove the initial 0. 

## Specifications

- Polaris version: 1.8.3
- React version: 15.6.1
- Browser: Chrome
- Device: Macbook Pro
- Operating System: High Sierra

**Comment by ridem** [comment]
It may be because you're not properly handling the "value" of your component. I quickly reimplemented your issue and had it working. So I suggest implementing your form with [controlled components' method](https://reactjs.org/docs/forms.html#controlled-components).


[Screencast](https://streamable.com/kwh1u)

**Code**
```js
constructor() {
  ...
  this.state = {
    min_value: 0
  }
}
```
In `render()`:
```jsx
<TextField
  label="My label"
  placeholder="0.00"
  type="number"
  min="0"
  onChange={value => this.setState({min_value: parseInt(value, 10)})}
  value={this.state.min_value}
/>
```

**Comment by ry5n** [comment]
@cargix1 Did ridem’s solution solve the issue for you?

**Comment by ry5n** [comment]
Polaris does require using controlled components. Let us know if you have further issues or questions.

**Comment by ode10xers** [comment]
@cargix1 did you get the solution?
