### ISSUE TITLE
TextField.tsx : error TS2554

### ISSUE THREAD

**Issue by Invader444** [Shopify/polaris#247]
# Issue summary

Build fails with TS2554 error.

## Expected behavior

Successful build.

## Actual behavior

Build fails.
<details>src/components/TextField/TextField.tsx(60,5): error TS2554: Expected 1-2 arguments, but got 0.
</details>

## Steps to reproduce the problem

1. Clone the repository.
2. npm install
3. npm run-script build

## Specifications

- Polaris version: 1.9.1
- React version: 16.2.0
- Browser: n/a
- Device: PC
- Operating System: Windows 7 64-bit

---

**Comment by kaelig** [comment]
Fixed in v1.10.1
