### ISSUE TITLE
Add onAction (or onClick) to ResourceList.Item components

### ISSUE THREAD

**Issue by Invader444** [Shopify/polaris#249]
# Issue summary

Add onAction (or onClick) to ResourceList.Item components.

## Expected behavior

For single-page applications, only providing url for ResourceList.Item is unwieldy, having to rely on `javascript:` urls and out-of-band object registries.

We should instead be allowed to specify an onClick callback (or onAction, to keep things separate, similar to Page breadcrumbs...).

## Specifications

- Polaris version: 1.9.1
- React version: 16.2.0
- Browser: Chrome 64.0.3282.39 (Official Build) beta (64-bit)
- Device: PC
- Operating System: Windows 7 64-bit

---

**Comment by michelleyschen** [comment]
Thank you so much for the contribution @Invader444!

However, the `ResouceList` component is going through significant update right now and this functionality will be part of that update in v2 coming up. 

I am going to close this issue and PR, but keep your eyes on the official release for polaris v2!

**Comment by danizord** [comment]
@michaecleyn do you suggest any workaround for that while v2 is not released?

**Comment by paulisloud** [comment]
Also curious for a ballpark ETA on v2. Making some architecture decisions and would appreciate knowing if we're talking ~2 weeks or 6 months.

**Comment by dfmcphee** [comment]
Hey folks! v2.0 is now in beta with the improved `ResourceList` component. Feel free to try it out and see how it works for you needs. We have the documentation in our beta version of the style guide here: https://polaris-v2.shopify.com/components/lists/resource-list#navigation

We would appreciate any feedback you have on it.

**Comment by kaelig** [comment]
And here is the command to pull Polaris React v2 from npm: `yarn add @shopify/polaris@next` 📦

**Comment by paulisloud** [comment]
Awesome! Looking at the repo, is CHANGELOG_V2 exhaustive / up to date as far as breaking changes?

Will give this a try today / this week.

**Comment by kaelig** [comment]
Awesome! [CHANGELOG_V2.md](https://github.com/Shopify/polaris/blob/v2/CHANGELOG_V2.md) has been kept up to date all along, but please let us know if anything is unclear.

**Comment by paulisloud** [comment]
Trying it, and i'll post a separate issue if this is more than just something I'm missing, but I yarn added the 2.0 beta and dropped in the ResourceListExample from the 2.0 docs, and get

`
index.es.js:7802 Uncaught TypeError: Cannot read property 'intl' of undefined
    at new ResourceList (index.es.js:7802)
`

**Comment by dfmcphee** [comment]
We are still working on clarifying the documentation for this but as of v2 you will now need to wrap your app in our `<Provider>` component: https://polaris-v2.shopify.com/components/behavior/provider#navigation

**Comment by paulisloud** [comment]
Mine is wrapped in a provider, just not as an immediate ancestor. Here is my index.js

`
import * as React from 'react';
import 'isomorphic-fetch';
import { render } from 'react-dom';
import { Provider } from 'react-redux';
import { AppContainer } from 'react-hot-loader';
import { Route, Switch } from 'react-router'
import { ConnectedRouter as Router } from 'react-router-redux'

import store, { history } from '../client/store';

import Raven from 'raven-js'
import { sentry_url, logException } from './data/config'

import App from './App';

Raven.config(sentry_url).install()

function renderApp() {
  render(
    <AppContainer>
      <Provider store={store}>
        <Router history={history}>
          <Route path='/' >
            <App />
          </Route>
        </Router>
      </Provider>
    </AppContainer>,
    document.getElementById('root')
  );
}

renderApp();

if (module.hot) {
  module.hot.accept();
}

`

**Comment by dfmcphee** [comment]
Is that the `Provider` from `react-redux` or from `polaris`? You will need to have the Polaris one wrap your app as well to have that work. To avoid naming collisions you can do something like:

`import {Provider as PolarisProvider} from '@shopify/polaris';`

and then to use it:

```jsx
<AppContainer>
  <PolarisProvider>
    <Provider store={store}>
      <Router history={history}>
        <Route path='/' >
          <App />
        </Route>
      </Router>
    </Provider>
  </PolarisProvider>
</AppContainer>,
```

**Comment by paulisloud** [comment]
Boom that was it. Was using only Redux, didn't realize that I would need both.

Probably worth adding to the changelog.

Thanks, testing again...
