### ISSUE TITLE
Checkbox checkmark missing in 1.9.0 in CSS/CDN version

### ISSUE THREAD

**Issue by daddy88** [Shopify/polaris#252]
# Issue summary

The checkbox component does not have the checkmark when checked in version 1.9.0 and higher, it works fine when using version 1.8.3.

This issue is related to the hosted CSS version of Polaris.

## Expected behavior

Expected the little checkmark to appear when a checkbox is checked.

## Actual behavior

Checkbox component stays empty even when checked.
Its only visual, the component works anyways.

## Steps to reproduce the problem

1. Open polaris/examples/cdn-styles/index.html in a browser

## Specifications

- Polaris version: 1.9.0 and 1.9.1
- React version: N/A
- Browser: Safari 11.0.2 and Chrome 63.0.3239.84
- Device: Desktop
- Operating System: OSX 10.13.2

**Comment by ry5n** [comment]
Thanks for raising this. We’ve identified the issue and we’re working on a fix for release as soon as possible.

**Comment by monmon-dotdev** [comment]
Hello, wondering if this was fixed and released to https://sdks.shopifycdn.com/polaris/latest/polaris.css

Many thanks :)

**Comment by chloerice** [comment]
Hey @monmon-dotdev, I merged the fix and it should be released today. I'll ping and @daddy88 you once it is!

**Comment by chloerice** [comment]
@daddy88 @monmon-dotdev 1.10.1 has been released with the fix!

**Comment by monmon-dotdev** [comment]
Yay! Thanks a lot :)
