### ISSUE TITLE
Proposal: Skeleton prop 

### ISSUE THREAD

**Issue by dunckr** [Shopify/polaris#253]
Hi

Thanks for making this component library - I’m enjoying working with it.

I really like the UX of the skeleton components. However, I feel like the API could be changed slightly and would make it much easier to ensure that skeleton structure never gets out of date.

Currently:

```js
class App extends Component {
	render() {
		const { isLoading } = this.props;
		return (
			<div>
				{isLoading && (
					<SkeletonPage title={pageTitle} separator secondaryActions={secondaryActions.length}>
						<Layout>
							<Layout.AnnotatedSection title={title}>
								<Card sectioned>
									<SkeletonBodyText lines={5} />
								</Card>
							</Layout.AnnotatedSection>
						</Layout>
					</SkeletonPage>
				)}
				{!isLoading && (
					<Page title={pageTitle} secondaryActions={secondaryActions}>
						<Layout.AnnotatedSection title={title} description={description}>
							<Card sectioned>
								<div>...</div>
							</Card>
						</Layout.AnnotatedSection>
					</Page>
				)}
			</div>
		);
	}
}
```

Proposal:

```js
class App extends Component {
	render() {
		const { isLoading } = this.props;
		return (
			<Page title={pageTitle} secondaryActions={secondaryActions} skeleton={isLoading}>
				<Layout.AnnotatedSection title={title} description={description} skeleton={isLoading}>
					<Card sectioned skeleton={isLoading}>
						<div>...</div>
					</Card>
				</Layout.AnnotatedSection>
			</Page>
		);
	}
}
```

**Comment by dfmcphee** [comment]
Hey @dunckr. Thanks for the suggestion. We had actually considered an API similar to what you are proposing when we built the component. We decided to go the way that we did because we found we were always changing the blocks of content between the loading and non loading state so it made it more clear to just swap the entire block based on the loading state rather than just pass a prop through.

**Comment by ry5n** [comment]
Since we considered something like this and chose a different route I’m going to close this. But we’re always open to additional feedback.
