### ISSUE TITLE
Buttons on Resource List cannot be clicked.

### ISSUE THREAD

**Issue by cesarho** [Shopify/polaris#254]
# Issue summary

The Button in the resources list cannot be clicked. 

The following items passed to ResourceList:
```jsx
  {
      attributeOne: 'Product Name',
      attributeTwo: 'Variant Name',
      attributeThree: <ButtonGroup segmented>
        <Button plain>Edit</Button>
        <Button icon="delete" onClick={this.handleDelete}></Button>
      </ButtonGroup>
    }
```

## Expected behavior

The button could be clicked and call the onClick functions.

## Actual behavior

When mouseover the button, it even won't change to pointer.

## Steps to reproduce the problem

1. Create the resources list as described
2. Test via browser

## Specifications

- Polaris version: 1.1.1
- React version: 16.2.0
- Browser: Chrome
- Device: MacBook Pro
- Operating System: MacOS

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 This repo is for reporting issues and feature requests only

**Comment by babenzele** [comment]
Same with links, no pointer and no click event.

@ry5n Is there an ETA on the new ResourceList component? We're trying to plan for our launch and are trying to determine whether we need to roll our own.

**Comment by kaelig** [comment]
I see `Polaris version: 1.1.1`, did you mean `Polaris version: 1.10.1`?

**Comment by ry5n** [comment]
For your use case you can try the `actions` prop, as long as those actions are available on the page the item links to: `<ResourceList.Item actions={[{content: 'Action', url: 'path/for/route'}] />`

The upcoming version of this component is designed to support more flexible clickable children, although you may need to preventDefault in your handler. 

The upcoming version will be part of a Polaris 2.0, but it’s available now as part of [an early beta](https://github.com/Shopify/polaris/releases/tag/v2.0.0-beta.4). Two caveats: documentation hasn’t  been updated yet (working on it), and of course this is a beta so the API could change before a final release.

**Comment by ry5n** [comment]
The 2.0, the resource list component now accepts arbitrary content, including actions, although you may need to `preventDefault`. Check out the new documentation: https://polaris.shopify.com/components/lists/resource-list
