### ISSUE TITLE
Help Text add link , button plain or popover

### ISSUE THREAD

**Issue by munloong** [Shopify/polaris#256]
# Issue summary

Help text cannot add other polaris component

## Expected behavior

  Add for new feature

## Actual behavior

  Got anyway to add help text with link or button plain?

## Specifications

- Polaris version:latest
- React version:latest
- Browser:google chrome
- Device:laptop
- Operating System:mac os high sierra

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 This repo is for reporting issues and feature requests only

**Comment by ridem** [comment]
You can actually add components in helpText

**Code:**
```jsx
<TextField
  multiline
  label="How did you hear about us?"
  placeholder="Website, ads, email, etc."
  value={this.state.autoGrow}
  onChange={this.valueUpdater('autoGrow')}
  helpText={<div>Some text <Link>A Polaris Link</Link></div>}
/>
```
**Output:**
<img width="624" alt="screen shot 2018-01-25 at 18 38 30" src="https://user-images.githubusercontent.com/3911747/35403132-1109a230-01ff-11e8-985c-d1b838f741ba.png">

**Comment by munloong** [comment]
cool
