### ISSUE TITLE
Link to download UI Kit is broken on https://polaris.shopify.com/resources/resources 

### ISSUE THREAD

**Issue by nickywalsh** [Shopify/polaris#257]
Link to download UI Kit (Sketch) is broken on https://polaris.shopify.com/resources/resources.

Takes you to: https://github.com/Shopify/polaris/releases/download/v2.0.0-beta.4/Sketch.UI.Kit.zip which is a 404 page on Github

**Comment by kaelig** [comment]
Thank you for letting us know, the beta version of Polaris was deployed inadvertently. Apologies for the inconvenience! The issue should be resolved in the next few minutes.
