### ISSUE TITLE
Add onAction to home link

### ISSUE THREAD

**Issue by tim-phillips** [Shopify/polaris#260]
# Feature Request summary

This feature would run an `onAction` function when the user clicks the home link, so that the app may route internally, rather than the app reloading from scratch each time.

I'm using Developer Tools as an example. What I'm calling the home link is in the rectangle:

<img width="813" alt="screen shot 2018-01-29 at 4 14 38 pm" src="https://user-images.githubusercontent.com/3578574/35541486-e38fe5a8-050f-11e8-9358-aac885b5c9dc.png">

## Actual behavior

Currently, when the user clicks the home link, the entire page is reloaded and the app has to load again.

## Specifications

- Polaris version: 1.10.2
- React version: 16.2.0
- Browser: Chrome latest
- Device: Desktop
- Operating System: macOS

**Comment by m20io** [comment]
👍

**Comment by nwtn** [comment]
Thanks for your suggestion! We’ve added this to our backlog and are keeping it in mind as we build out our roadmaps. I’ll leave this issue open for the time-being so we can update it when we’re able to share more concrete plans.

**Comment by ry5n** [comment]
We’re hard at work on some key improvements to the EASDK. I can’t comment on specific features, but as always for feature requests, upvoting this issue will help us prioritize. 💜

**Comment by m20io** [comment]
Any updates on this?

**Comment by tim-phillips** [comment]
This was actually really resolved by #1349
