### ISSUE TITLE
[EmptyState] component within content context not displaying svg image

### ISSUE THREAD

**Issue by meandillar** [Shopify/polaris#2611]
## Issue summary

I am using an EmptyState component within a Card. When using an svg the image is 0 x 0 pixels meaning it isn't visible. 

## Expected behavior

Image should be visible.

## Actual behavior

Image is 0 x 0 pixels. This is fixed by giving the wrapping container `Polaris-EmptyState__ImageContainer` a width, for example, of `100%`

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 4.9.1
- Browser: Chrome
- Device: Macbook Pro
- Operating System: Catalina

**Comment by AndrewMusgrave** [comment]
Reproduction: https://codesandbox.io/s/intelligent-bas-2w98s
cc / @chloerice Could this be related to any of your empty state work? Or could your work be fixing this?

**Comment by ConduciveMammal** [comment]
I'm also getting this issue with SVG images. There's seemingly no way to specify a width for the image.

**Comment by aaronadamsCA** [comment]
As of Polaris 6 my SVG images disappeared from `EmptyState`.

I'm injecting this CSS to work around the issue:

```css
.Polaris-EmptyState__ImageContainer {
  width: 24rem;
}
```

What's happening here:

- The empty state component uses a flexbox column.
- Unlike a regular block element, a child of a flex column starts at `0` width, and then grows to the width of its children.
- A PNG `img` defaults to its own width, but an SVG `img` defaults to its parent's width. This is `0`.
- The container takes the width of its children. This is also `0`.
- It appears somebody tried using `flex-basis: 50%` to give the image container width; but `flex-basis` works along the flex axis, so [when `flex-direction` is a column, this controls height instead](https://stackoverflow.com/a/34355447/802414).

**Comment by AndrewMusgrave** [comment]
cc/ @alex-page @kyledurand

**Comment by devopsangel** [comment]
I have sort of the same issue too. Somehow my `margin-left` got `-70%`

Ended up injecting too.

```
.Polaris-EmptyState__Image {
    margin-left: -0% !important;
}
```

**Comment by marc-firebrand** [comment]
Also getting this issue with an SVG in an EmptyState, will inject the css to workaround the issue but would be good to get a fix.

**Comment by alex-page** [comment]
Hey folks, if anyone wants to make a PR to look into resolving this problem I would be happy to review it.
