### ISSUE TITLE
Page secondary actions popover remains visible after trigger button is hidden

### ISSUE THREAD

**Issue by andrewpye** [Shopify/polaris#262]
# Issue summary

Page secondary actions rollup popover remains visible after resizing page to make it large enough for individual secondary actions to be displayed.

## Expected behavior

When the page is made wide enough for the `Actions` button to be hidden and the secondary actions are displayed individually, the popover should disappear as well.

## Actual behavior

The popover remains visible, with the tip div misplaced since the button it's "anchored" to has been hidden:

![page-secondary-actions-popover](https://user-images.githubusercontent.com/5737342/35612544-c48a83c6-0671-11e8-9975-652e8fbb260f.gif)

## Steps to reproduce the problem

See GIF above.

## Specifications

- Polaris version: 1.10.2
- React version: 16.0.2
- Browser: Chrome Canary
- Device: Macbook Pro
- Operating System: macOS Sierra 10.12.6

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 This repo is for reporting issues and feature requests only

**Comment by ry5n** [comment]
Thanks for flagging this @andrewpye. I’ve opened this in our internal issue tracker. However, I can say that since most merchants won’t see this very often, it’s not at the top of our priority list.

**Comment by andrewpye** [comment]
No worries, makes sense @ry5n. Thanks for the update!

**Comment by ry5n** [comment]
We haven’t been able to get to this, so I’ve moved it to our backlog. Feel free to upvote by adding a 👍 to the original issue report. We take the upvotes into account when planning future work.
