### ISSUE TITLE
Is using polaris to build a web app a good idea?

### ISSUE THREAD

**Issue by mdunbavan** [Shopify/polaris#263]
# Issue summary

The question i am asking is in regard to building a webapp. I have a client that wants to be able to allow merchants of their choice to go into the app away from the site through a login interface where they can buy products in bulk and edit orders in bulk.

## Specifications

- Polaris version: Recent
- React version: Recent
- Browser: Most up to date
- Device: Any
- Operating System: Any

What is the scope for the above with Polaris and the embedded SDK?

Thanks,
Mark

**Comment by chaddjohnson** [comment]
Polaris is a fantastic choice for building Shopify apps. As for non-Shopify apps, I don't know.

**Comment by chaddjohnson** [comment]
@mdunbavan Polaris is a fantastic choice for building Shopify apps. As for non-Shopify apps, I don't know.

**Comment by dfmcphee** [comment]
The aim of Polaris is to help you build good merchant facing interfaces for Shopify. If your app fits into the Shopify ecosystem or is merchant facing than I would say it is a good choice. Outside of that it may not be what you are looking for.

Going to close this but feel free to re-open if you have more questions or comments about it.
