### ISSUE TITLE
Page title and actions disappear when wrapped with EmbeddedApp.

### ISSUE THREAD

**Issue by dsankar1** [Shopify/polaris#266]
# Issue summary
The Page component provided by Polaris loses its title and actions when I wrap it with the EmbeddedApp component. 

## Expected behavior
<img width="960" alt="showingtitle" src="https://user-images.githubusercontent.com/31108228/35698170-4d2d86a4-075a-11e8-961b-2d7348df0904.PNG">

## Actual behavior
<img width="960" alt="missingtitle" src="https://user-images.githubusercontent.com/31108228/35698135-39cb4f10-075a-11e8-9a7e-9b8ef39460dd.PNG">

## Steps to reproduce the problem

1. Create Page component with title/actions/etc
1. Wrap Page with EmbeddedApp given the props apiKey="key" and shopOrigin="https://example.myshopify.com"

## Specifications

- Polaris version: 1.9.1
- React version: 16.2.0
- Browser: Chrome
- Device: Laptop
- Operating System: Windows

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 This repo is for reporting issues and feature requests only

**Comment by dfmcphee** [comment]
Hey @dsankar1. Thanks for the issue but this is actually expected. When the `<Page>` component is used within `<EmbeddedApp>` it will use the EASDK to send the title and actions to the admin so that they can display in the embedded app titlebar.

**Comment by dsankar1** [comment]
@dfmcphee Ah gotcha, I thought that might have been the case. Thanks for the response!
