### ISSUE TITLE
Stack an element next to a Card's title

### ISSUE THREAD

**Issue by babenzele** [Shopify/polaris#271]
# Issue summary

I'm trying to put a link to the right of a `Card`'s `title`. 

## Expected behavior

You can see that normally there is spacing between the `Card`'s `title` text and the `TextStyle`:

```javascript
<Layout.Section>
  <Card title='Header text' sectioned>
    <TextStyle variation='subdued'>
      This is some text.
    </TextStyle>
  </Card>
</Layout.Section>
```

<img width="480" alt="screen shot 2018-02-13 at 5 29 57 pm" src="https://user-images.githubusercontent.com/3578574/36183890-6da790ac-10e5-11e8-8fe2-1efe27212b8e.png">

## Actual behavior

If I take out the `title` and place it in a `Heading`, the elements inside the `Card` are squished together.

```javascript
<Layout.Section>
  <Card sectioned>
    <Heading>Header text</Heading>
    <TextStyle variation='subdued'>This is some text.</TextStyle>
  </Card>
</Layout.Section>
```

<img width="479" alt="screen shot 2018-02-13 at 5 31 24 pm" src="https://user-images.githubusercontent.com/3578574/36183897-776d34de-10e5-11e8-95c8-755a759f4499.png">

The reason I'm doing this is to add something to the right of the `title`/`Heading`.

```javascript
<Layout.Section>
  <Card sectioned>
    <Stack>
      <Stack.Item fill>
        <Heading>Header text</Heading>
      </Stack.Item>
      <Stack.Item>
        <Link>edit</Link>
      </Stack.Item>
    </Stack>
    <TextStyle variation='subdued'>This is some text.</TextStyle>
  </Card>
</Layout.Section>
```

<img width="465" alt="screen shot 2018-02-13 at 5 53 18 pm" src="https://user-images.githubusercontent.com/3578574/36184151-d3f933c8-10e6-11e8-9cb3-2c2d1178915d.png">

Is there any way to do this with the correct spacing?

## Specifications

- Polaris version: 1.10.2
- React version: 16.2.0
- Browser: Chrome latest
- Device: Desktop
- Operating System: macOS

**Comment by chloerice** [comment]
Hey @babenzele! You can accomplish this using the card component's existing props. 

For example, instead of using a stack

```jsx
<Layout.Section>
  <Card sectioned>
    <Stack>
      <Stack.Item fill>
        <Heading>Header text</Heading>
      </Stack.Item>
      <Stack.Item>
        <Link>edit</Link>
      </Stack.Item>
    </Stack>
    <TextStyle variation='subdued'>This is some text.</TextStyle>
  </Card>
</Layout.Section>
```

You can use the `title` and `actions` props

```jsx
<Layout sectioned>
  <Card sectioned title="Header text" actions={[{content: 'Edit', onAction: () => {}}]}>
    <TextStyle variation="subdued">This is some text.</TextStyle>
  </Card>
</Layout>
```

**Comment by babenzele** [comment]
Awesome! Thanks @chloerice. 

I missed that in the docs. I must have seen "action menu" and didn't think it applied.

**Comment by babenzele** [comment]
@chloerice Is there any way to make the Card action be a button?

**Comment by chloerice** [comment]
>@chloerice Is there any way to make the Card action be a button?

No, but you can make the action either a `primaryFooterAction` or `secondaryFooterAction` and they will be buttons below the card's content.

```jsx
<Layout sectioned>
  <Card
    sectioned 
    title="Header text"
    actions={[{content: 'Edit', onAction: () => {}}]}
    primaryFooterAction={{content: 'Edit', onAction: () => {}}}
    secondaryFooterAction={{content: 'Edit', onAction: () => {}}}
  >
    <TextStyle variation="subdued">This is some text.</TextStyle>
  </Card>
</Layout>
```

<img width="479" alt="screen shot 2018-02-15 at 11 38 23 am" src="https://user-images.githubusercontent.com/18447883/36277185-06344b52-1245-11e8-9011-747a33c03856.png">
