### ISSUE TITLE
Selectable Data Table Rows w/ Bulk Actions?

### ISSUE THREAD

**Issue by gil--** [Shopify/polaris#2738]
## Feature request summary

Came across this in the new App Ads UI. From what I tell this is not standard behavior but basically surfacing selected data tables w/ bulk actions similar to Resource List but for tabular data.

<img width="478" alt="Screen Shot 2020-02-12 at 8 38 38 PM" src="https://user-images.githubusercontent.com/3484527/74393349-d1b79c00-4dd7-11ea-86db-5c0f243718bb.png">

## Rationale

For data heavy information, a table is appropriate but we also may want to apply a bulk action on a number of the rows.---

**Comment by chaddjohnson** [comment]
`DataTable` components should have a `selectable` option whereby items have checkboxes and may be selected as in `ResourceList`. I am surprised this is a non-option, and I would hope Shopify did not intentionally omit this functionality. This functionality is present on the native Products page, for example, and so it is fair to ask that this be made available for developers, as well, via Polaris. There definitely are valid use cases where a shop owner would need to see stats in a list of selectable items (e.g., Products list showing number in stock, or net sales).

Can we please get this feature on the roadmap?

**Comment by chaddjohnson** [comment]
@BPScott @AndrewMusgrave @kaelig Shopify internally uses data tables with selectable and actionable rows. Why do the Polaris guidelines advise against this?

It would be helpful to know whether actionable DataTable is being considered as a roadmap item or if it will never happen.

A response would be appreciated.

**Comment by camelmasa** [comment]
They are creating an IndexTable component.
I hope it solves the problem.

Ref: https://github.com/Shopify/polaris-react/issues/390#issuecomment-669952565

**Comment by AndrewMusgrave** [comment]
Hi @chaddjohnson, sorry I missed your first ping. As @camelmasa mentioned we're creating a component to solve this need and add to Polaris. It's on our roadmap and something we're actively working on 😄

**Comment by chaddjohnson** [comment]
Fantastic news! Thank you for the responses. I am a happy camper now.

**Comment by itsniper** [comment]
Excellent! I'm working on my second app that could really use this component. Hopefully, it's available soon 🤞

**Comment by Alexzanderk** [comment]
Hi @AndrewMusgrave, do you have any updates on when this component `IndexTable` would be done?

**Comment by Alexzanderk** [comment]
@AndrewMusgrave hi, do you have any updates?

**Comment by EdwardGoomba** [comment]
@Alexzanderk `IndexTable` was just released a few days ago in `6.1.0`. You can use it.

**Comment by chaddjohnson** [comment]
The [component](https://polaris.shopify.com/components/lists-and-tables/index-table) looks great! Very nice work @AndrewMusgrave and @lhoffbeck! Thank you for getting this out there.
