### ISSUE TITLE
TextField cannot be edited

### ISSUE THREAD

**Issue by YourWishes** [Shopify/polaris#275]
# Issue summary

When using React (ES6+) a text field cannot be edited.

Issue seems to be caused by Polaris setting 'value' (even when the props don't have it set) on the TextField , which causes React to set it to be uneditable, should be "defaultValue" to allow editing.

You can also set "value={null}" on the props to fix the issue as well.

## Expected behavior

When using

    <TextField label="Test"  />

the expected function is a simple editable text field that has the label of "Test"

## Actual behavior

The TextField visually renders fine, however no input will work on the text field

## Steps to reproduce the problem

1. Using React, Webpack, Babel and Shopify Polaris 1.11.0
2. Create a simple element with a TextField
3. Compile and attempt to edit text field

## Specifications

- Polaris version: 1.110
- React version: 16.2.0
- Browser: Firefox 58.0.2
- Device: Microsoft Surface Pro
- Operating System: Windows 10

**Comment by buggy** [comment]
@YourWishes You need to maintain the state for your components. This is slightly different from input components in React which maintain their state internally. For example: You can add an `onChange` handler to `TextField` that stores the value in the state of the parent control then set `value` on `TextField` from the state of the parent control. A similar approach applies to Redux.

**Comment by chloerice** [comment]
Yes @YourWishes @buggy is right on the money. You need to add `onChange`--I know it's confusing that it isn't a required prop, but since the text field component can also be `readOnly` we have `onChange` as optional.
