### ISSUE TITLE
[Docs] Identify pain points and gaps while using layout components

### ISSUE THREAD

**Issue by chloerice** [Shopify/polaris#275]
To help draft v1 of the layout foundations documentation, use the components to build out a CodeSandbox demo of layouts from the Handshake homepage. Things to take note of:
- Pain points and confusion
- Differences between Polaris React and the foundations approach to building components that affect the way they're used (there's a paradigm shift)
- Commonly used atomic props
- Gaps in atomic props

**Comment by sarahill** [comment]
Closing this for now. We’ve written and shipped documentation in `shopify/polaris` repository readme files for the foundational layout components. We focused on publishing content for the [component api](https://github.com/Shopify/polaris/blob/main/packages/components/README.md) and current [design tokens](https://github.com/Shopify/polaris/blob/main/packages/tokens/README.md) to bring visibility to the current capabilities within the foundation.

We also started constructing a demo along with a [layout quick start guide](https://github.com/Shopify/polaris/pull/316).  We’ll pause the quick start guide for now. We believe we’ve got the right information surfaced for us to learn and reference as we move on to working with the Deliver and Operate teams in the coming cycles.
