### ISSUE TITLE
JavaScript error on Components page

### ISSUE THREAD

**Issue by meecrobe** [Shopify/polaris#281]
# Issue summary
JS error in card with header action preview.

## Expected behavior
Card with header action preview render on click.
<img width="920" alt="screen shot 2018-03-20 at 22 43 04" src="https://user-images.githubusercontent.com/8003440/37678825-39b045a2-2c90-11e8-8968-c2c8e5bc99a1.png">

## Actual behavior
JS error on the page. No preview.
<img width="1437" alt="screen shot 2018-03-20 at 22 44 34" src="https://user-images.githubusercontent.com/8003440/37678850-4b50f900-2c90-11e8-833c-e99820fe7a75.png">

**Comment by kaelig** [comment]
Thank you for using Polaris and for reporting this, a fix is on its way to the next patch.
