### ISSUE TITLE
The entire lodash is bundled when using polaris v2

### ISSUE THREAD

**Issue by KrasiNedew** [Shopify/polaris#283]
# Issue summary

Bad imports of lodash result in the entire library being bundled (~750kb)

The components doing that are DropZone, FileUpload and Provider/utils

If you can change those imports from
```javascript
import { get } from 'lodash'
```
to
```javascript
import get from 'lodash/get'
```
it would be awesome

## Expected behavior
Import only what you need from lodash

## Actual behavior
The entire lodash is bundled because of a few bad imports

## Steps to reproduce the problem

1. Install polaris 2.0.0-beta.12
2. Bundle it

## Specifications

- Polaris version: 2.0.0-beta.12
- React version: 16.2
---

**Comment by chloerice** [comment]
Thanks for raising this @KrasiNedew, adding to this to our internal project board right now!

**Comment by KrasiNedew** [comment]
Thank you :)

**Comment by dfmcphee** [comment]
The fix has been merged and will be released with the next beta. Thanks for bringing this up @KrasiNedew.
