### ISSUE TITLE
Handling actions in components with no onAction parameter

### ISSUE THREAD

**Issue by paulisloud** [Shopify/polaris#286]
# Issue Summary

I've got to imagine this is addressed somewhere but I can't located it after a substantial dig through the documentation: How we handle actions in the following sorts of React components?

* Page - primaryAction: There is no onAction / onClick parameter. How we trigger something to happen the 'content' (for example 'Save') is clicked?
* Cards with actions: Same - how do we handle the click? I'm using the HTML version currently where I can manually add an onClick action, but would like to use the cleaner React component

## Expected behavior

Would like for these components to have an onAction / onClick parameter

**Comment by dfmcphee** [comment]
Hey @paulisloud. We are still working on a better way to document and expose these options but the components you mentioned do take an `onAction` parameter. All of these actions extend this type and its properties: https://github.com/Shopify/polaris/blob/master/src/types.ts#L6

**Comment by paulisloud** [comment]
I did give onAction a try before submitting my issue just to see if it might be undocumented, but I get no result. Here is an example:

`

doSomething(e) {
    console.log('doing something', e);
  }
<Page
        icon='icon.png'
        breadcrumbs={[{ content: 'Settings' }]}
        primaryAction={{
          content: "Save",
          disabled: this.state.saveDisabled
        }}
        onAction={this.doSomething}
      >
`

As you might guess, the console.log never runs. Can expand code example out with the entire component if you like, but I think you get the idea.

**Comment by dfmcphee** [comment]
Ah sorry. The `onAction` should be passed to the object in `primaryAction` not on the `<Page>` itself.

```jsx
doSomething(e) {
  console.log('doing something', e);
}
<Page
  icon='icon.png'
  breadcrumbs={[{ content: 'Settings' }]}
  primaryAction={{
    content: "Save",
    disabled: this.state.saveDisabled,
    onAction={this.doSomething}
  }}
>
```

**Comment by paulisloud** [comment]
Ah, that makes sense. Works perfect, thanks.
