### ISSUE TITLE
The entire lodash is bundled in v2 (again)

### ISSUE THREAD

**Issue by KrasiNedew** [Shopify/polaris#289]
# Issue summary
The entire lodash is bundled because of a bad import in utilities/memoized-bind

I have a simple suggestion to avoid this in the future - running a bundle analyzer before a release
## Specifications

- Polaris version: 2.0.0-beta.13
- React version: 16.2.0

**Comment by dfmcphee** [comment]
Thanks again for catching this @KrasiNedew. We have been looking into ways to analyze the bundle in our CI process. This should be resolved in v2 beta 14 that was just released.
