### ISSUE TITLE
Spacing inconsistency in EmbeddedPage header with breadcrumbs

### ISSUE THREAD

**Issue by sutherland** [Shopify/polaris#293]
# Issue summary

For the `EmbeddedPage` component, there are spacing inconsistencies in the page header with breadcrumbs vs. without breadcrumbs. Noticeable when navigating between pages with/without breadcrumbs. I don't believe it's a configuration issue. Thanks!

![breadcrumbs](https://user-images.githubusercontent.com/56822/38505574-e1d64d8c-3bed-11e8-889d-75c85b106380.png)

## Expected behavior

Consistent spacing in the page header with breadcrumbs vs. without breadcrumbs.

## Actual behavior

Inconsistent spacing in the page header with breadcrumbs vs. without breadcrumbs.

## Steps to reproduce the problem

1. Configure `EmbeddedPage` components with/without breadcrumbs as documented
1. Notice the spacing inconsistencies in the page header with breadcrumbs vs. without breadcrumbs

## Specifications

- Polaris version: 1.13.1
- React version: 16.3.1
- Browser: Chrome
- Device: Desktop
- Operating System: macOS (10.13.4)

**Comment by nwtn** [comment]
At Shopify Unite, we announced some upcoming changes to the EASDK, along with the app title bar. Check out our [Platform Updates blog post](https://www.shopify.ca/partners/blog/platform-updates) under the “App identifier and navigation extension” heading. When these updates roll out later this summer, they should take care of the spacing issues you’re noticing.

Thank you for the report!
