### ISSUE TITLE
[OptionList] Extra empty LI/UL in sections.

### ISSUE THREAD

**Issue by kaelig** [Shopify/polaris#2955]
## Issue summary

In the "Option list with sections" example, an extra li>ul block is inserted.

Seen in https://5d559397bae39100201eedc1-hgctndungx.chromatic.com/?path=/story/all-components-option-list--option-list-with-sections

## Expected behavior

2 list items

![Screen Shot 2020-04-29 at 2 45 01 PM](https://user-images.githubusercontent.com/85783/80650077-1393ce00-8a28-11ea-86fd-42e51b3f05a9.png)

## Actual behavior

2 list items, preceded by 1 list item containing an empty `ul`

![Screen_Shot_2020-04-29_at_2_45_15_PM](https://user-images.githubusercontent.com/85783/80650154-4b9b1100-8a28-11ea-834f-4a243a282afc.png)

## Steps to reproduce the problem

1. Go to https://5d559397bae39100201eedc1-hgctndungx.chromatic.com/?path=/story/all-components-option-list--option-list-with-sections
1. Inspect the code

## Reduced test case

https://codesandbox.io/s/9runp?module=App.js

**Comment by jacquesporveau** [comment]
I am going to start working on this.

**Comment by kaelig** [comment]
Marking this as an accessibility issue as such markup can be misleading users on the number of items in a list when using assistive technologies.
