### ISSUE TITLE
Shopify Polaris component border hidden sometimes

### ISSUE THREAD

**Issue by akex0721** [Shopify/polaris#296]
Shopify Polaris component border hidden
![image](https://user-images.githubusercontent.com/30766060/38723587-268ccafc-3f34-11e8-9440-0e91cc9dc2cb.png)

**Comment by AndrewMusgrave** [comment]
@akex0721 Thanks for bringing this to our attention. Would you mind posting a code example so I can reproduce this?

**Comment by akex0721** [comment]
```
<Modal.Body margin>
          <div>
            <Select
              label='Hours'
              options={[
                {
                  label: '1 hour - $65',
                  value: 65
                },
                {
                  label: '2 hour - $130',
                  value: 130
                }
              ]}
              value='1 hour - $65'
            />
            <p style={{color: '#919EAB', fontSize: '12px', lineHeight: '16px', margin: '8px 0px 16px'}}>You will receive: ${48.75}</p>
          </div>
          <div>
            <Select
              label='Estimated turnaround time'
              options={[
                {
                  label: '1 day',
                  value: 1
                },
                {
                  label: '2 days',
                  value: 2
                }
              ]}
              placeholder='Choose number of days'
              value='1 day'
            />
          </div>
        </Modal.Body>
```

**Comment by akex0721** [comment]
@AndrewMusgrave

**Comment by AndrewMusgrave** [comment]
@akex0721 I can't seem to recreate this. If you wouldn't mind would I be able to get more information. For example: version of polaris, browser, platform, and browser zoom.

Is it possible that you've using another framework that may be overriding styles from polaris?

**Comment by AndrewMusgrave** [comment]
I still can't to reproduce this. Can you consistently reproduce this, possibly without the modal?

**Comment by chloerice** [comment]
Hi @eugene-zheng0208, have you tried upgrading to the latest stable version of Polaris (1.14.1)?

**Comment by ry5n** [comment]
Polaris version 2.x is out of beta and I’d encourage upgrading. If you still see the problem please re-open the issue. Thanks!

**Comment by brightraudona** [comment]
is there a solution?
