### ISSUE TITLE
Feature Request: Timeline Component

### ISSUE THREAD

**Issue by jordanskole** [Shopify/polaris#298]
# Feature request: Timeline Component

I would love to see a timeline component included in a future release of Polaris

## Expected behavior

I think this feature helps round out some of the existing components in the Shopify Admin UI, and is a necessary component to visualize;
*  a series of events that _already happened_ in a chronological order
* events _that are expected to happen_ in a chronological order. 

![image](https://user-images.githubusercontent.com/1438316/38841750-8beeb65c-41ab-11e8-8fd9-a017c2067666.png)

**Comment by ry5n** [comment]
We’ll eventually have a React implementation of this for the Shopify admin. It’s not on the immediate horizon for public release in Polaris, but I’m lookin into it now.

**Comment by ry5n** [comment]
For the moment this has been moved to our backlog. I’ll close this issue for now, since the timeline for public release isn’t known right now.

However, **we encourage everyone who wants this feature to add a 👍** to the original issue report. We’ll take your collective interest into account when we look at what to work on next.

**Comment by devchris** [comment]
It would be awesome to have this component! I might open a pull request to add it if no one is working on it. @ry5n

**Comment by whitehorse0324** [comment]
Hi @ry5n ,
When can I use timeline component through polaris?
According to status page, it's not considered yet.
Can you make it soon?

**Comment by chloerice** [comment]
Hi @whitehorse0324 👋thanks for checking in. Bringing the timeline component into the system is not on our roadmap at this time, but if that changes we will update this issue!

**Comment by ctrlaltdylan** [comment]
Also requesting that this component be available for partner use. It would be perfect for my app to communicate a timeline of events to an order on a details page.

**Comment by angeloocana** [comment]
Shopify Logistics needs to build a timeline for a project I'm working on right now. Would love to be able to use a timeline component from Polaris.

**Comment by Anyoks** [comment]
Also requesting this feature too!

**Comment by james-julius** [comment]
Wanting to bump this as I'll be using the Tailwind/Flowbite one in the meantime which won't be as nice as this integrated one. 

For anyone who needs a drop-in replacement, here it is:
https://flowbite.com/docs/components/timeline/

**Comment by huykon** [comment]
do we have any polaris component for timeline at this moment?

**Comment by johnmcguin** [comment]
I would love this feature as well!

**Comment by TemurbekRuziyev** [comment]
Hello
Why is this request closed? 
As Shopify promotes to use Polaris to use this library, it would be great if the timeline component is publicly available

**Comment by remy727** [comment]
@TemurbekRuziyev, I recommend using this:
https://www.polariscomponents.com/components/timeline
