### ISSUE TITLE
DataTable sorting inconsistent styling for 'text' headings

### ISSUE THREAD

**Issue by FelixTellmann** [Shopify/polaris#300]
# Issue summary

DataTable headings with columnContentTypes='text' align right when sorting is enabled

## Expected behavior

Headings align left/right based on columnContentTypes regardless of sorting functionality. Sorting downArrow icon should be on the right for text items.

## Specifications
Polaris version: 2.0.0-beta.17
React version: 16.3.1

**Comment by chloerice** [comment]
Thanks for raising catching this alignment bug @FelixTellmann! Adding to our issue tracker now.

**Comment by chloerice** [comment]
@FelixTellmann we've just released a new patch with a fix 😁
