### ISSUE TITLE
Inifinite Scroll on Resource List

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/polaris#3000]
I am pretty sure I am missing something here, but there does not seem to be any support in Polaris for Infinite Scroll? Only paging seems to have some support. Clearly this seems to be at odds with use of GraphQL as it supports infinite scroll nicely, but not paging. So if we wanted to offer Infinite Scroll on a Resource List, we have to wrap the Resource List ourselves I suppose. 

Does anyone have a Gist or CodeSandbox of Polaris Resource List working with an Infinite Scroll?

**Comment by dfmcphee** [comment]
Hey @resistorsoftware. You are correct, the resource list doesn't support this out of the box at the moment. I do agree that this is something we should look at handling automatically in the component in the future. For now I put together a little example sandbox with a custom implementation wrapping the resource list: https://codesandbox.io/s/polaris-infinite-scroll-example-7sr06

**Comment by resistorsoftware** [comment]
God-like!

So amazing. As as struggle and bump into all the gotchas of React, and I look back on how I did it and it was JARRING, and how you did it and it was smooth, certainly paved the way for me to learn from you! Cannot say much other than THANK YOU !!!!!

**Comment by benkraus** [comment]
Came across this a few years later, needed the same. Updated the example above for Polaris 12: https://codesandbox.io/s/polaris-infinite-scroll-example-forked-cdmxhz

**Comment by resistorsoftware** [comment]
@benkraus Amazing! Awesome! Thank you so much for that. I am sure many will benefit.

**Comment by snipert1549** [comment]
Hi @benkraus 
Could you please refresh your link ? I do not know hwy but when I try open it it's says that Sandbox not founded

**Comment by resistorsoftware** [comment]
Agreed! It is one thing to push code to the cloud and then quite another to make it disappear!
