### ISSUE TITLE
Multiple locales example from the "Using translations" section missing information

### ISSUE THREAD

**Issue by petetnt** [Shopify/polaris#3016]
## Issue summary

In the section describes multiple locales as such:

> If a project supports multiple locales, then load them dynamically using @shopify/react-i18n. This ensures that you load only the translations you need.
> ```js
> import AppProvider from '@shopify/polaris';
> // en.json is English. Replace with fr.json for French, etc
> import translations from '@shopify/polaris/locales/en.json';
> import {useI18n} from '@shopify/react-i18n';
> function App() {
>  const [i18n] = useI18n({
>     id: 'Polaris',
>      fallback: translations,
>     translations(locale) {
>       return import(
>         /* webpackChunkName: "Polaris-i18n", webpackMode: "lazy-once" */ `@shopify/polaris/locales/${locale}.json`
>       ).then((dictionary) => dictionary && dictionary.default);
>      },
>    });
>
>    // i18n.translations is an array of translation dictionaries, where the first
>    // dictionary is the desired language, and the second is the fallback.
>    // AppProvider however expects that the first dictionary is the fallback
>    // and the second is the desired language. Thus we need to reverse the array
>    // to ensure the dictionaries are in the order desired by AppProvider.
>    // The slice is to ensure we don't manipulate the original translations array
>    // as reverse() modifies the array in-place.
>    return (
>   <AppProvider i18n={i18n.translations.slice().reverse()}>
>        {/* App content */}
>   </AppProvider>
>    );
>  }
> ```

This seems to be missing tons of formation, for example that to use `@shopify/react-i18n` you need to wrap the whole thing to another provider (I18nContext.Provider) and pass a `I18nManager` instance to it. The sections is are also missing concrete examples how to use the i18n-library (eg. import hook, run i18n.translate('Polaris.Save'))

## Expected behavior

Translations work

## Actual behavior

`Missing I18nManager` error

## Steps to reproduce the problem

1. Follow the guidance in  https://polaris.shopify.com/components/structure/app-provider

## Reduced test case

Sorry, no test case for now as it pretty much needs full app setup...

## Specifications

```bash
  System:
    OS: macOS Mojave 10.14
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 48.79 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 74.0
    Safari: 12.0
  npmPackages:
    @shopify/polaris: ^4.21.0 => 4.21.0
    react: 16.13.1 => 16.13.1
    react-dom: 16.13.1 => 16.13.1
```

**Comment by petetnt** [comment]
Similarly the issue fights against the requirement of "AppProvider should be the topmost provider" but I guess adding the appbridge one before that violates that one too.

**Comment by mubbo** [comment]
@petetnt  you don't happen to have a working example do you? I've run into the same problem that the documentation for this is horrible.

Cheers

**Comment by petetnt** [comment]
My `_app.tsx` looks like this if it helps:

```
import React from 'react';
import App from 'next/app';
import Head from 'next/head';
import { Provider } from '@shopify/app-bridge-react';
import { AppProvider } from '@shopify/polaris';
import '@shopify/polaris/styles.css';
import shopifyTranslations from '@shopify/polaris/locales/en.json';
import { I18nContext, I18nManager, useI18n } from '@shopify/react-i18n';
import Cookies from 'js-cookie';
import { createClient, Provider as GraphQLProvider } from 'urql';

const client = createClient({
  url: `${process.env.PUBLIC_URL}/graphql`,
});

const config = {
  apiKey: process.env.API_KEY,
  shopOrigin: Cookies.get('shopOrigin'),
  forceRedirect: true,
};

const Providers = ({ children }): JSX.Element => {
  const [i18n] = useI18n({
    fallback: shopifyTranslations,
    async translations(locale) {
      const dictionary = await import(
        /* webpackChunkName: "Polaris-i18n", webpackMode: "lazy-once" */ `@shopify/polaris/locales/${locale}.json`
      );

      return dictionary.default;
    },
  });

  return (
    <Provider config={config}>
      <AppProvider i18n={i18n.translations.slice().reverse()}>
        <GraphQLProvider value={client}>{children}</GraphQLProvider>
      </AppProvider>
    </Provider>
  );
};

class Foo extends App {
  render(): JSX.Element {
    const { Component, pageProps } = this.props;
    const locale = 'en';
    const i18nManager = new I18nManager({
      locale,
      onError(err): void {
        // eslint-disable-next-line
        console.error(err.message);
      },
    });

    return (
      <>
        <Head>
          <title>Foo</title>
          <meta charSet="utf-8" />
        </Head>
        <I18nContext.Provider value={i18nManager}>
          <Providers>
            <Component {...pageProps} />
          </Providers>
        </I18nContext.Provider>
      </>
    );
  }
}

export default Foo;
```

**Comment by JumBay** [comment]
+1

**Comment by petetnt** [comment]
It's still broken, but see https://github.com/Shopify/polaris/issues/3016#issuecomment-774934958 if you need to deal with it

**Comment by daviareias** [comment]
It's 2024 and there's 0 documentation about the need to use I18nManager

**Comment by trenkwill** [comment]
> It's 2024 and there's 0 documentation about the need to use I18nManager

I agree, finding relevant information on how to use i18n, getting the locale, setting it up in a Remix Shopify app is difficult.

**Comment by ascheucher-shopify-partner** [comment]
Just in case anybody stumbles over this, @shopify/react-i18n is deprecated now.

The suggesetion in the Shopify Developer Community was to use https://www.npmjs.com/package/react-i18next
