### ISSUE TITLE
Not able to render any elements inside the body of the Embedded Modal Component

### ISSUE THREAD

**Issue by johnnunns** [Shopify/polaris#304]
Using the modal from the embedded sdk. I see the options you've given, but no where do I see the ability to render any custom elements inside of the modal to account for the body of the modal. Is this on purpose?

## Expected behavior
<Modal title="Test" primaryAction= () => foo >
  <p>This should be the body</p>
</Modal>

## Actual behavior

Body remains empty. The only way I've found to actually render any content is to bring it in through an external source. I'm not sure the reasoning for this. What are my options?

## Specifications

- Polaris version: 1.8.3
- React version: 16
- Browser: Chrome
- Device: Mac

---

**Comment by chloerice** [comment]
Hi @johnnunns, embedded modals can only be rendered with the content provided [via the required `src` prop specified](https://polaris-v2.shopify.com/components/embedded/embedded-modal). 

```jsx
<Modal
  src="https://my-app.com/upgrade-to-retail-package"
  open={this.state.open}
  title="Upgrade your Shopify POS with the Retail Package"
  primaryAction={{
    content: 'Add Retail Package',
    onAction: () => this.setState({open: false}),
  }}
  secondaryActions={[{
    content: 'Cancel',
    onAction: () => this.setState({open: false}),
  }]}
  onClose={() => this.setState({open: false})}
/>
```

**Comment by johnnunns** [comment]
This seems like a complicated answer to a problem that's solved with the creation of a react component built in polaris. Is there any talk of creating this?
