### ISSUE TITLE
Feature Request: Allow disabling a tab on conditional basis

### ISSUE THREAD

**Issue by Cma-Rawal** [Shopify/polaris#305]
# Issue summary
Tabs should be allowed to be disabled on conditional basis

<Tabs
          tabs={tabs}
          selected={selected}
          onSelect={this.handleTabChange}
        />

if a property like "disabled={condition}" could be added.

⚓️ We’re not accepting pull requests at this time<br />
🗒 This repo is for reporting issues and feature requests only

**Comment by ry5n** [comment]
Thanks for the request, @Cma-Rawal. We’re not actively working on this right now, but we treat all feature requests as part of our backlog. I’m going to close this issue, but I we encourage everyone who’s interested to add a 👍 to the original issue report. We’ll take your collective interest into account when we look at what to work on next.

Thanks again!
