### ISSUE TITLE
Date Picker focus issue

### ISSUE THREAD

**Issue by meecrobe** [Shopify/polaris#313]
# Issue summary

If Date Picker component has selected date or range or is focused and located out of the iframe's viewport, after triggering change event on any input element on the page, that element loses it's focus, viewport jumps back to Date Picker component and focuses it.

## Expected behavior

Trigger change event on any other element without losing it's focus.

## Steps to reproduce the problem

1. Choose date or date range with Date Picker.
1. Scroll the page as the Date Picker will be outside the page.
1. Trigger change event on any input element.

![screencast 2018-05-07 19-09-36](https://user-images.githubusercontent.com/8003440/39712072-60d268d0-522a-11e8-88bc-8209320cda2c.png)

**Comment by ry5n** [comment]
Thanks for reporting this @meecrobe. I’ve created an issue on our internal issue tracker; we’re looking into it.

**Comment by BarryCarlyon** [comment]
I also have just discovered this issue.

But

1. Choose date or date range with Date Picker.
1. Trigger change event on any input element.

It does it even if the date picker is in frame or put of frame, a datepicker just needs to be "open"

**Comment by ry5n** [comment]
A few hours ago we released [version 2.1.2](https://github.com/Shopify/polaris/releases/tag/v2.1.2) which fixes this issue 🎉
