### ISSUE TITLE
Drop zone documentation missing instructions on uploading files to a server

### ISSUE THREAD

**Issue by chrismanderson** [Shopify/polaris#314]
# Issue summary

The documentation for the new (and awesome!) Drop zone component does not contain any instructions on how to actually upload the image to a server. (https://polaris.shopify.com/components/actions/drop-zone)

## Expected behavior

I would expect an example of the actual upload of a file to be present on the documentation page. There are mentions of "server-side upload error messages" in terms of the content guidelines, but again, no mention of how to process the upload itself.

It's probably reasonable to expect the Polaris consumer to implement the uploading step themselves, as it could vary wildly from use-case to use-case. But, it does feel to me that a component concerned with file uploading should provide documentation that provides the complete functionality, rather than just the upload itself.

**Comment by ry5n** [comment]
Thanks for bringing this up @chrismanderson. Polaris is focused on the UI layer, and doesn’t try to implement any business logic (including sending or receiving data). We’re not planning to expand the scope of the library itself, but we know it’s important to give some guidance like you say.

We are planning to address this in some form, such as additional documentation, example apps, or something else. I can‘t promise a particular timeline right now.

**Comment by chrismanderson** [comment]
I think an example app down the road would be a great idea. Cheers!

**Comment by dani-sanomads** [comment]
@ry5n Can you share any details on that. Thanks.

**Comment by Chadyka** [comment]
@ry5n  It would be great if you could share an example here for this business logic or provide a polaris file upload UI component that simply opens the shopify admin files tab in a modal which could return the selected file after upload or handle multiple file selections as an Array. This way they would be uploaded to the store as a file and the form could update metaobjects that have a file value as an id.
