### ISSUE TITLE
Modal > `onScrolledToBottom` broken in some screen resolutions

### ISSUE THREAD

**Issue by ben10code** [Shopify/polaris#3225]
## Issue summary

While working in `shopify/web`, I've noticed that the `onScrolledToBottom` in `Modal` does not work in some screen sizes. 

Moreover, I think it is good to note that I have a 1440p monitor. It works fine in all screen sizes for my coworker with a 1080p monitor.

Here is a little video showing the issue. 

- First try: 1953 px x 1050px. Works ✅ 
- Second try: 2059px x 1083 px. Works ✅ 
- Third try: 2097px x 1108px. ❌ 
- Fourth try (not in the video): 2097 px x 997 px ❌ 

https://drive.google.com/file/d/1928qia8wK4v5enksp5b869Vvjr5a3Jmi/view?usp=sharing

## Expected behavior

`onScrolledToBottom` should be triggered in all resolutions when the bottom of the modal is reached.

## Actual behavior

`onScrolledToBottom` is not triggered in all resolutions. 

## Steps to reproduce the problem

https://drive.google.com/file/d/1928qia8wK4v5enksp5b869Vvjr5a3Jmi/view?usp=sharing

## Reduced test case

Unfortunately, I am unable to reproduce this issue in a sandbox with just a modal. It works just fine. However, when I copy the code from the sandbox into web, it doesn't work (in web). 

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 5.2.1
- Browser: Version 85.0.4183.83 (Official Build) (64-bit)
- Device: MacBook Pro (15-inch, 2019)
- Operating System: macOS Catalina V10.15.3

**Comment by arthurgouveia** [comment]
👍 Also able to reproduce this locally

**Comment by rorz** [comment]
Also confirming reprod on this!

**Comment by alex-page** [comment]
Please re-open if it is still a problem
