### ISSUE TITLE
DatePicker selecting a date submits the form

### ISSUE THREAD

**Issue by BarryCarlyon** [Shopify/polaris#323]
# Issue summary

Selecting items on the datepicker submits the form.

This occurs in with allowRange true/false and/or multiMonth true/false

    <Form onSubmit={this.handleSubmit}>
        {otherfieds}
        <DatePicker
            month={this.state.month}
            year={this.state.year}
            onChange={this.handleDatePickerChange}
            onMonthChange={this.handleDatePickerMonthChange}
            selected={this.state.selected}
            allowRange={false}
            multiMonth={false}
        />

        <Button
            submit
            primary
            loading={this.state.loading}
            icon="save"
            disabled={this.state.allowSubmit ? false : true}
            >Submit</Button>
    </Form>

## Expected behavior

Picking a date or a date range selects the date or date range only

## Actual behavior

A date or date range is selected, **and** the form is submitted.

## Steps to reproduce the problem

1. Select a date on the date picker
1. Cry as your Form is submitted

## Specifications

- Polaris version: 2.0.0
- React version: 16.3.2
- Browser: Chrome
- Device: Desktop
- Operating System: mac OSX

**Comment by danrosenthal** [comment]
Thanks for logging this issue @BarryCarlyon! I've logged it in our internal repo and will close this in favor of the internal issue.
