### ISSUE TITLE
Embeded app SDK integration

### ISSUE THREAD

**Issue by Mwerdean** [Shopify/polaris#328]
# Issue summary

Apologize in advance for the newbie question.
I've created an example app to use on a test Shopify store and i'm having problems embedding the app into the admin page. On my Shopify Partners page I've created a new app and provided the apiKey along with my test shop origin url in the AppProvider tag.  From here I'm not sure where to go from here. I've checked my shopify account for an app requesting to be installed but nothing shows. Do I need to use a SSL tunnel using ngrok and set up a server? Right now the url in my Shopify Partners is localhost:3000. If somebody could give some direction it would be greatly appreciated.

I used this video guide to create the app:
https://www.youtube.com/watch?v=6hiGCw-dY9M
And this web page for guidance:
https://polaris.shopify.com/components/get-started#using-embedded-components

⚓️ We’re not accepting pull requests at this time<br />
🗒 This repo is for reporting issues and feature requests only

**Comment by BarryCarlyon** [comment]
Yeah without SSL it just won't load (should get a suitable error in chrome inspector or similar about mixed content)

ngrok is a valid way round this issue, or setting up a server and use a free SSL cert from letsencrypt

**Comment by ry5n** [comment]
Thanks for the question @Mwerdean. It’s great to hear you’re getting started building an app with Shopify. 

[This video from developers.shopify.com](https://fast.wistia.net/embed/iframe/bk7v4jfqyc?popover=true) is probably a good place to start. 

There are a couple of other tutorials that might be helpful:
- [Building a public Shopify application](https://help.shopify.com/api/tutorials/building-public-app)
- [Building a Shopify application with Node.js and Express](https://help.shopify.com/api/tutorials/building-node-app)
