### ISSUE TITLE
Resource List: Missing padding

### ISSUE THREAD

**Issue by BarryCarlyon** [Shopify/polaris#330]
# Issue summary

https://polaris.shopify.com/components/lists-and-tables/resource-list#navigation

- Set to `Resource List with Filtering`
- Hit x on "Account status is Account enabled"

## Expected behavior

![image](https://user-images.githubusercontent.com/20999/40489749-be8611b8-5f61-11e8-9450-56ae02d60248.png)

## Actual behavior

From the docs

![image](https://user-images.githubusercontent.com/20999/40489702-9dd7017a-5f61-11e8-825d-769dc751f008.png)

The lack of vertical padding between the search field and the first entry in the Resource List

Live example (non docs):

![image](https://user-images.githubusercontent.com/20999/40489807-e29fc864-5f61-11e8-8e9b-1c8331a1222a.png)

## Steps to reproduce the problem

See issue summary

## Specifications

- Polaris version: The Documentation version and Polaris 2.0.0
- React version: 16.x
- Browser: Chrome
- Device: Desktop
- Operating System: mac

**Comment by ry5n** [comment]
Thanks for catching this. It looks like a bug with the component; I’ll open an issue and we’ll get it fixed in a future version, as soon as we can.

**Comment by ry5n** [comment]
We’ve found the issue the fix will be available in the next release.
