### ISSUE TITLE
[new DL][Banner in a card] Close button is misaligned and can overlap text

### ISSUE THREAD

**Issue by kaelig** [Shopify/polaris#3307]
## Issue summary

Close button is misaligned and can overlap text.

## Expected behavior

![Screen_Shot_2020-09-23_at_3_07_27_PM](https://user-images.githubusercontent.com/85783/94074893-000a4a80-fdaf-11ea-9a35-0cdc3896595e.png)

## Actual behavior

![Screen_Shot_2020-09-23_at_3_07_43_PM](https://user-images.githubusercontent.com/85783/94076407-d69eee00-fdb1-11ea-9156-7c6d7b56f591.png)

## Steps to reproduce the problem

Go to http://polaris-react.herokuapp.com/?path=/story/all-components-banner--banner-in-a-card, compare the old to the new design language.

**Comment by alex-page** [comment]
This is resolved!
