### ISSUE TITLE
Proper syntax for adding more than one item to breadcrumb in embedded app?

### ISSUE THREAD

**Issue by paulisloud** [Shopify/polaris#331]
Currently, using the breadcrumb in an embedded app like so:

breadcrumbs={[{ content: 'Customers', url: '/customers' }, { content: 'Customer Profile', url: `/customers/${customerId}` }]}

Renders only:
App Name / Customer Profile

Note that the ' / Customers / ' section you might expect is not there. Is this a syntax issue or am I misunderstanding what to expect from the breadcrumb property of the Page component?

## Expected behavior

A declaration of:

`breadcrumbs={[{ content: 'Customers', url: '/customers' }, { content: 'Customer Profile', url: `/customers/${customerId}` }]}`

Would render:

App Name / Customers / Customer Profile, and clicking on "Customers" would take the person back to the parent page. But given that the app doesn't have SSR, and navigation is handled through a redux .push(), I'm not sure how to invoke an action here.

## Actual behavior

App Name / Customer Profile, where clicking on customer profile takes you to /customers/the_id in the Shopify admin, vs in my app.

## Steps to reproduce the problem

1. Create a Page component in an embedded app
2. Add the code above to the component for the breadcrumb

## Specifications

- Polaris version: 2.0.0
- React version: 16.2

---

**Comment by paulisloud** [comment]
Anything on this?

**Comment by dfmcphee** [comment]
Hey @paulisloud. Thanks for reaching out. Unfortunately this is a limitation of the EASDK. It only accepts one level of breadcrumb.

https://help.shopify.com/api/embedded-apps/embedded-app-sdk/methods#shopifyapp-bar-initialize-config

**Comment by paulisloud** [comment]
Too bad. Any hope of a feature request on this?

Could you provide any examples of navigation patterns typically used in embedded apps leveraging Polaris?

**Comment by tmlayton** [comment]
I don‘t suspect this is something we will support – specifically multiple breadcrumbs. Shopify admin at one time had multiple levels of breadcrumbs and we decided to move away from this pattern.

Although we do recognize that app navigation is a pain point and is something we are currently working on solving with the EASDK.

As for examples of app navigation patterns using Polaris, a popular pattern is navigation using [tabs](https://polaris.shopify.com/components/navigation/tabs) (e.g. [teelaunch](https://apps.shopify.com/teelaunch-1)). We are exploring this pattern being supported by the EASDK.

**Comment by paulisloud** [comment]
Glad to know it's in progress. Any rough idea on a beta ETA?

**Comment by tmlayton** [comment]
As a rough idea I would expect in the next couple months we will have some part of this shipped.

**Comment by paulcanning** [comment]
Any update on this?

**Comment by paulcanning** [comment]
Still no news on this, after 8 months?

**Comment by adipasquale** [comment]
up 👍 navigation is really tricky with Embedded Apps
