### ISSUE TITLE
Customize header for ResourceList

### ISSUE THREAD

**Issue by jstoeffler** [Shopify/polaris#332]
# Issue summary

I think it would be interesting to allow to customize entirely the ResourceList's Header, with a renderHeader() function for example.  Or at least what is displayed at `itemCountTextMarkup`.

## Expected behavior

I am trying to reproduce Shopify's Collection Product List, where you can add items to a list:

![Shopify's Product Collection List](https://i.imgur.com/kMGoVJV.png)

## Actual behavior

Not possible to customize anything except adding some specific components.

## Steps to reproduce the problem

- Try to add custom header.

## Specifications

- Polaris version: 2.0.0
- React version: 16.3.1
- Browser: Chrome 66.0.3359.181
- Device: MacBook air
- Operating System: Mac OS High Sierra

**Comment by dleroux** [comment]
@jstoeffler thank you for requesting this feature. I will close this issue for now and mark-it as a `feature request` so we can keep track of it. Feel free to give it a 👍 as it will help us prioritize future development.

**Comment by jstoeffler** [comment]
Thanks!
