### ISSUE TITLE
Loading spinner doesn't appear in ResourceList when Searching through filters onQueryChange

### ISSUE THREAD

**Issue by junaidatique** [Shopify/polaris#3329]
## Issue summary
I am using `Filters` with `ResourceList` component. When I search through `onQueryChange` and while making the API request, I enable `loading` state of `ResourceList`. The component adds `padding-top` which hides the loading spinner. 

So here are the steps to reproduce this

- `ResourceList` component is loaded with `filterControl` attached with some data
- Enter some text in `queryValue` of `Filters` and enabling loading state of `ResourceList`
- Loading spinner will appear. Try to write something where results is empty
- now remove the search filter text and you can see that loading spinner will not appear.
- It will only appear if there is only one record after searching. 

## Expected behavior
it should show loading spinner everytime when every the loading attribute is marked true..

the [function](https://github.com/Shopify/polaris-react/blob/38457e8742ec2032cf1226b60d808522f6a9b5ad/src/components/ResourceList/ResourceList.tsx#L353) that calculates the loading position doesn't account the height of the resource list component. It calculates based on the screen size I guess. 

## Actual behavior
loading spinner hides if 

## Steps to reproduce the problem
already mentioned above.

**Comment by jaret32** [comment]
I am seeing this same issue on the latest version.

**Comment by alex-page** [comment]
@junaidatique are you interested in making a PR for this issue? Are you able to add a screen recording or a codesandbox to help us replicate it?

**Comment by SeanyB** [comment]
Due to staleness we will close this issue for now. Please feel free to re-open it with perhaps a codesandbox link for reproduction if you still have this issue.
