### ISSUE TITLE
Add default print styles for Cards

### ISSUE THREAD

**Issue by gcornhill** [Shopify/polaris#3332]
## Feature request summary
Add in general print styles for cards.

## Rationale
Working on the new Order Details port project, we realized the cards add a lot of spacing for print, resulting in increased page count and more pages having to be printed by merchants.

It would be nice if cards when printed had reduced padding, borders, font sizes, etc.
Also something to consider is how they stack for printing, for Order Details we wanted to remove space between stacked Cards.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by tarynmusgrave** [comment]
This is part of this request https://github.com/Shopify/polaris-react/pull/3537

**Comment by alex-page** [comment]
Hey @gcornhill is this still an issue?

**Comment by gcornhill** [comment]
Yes! Still really brittle css code in orders to handle printing...

**Comment by dominikwilkowski** [comment]
Hey @gcornhill, As part of our layout work coming up we will look into this issue and see if we can also address this.

**Comment by gcornhill** [comment]
Amazing! I'm so embarrassed by the selectors we had to use 2 years ago.... Lol.
