### ISSUE TITLE
Tooltip:: active property is not working

### ISSUE THREAD

**Issue by pbarrios** [Shopify/polaris#335]
# Issue summary

The tooltip is always being shown, no matter of the active property. The example in the [docs](https://polaris.shopify.com/components/overlays/tooltip) is also failing

## Expected behavior

The tooltip is not visible when the active property  is `false`.

## Actual behavior

The tooltip is always visible, no matter of the active property.

## Steps to reproduce the problem

Same as described here: https://polaris.shopify.com/components/overlays/tooltip

## Specifications

- Polaris version: 2.0.0
- React version: 16.2.0
- Browser: Chrome  66.0.3359.181
- Device: PC Desktop
- Operating System: WIN 10

---

**Comment by solonaarmstrong** [comment]
Thank you for bringing this up.

**Comment by tmlayton** [comment]
@pbarrios this is fixed and released in 2.6.0, thanks again for the issue!
