### ISSUE TITLE
Remove badge, icon, image, .. props from ActionList item component

### ISSUE THREAD

**Issue by tleunen** [Shopify/polaris#3350]
## ActionList.Item

Following this PR to add a [`suffix`](https://github.com/Shopify/polaris-react/pull/3216), and this one for a[ `prefix`](https://github.com/Shopify/polaris-react/pull/3313), a few props become "useless" inside the Action List item component.

`prefix` and `suffix` offer more flexibility to consumers, therefore, these props can be remove: `badge`, `icon`, `image`.

Moreover, by making `content` more flexible as well (taking a React Node instead of a string), we could also simplify the component and remove `ellipsis`, because ellipsis should be done automatically when the content is too large, via `<Truncate>` for example.

**Comment by RickyMarou** [comment]
Would be nice to also update [the documentation](https://polaris.shopify.com/components/action-list) to remove all usage of `icon` and other deprecated props on the component
