### ISSUE TITLE
[Textfield] Show character count only when the input is focused

### ISSUE THREAD

**Issue by tleunen** [Shopify/polaris#3363]
## Feature request summary

The textfield has a way to show a character count. But the count is always rendered. We would like the option to show the count only when the input is focused

Something along these lines maybe?
```jsx
    <TextField
      {...}
      showCharacterCountOnFocus
    />
```

**Comment by dominikwilkowski** [comment]
Hey @tleunen,
Thank you for waiting ages for us to get back to you 😄 

I think the best way for you and anyone else who happens to stumble upon this issue later, to use the `showCharacterCount` prop to enable and disable the character counter with your own logic.
So for your specific case on `blur` you set `showCharacterCount={false}` and on `focus` you set it to `showCharacterCount={true}`.
That way we can avoid adding another prop but still allow you to do what you need to do.

I'm closing this issue for now but do let me know if there is a case I haven't thought about.
