### ISSUE TITLE
ResourceItem does not reflect state changes when selectedItems property is passed to ResourceList

### ISSUE THREAD

**Issue by haseebanwar** [Shopify/polaris#3366]
## Issue summary
Hi,
 
I noticed that ResourceItem does not reflect state changes when `selectedItems` property is passed to ResourceList. If `selectedItems` property is not given to the ResourceList component then ResourceItem works fine.

## Expected behavior
When something updates in state, ResourceItem should reflect that change. State variables in ResourceItem should update like this:

![without-selectedItems](https://user-images.githubusercontent.com/45782139/94941205-00f95580-04ee-11eb-80fc-accffa4e874b.gif)

## Actual behavior
Actual Behavior of ResourceItem with `selectedItems` passed to ResourceList. Reference the code snippet below:

![with-selectedItems](https://user-images.githubusercontent.com/45782139/94941210-035baf80-04ee-11eb-98ec-e480a46e8c4e.gif)

## Reduced test case

```
import React, { useState } from 'react';
import {
  Card,
  ResourceItem,
  ResourceList,
  Avatar,
  TextStyle,
  Button,
} from '@shopify/polaris';

const Test = (props) => {
  const [state, setState] = useState(12);

  return (
    <Card>
      <Button onClick={setState.bind(null, Math.random())}>Do Something</Button>
      <ResourceList
        resourceName={{ singular: 'customer', plural: 'customers' }}
        items={[
          {
            id: 341,
            name: 'Mae Jemison',
          },
          {
            id: 256,
            name: 'Ellen Ochoa',
          },
        ]}
        renderItem={(customer) => {
          const { id, name } = customer;
          const media = <Avatar customer size="medium" name={name} />;

          return (
            <ResourceItem
              id={id}
              media={media}
              accessibilityLabel={`View details for ${name}`}
            >
              <h3>
                <TextStyle variation="strong">{name}</TextStyle>
                {/* Printing state value here */}
                <p>{state}</p>
              </h3>
            </ResourceItem>
          );
        }}
        selectedItems={[341]}
      />
    </Card>
  );
};

export default Test;

```

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: latest
- Browser: Chrome
- Device: PC
- Operating System: Windows 10

**Comment by meecrobe** [comment]
A year has passed since https://github.com/Shopify/polaris-react/issues/2357... 😉  
Update the `key` prop on the `ResourceItem`.

[Sandbox](https://codesandbox.io/s/cranky-sun-oohsx?file=/src/App.js)
