### ISSUE TITLE
TextField could have a prop to indicate a label it should use

### ISSUE THREAD

**Issue by arthurgouveia** [Shopify/polaris#3398]
## Feature request summary

I'd like to propose the addition of another prop `labelId` that is mutually exclusive with `label`, so that if we do provide an id, `TextField` renders only the input.

## Rationale

Given different design applications, we might end up having a specific need where the labels are not stacked on top of their inputs, and even if Polaris allowed an `inline` prop, depending on the design, still it wouldn't really solve the issue of double labelling an input.

Here's the current design application for Email Editor:
<img width="1574" alt="Screen-Shot-2020-10-06-13-57-38 43" src="https://user-images.githubusercontent.com/642737/95338668-2d5ff980-0881-11eb-807b-cf26d491a16d.png">

While one may say that having the labels on the side be `aria-hidden` and adding a click handler to focus the desired input, it solves the issue on a very inelegant way and throws away a bunch of semantics. In our case, assuming `TextField` had an `inline` prop, still it wouldn't work since the labels need to match the width of the largest one.

We've had a [conversation on Slack](https://shopify.slack.com/archives/CQK6FNLJK/p1602006810225400) about this that is quite relevant about this feature request.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by mzlock** [comment]
I'd like to second this proposition/request. I have a use case for a `<table>` with repeating fields in rows. Per a recommendation from WebAIM, I'd like to use the table column `<th>` as the fields' label via `aria-labelledBy`.

WebAIM recommendation: https://webaim.org/techniques/forms/advanced#multiple

My table of fields design from Figma:
<img width="587" alt="Screen Shot 2021-04-07 at 2 27 43 PM" src="https://user-images.githubusercontent.com/1087001/113926978-df3d9b80-97ba-11eb-8693-67544b9cc278.png">

---

🤔  Thinking on it a little, I think the `label` prop _should still be required_ as a fall-back. If ARIA is working properly, then the `aria-labelledby` would be read _instead of_ the given `<label>`.  I never like to rely on ARIA alone, personally, and having both should work well; it might just be a little annoying for devs.

Alternative to adding a new `labelId` prop, the `<TextField>` component could be updated to accept `aria-labelledby` as a valid attribute or `ariaLabelledby` as a new prop, which would override the current usage of `aria-labelledby` on the component.

**Comment by mzlock** [comment]
I'd like to second this proposition/request. I have a use case for a `<table>` with repeating fields in rows. Per a recommendation from WebAIM, I'd like to use the table column `<th>` as the fields' label via `aria-labelledBy`.

WebAIM recommendation: https://webaim.org/techniques/forms/advanced#multiple

---

🤔  Thinking on it a little, I think the `label` prop _should still be required_ as a fall-back. If ARIA is working properly, then the `aria-labelledby` would be read _instead of_ the given `<label>`.  I never like to rely on ARIA alone, personally, and having both should work well; it might just be a little annoying for devs.

Alternative to adding a new `labelId` prop, the `<TextField>` component could be updated to accept `aria-labelledby` as a valid attribute or `ariaLabelledby` as a new prop, which would override the current usage of `aria-labelledby` on the component.

**Comment by yurm04** [comment]
Thanks for the request, @arthurgouveia . We’re not actively working on this right now, but we keep an eye on all feature requests.

I’ll close this issue for now, but we encourage everyone who wants this feature to add a 👍 to the original issue report. We’ll take your collective interest into account when we look at what to work on next. 💜
