### ISSUE TITLE
Add option for different color mobile menu logo

### ISSUE THREAD

**Issue by achadee** [Shopify/polaris#3418]
## Feature request summary
We need a way to define a different image for the mobile menu to prevent image contrasting issues

see screenshots below
![Screen Shot 2020-10-08 at 8 26 11 pm](https://user-images.githubusercontent.com/5952918/95440298-82e0f700-09a4-11eb-8ea3-0b888632a517.png)

![Screen Shot 2020-10-08 at 8 26 29 pm](https://user-images.githubusercontent.com/5952918/95440321-8d9b8c00-09a4-11eb-93c1-96a037fc67d3.png)

Happy to fork and work on this if it hasn't been developed yet

**Comment by yurm04** [comment]
Thanks for the request, @achadee . We’re not actively working on this right now, but we keep an eye on all feature requests.
I’ll close this issue for now, but we encourage everyone who wants this feature to add a 👍 to the original issue report. We’ll take your collective interest into account when we look at what to work on next. 💜
