### ISSUE TITLE
Styleguide for date of birth field

### ISSUE THREAD

**Issue by shenst1** [Shopify/polaris#342]
What would be the Polaris way of entering a date of birth. The datepicker component isn't appropriate because the year is difficult to select. We use 3 select fields, month, day, year. However, using the ```  <FormLayout.Group>``` component seems to only allow two input fields in a 50 -50 layout and then it breaks to the next line (i.e. not a 1/3 grid), which is awkward. What component or flow is recommended if only Polaris components are used?

**Comment by ry5n** [comment]
You may be able to use the Stack component:

```jsx
<Stack distribution="fill">
  <TextField label="Month" />
  <TextField label="Day" />
  <TextField label="Year" />
</Stack>
```

Give this a try by pasting it into any of the playgrounds on the Polaris site, like here: https://polaris.shopify.com/components/structure/stack

**Comment by ry5n** [comment]
I tool another look at this, and my suggestion above still wraps earlier than I’d like. Assuming you’re OK with each field being equal width, it’s possible to simply turn off wrapping:

```jsx
<Stack distribution="fill" wrap={false}>
  <TextField label="Month" />
  <TextField label="Day" />
  <TextField label="Year" />
</Stack>
```

If you wanted more control over the relative widths of each input, you could build a component to handle it, something like this: https://codesandbox.io/s/xoy0l9o72w

If you have any further questions or issues feel free to re-open the issue.

**Comment by shenst1** [comment]
Great response! Thanks!
