### ISSUE TITLE
[Popover] Render a backdrop when opening a popover

### ISSUE THREAD

**Issue by tleunen** [Shopify/polaris#3421]
## Feature request summary

The popover doesn't render any backdrop when it's opened. I think it makes sense, but there are use cases where it would be really visually better to have a slightly darker backdrop when a popover is opened, which let the user know his focus has to be inside the popover. 

It would be great if we can have a new prop to render a backdrop automatically.

One example of this is inside Shopify Email, as shown below:
![Kapture 2020-10-08 at 09 19 18](https://user-images.githubusercontent.com/1972567/95463959-695d9200-0947-11eb-989b-a7538b3f5e9e.gif)

**Comment by yurm04** [comment]
Thanks for the request, @tleunen . We’re not actively working on this right now, but we keep an eye on all feature requests.
I’ll close this issue for now, but we encourage everyone who wants this feature to add a 👍 to the original issue report. We’ll take your collective interest into account when we look at what to work on next. 💜
