### ISSUE TITLE
Migrating from EmbeddedApp to AppProvider component

### ISSUE THREAD

**Issue by superwhykz** [Shopify/polaris#345]
I am getting consistent issue migrating(from v1.9.1 tp ^2.0.0 or ^2.1.1) EmbeddedApp to AppProvider.  I am trying to understand if it is me or something else. Greatly apprecieate for any clue how to resolve this.

Error from console:
https://drive.google.com/file/d/1K-lmeAx8PTZZ2JYeaTHj4cOTgjrVAEtd/view?usp=sharing

Here are my code snips.

```
...
ReactDOM.render(
  <Provider store={createStoreWithMiddleware(Reducers)}>
    <BrowserRouter>
      <Route path="/" component={App} />
    </BrowserRouter>
  </Provider>,
  document.getElementById('container'),
);
```

and `{App}` components 

```
          ...
          <AppProvider
              apiKey={apiKey}
              shopOrigin={'https://' + this.props.shop.shopOrigin}
              debug={false}
              forceRedirect={true}
          >
            <Switch>
                {/* <Route exact path="/" component={
                                        this.props.installed ?
                                            ....
                                    } /> */}
                <Route
              ...
              ...
              ...
             </Switch>
          </AppProvider>
          ...
          ...
```

**Comment by ry5n** [comment]
Thanks for reporting this. To confirm what you’re seeing: you’ve included the `AppProvider` component in your embedded app (wrapping any other Polaris components), but you’re still seeing the console warn about `AppProvider` being required?

**Comment by superwhykz** [comment]
Yes, that is correct. All Polaris components wrapped inside `AppProvider`.

**Comment by chloerice** [comment]
Hi @superwhykz, is the `AppProvider` missing from the component import in this file by chance?

**Comment by harbify** [comment]
Hi @superwhykz, looks like the error you are getting is because one or more of the Polaris components are not wrapped in AppProvider. Could you please make sure that all files that import Polaris Components are wrapped in AppProvider? Also, could you please use AppProvider right after Redux Provider ( wrap BrowserRouter with it )?

**Comment by superwhykz** [comment]
Thanks so much @ry5n @chloerice @harbify ! You are right I have one component `{Spinner}` which was not wrapped in `{AppProvider}`.  Ehh... I overlooked. I am going to refactor and give a try. 

@harbify thanks for idea move `{AppProvider}` closer to `{Redux Provider}`.  I will see if I can move it up. I am pulling shop info from my own api need to see how it can be done.

**Comment by ry5n** [comment]
@superwhykz Thanks for the follow-up. `Spinner` definitely does need to be inside the `AppProvider`, so I’ll close this for now. But if you run into any problems please re-open this issue and ask; we’re happy to help.
