### ISSUE TITLE
Support partial width form components

### ISSUE THREAD

**Issue by mbaumbach** [Shopify/polaris#347]
# Issue summary

This is a feature request.

There are some scenarios where a smaller form control may be more appropriate, but there doesn't appear to be a well-defined way to build a form in this manner.

For example, in the Discounts area in the Shopify admin, there are some cases where a partial width control occurs:

![Partial width control](https://i.imgur.com/ZwyrX2G.png)

This can be especially useful for number inputs since this brings the spinner control and suffixes on the right closer to the text box value for small input values:

![Small input with suffix](https://imgur.com/cfenlo5.png)

## Expected behavior

Ideally, there could be a specialized component like `FormLayout.PartialItem` (or some much better name) that would limit the max width of the child control. Perhaps with a prop that determines the max width.

If this is going to pattern that you might want to support in Polaris, I think a dedicated component or more opinionated documentation would be great.

## Actual behavior

Currently, to accomplish this you either have to wrap the control in some component that sets the max-width, somewhat abuse the `FormLayout.Group` component, or use a `Stack`. A couple examples:

```
<FormLayout.Group>
    <TextField ... />
    <div />
</FormLayout.Group>
```
This would give you a half-width control, but you can do additional hackery with the `condensed` option on the group to get quarter-width.

```
<Stack>
    <TextField .../>
</Stack>
```
This results in a partial width control, though it appears to be slightly inconsistent in size depending on the props of the child control:

![Slight size differences](https://media.giphy.com/media/2vs5JTLLgFcDdBltZq/giphy.gif)

I don't think there's anything wrong with wrapping the control, but it feels like the `FormLayout.Group` is already solving similar problems in this space, so it seems natural to me to potentially extend it (or create a different `FormLayout` namespaced component) for this case if it's a common enough problem.

## Specifications

- Polaris version: 2.1.2
- React version: 16.4.0
- Browser: Any
- Device: Any
- Operating System: Any

**Comment by mbaumbach** [comment]
If this isn't a common enough problem, feel free to make this issue disappear. 😄

**Comment by ry5n** [comment]
I think this is something we should support, but it’s not slated to be tackled right away. In the meantime, I’m not sure what the absolute best solution is. One possibility that comes to mind is creating a simple component that acts a container with a max-width. The max-width could be set in a percentage or something that approximates the number of characters of input expected.

I’ll close this issue for now, but **we encourage everyone who wants this feature to add a 👍** to the original issue report. We’ll take your interest into account when we look at what to work on next.
