### ISSUE TITLE
Stacking Modals seems not possible

### ISSUE THREAD

**Issue by reflog** [Shopify/polaris#349]
# Issue summary

It's impossible to show one Modal on top of the other, the z-order is not maintained.

## Expected behavior

Every newly opened Modal should get z-order higher than the previous one.

## Actual behavior

Modal is placed on the bottom.

## Steps to reproduce the problem

1. Create a Modal
1. Place a button that opens another Modal
1. The second Modal will not be visible

**Comment by chloerice** [comment]
Hi @reflog, can you can describe your use case for presenting merchants with multiple modals at once?

**Comment by reflog** [comment]
I have a dialog (New Invoice) that has a Select dropdown (Clients) and an action (Add client).
I want that action to open another modal.

**Comment by ry5n** [comment]
Modals suspend the current flow and ask the merchant to do a small task in which they need to either confirm or cancel. Bringing them from such as context into another modal is kind of “modal inception” and is likely to be confusing. We don’t plan to make changes to the modal to enable this.

I would follow the general strategy that Shopify does, which uses a new page for create actions (like the collection create page). In this case adding a client could use a modal in the same way that adding products to a collection does.
