### ISSUE TITLE
TextField - Pass along required prop to input

### ISSUE THREAD

**Issue by dkershner6** [Shopify/polaris#3512]
## Feature request summary

The html input required prop enforces that an input has a value upon submit.  This would be helpful to be able to do with Polaris' `TextField` as well.

## Rationale

This would be easy to implement and provide a lot of extra functionality.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by yurm04** [comment]
Thanks for the request, @dkershner6 . We’re not actively working on this right now, but we keep an eye on all feature requests.

I’ll close this issue for now, but we encourage everyone who wants this feature to add a 👍 to the original issue report. We’ll take your collective interest into account when we look at what to work on next. 💜
