### ISSUE TITLE
Button actions are shown in Card when printing

### ISSUE THREAD

**Issue by tarynmusgrave** [Shopify/polaris#3539]
## Feature request summary

When printing the button actions group in the header is visible and should be hidden. Targeting 'buttons' in the card outside of polaris results in unintended actions such as hiding the email address (which is also a button outside of the header). 

![](https://screenshot.click/21-10-ps36x-0gk31.jpg)

## Rationale

---
This is required for the order details project. 

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by gcornhill** [comment]
Since this is lower priority and we are in code chill, I'm going to move this to nice to have.
@tarynmusgrave we can pair when you are back to prep a polaris component that hides children

**Comment by yurm04** [comment]
@gcornhill @tarynmusgrave is this feature request still relevant? Wondering if I can close it or if it's worth revisiting

**Comment by gcornhill** [comment]
I think may be worth re-visiting. The idea is there's always a bunch of things we want to hide on print. Taryn and I were going to make a polaris component which would just hid it's children on print. Not sure if this is the best way to solve it, but we have to target and hide things with custom css a lot on the order details page.

**Comment by yurm04** [comment]
Makes sense 👍 

I don't have a well formed opinion on how to do this at scale in the system, or if we even should. Maybe we can start locally in `shopify/web` test it out there and then revisit if the need across `shopify/web` and 3P developers is there?

Where to start with this... we used to have a sass function [`hidden-when-printing()`](https://github.com/Shopify/polaris/blob/43e205df38690c19b6a54fb0df4df4ebc7135c26/documentation/guides/migrating-from-v8-to-v9.md#hidden-when-printing) that was recently deprecated. The alternative now is:

```css
/* in a styles.scss file */

@media print {
  display: none !important;
}
```

Would a `HiddenWhenPrinting` wrapper react component in `shopify/web` be a viable solution to this? ex.

```jsx
import styles from './styles.scss'

const HiddenWhenPrinting = ({ children }) => {
  return (
    <div className={styles.hiddenWhenPrinting}>
      {children}
    </div>
  )
}
```

and then it could be used...

```jsx
<HiddenWhenPrinting>
  <Button>I should be hidden when printing</Button>
</HiddenWhenPrinting>
```

Here's a [CodeSandbox](https://codesandbox.io/s/busy-sanne-rofnux?file=/App.js) demo. Not entirely sure if this would work universally across `shopify/web` on polaris components but worth experimenting?
