### ISSUE TITLE
Feature Request: Customizable ResourcePicker components

### ISSUE THREAD

**Issue by sdn90** [Shopify/polaris#354]
Hey guys, great job on the major release. Its been a great experience working with it.

Are there any plans on building a lower level resource picker component? I think with the release of the GraphQL API, it would be fairly straight forward to build on from a developer perspective.

There are a few problems I think this could help with:

1. We need to display other data besides the collection/product's title
2. We may have validation errors we need to display in the picker component
3. We need a way to display the loading state of the resource picker. The current resource picker doesn't show any loading indicators and loads upon server response. On a 100mb connection, sometimes this takes a few seconds. This ends up being a few seconds of no visible feedback indicators for the user.

Also somewhat related but a different request:
Would it be possible to have some kind of abstraction for iframe messaging to make communication between modal and parent app easier?

**Comment by ry5n** [comment]
All really good questions. @gf3 what do you think?

**Comment by meecrobe** [comment]
+1

It will also be good to have an opportunity to have access to products/collections to filter them.
E.g. exclude unavailable products or products with 0 stock quantity from the rendered list.

**Comment by tms320c** [comment]
Really good request! I'd like to add to "We need to display other data besides the collection/product's title"  from @sdn90 -  we need to display other collections, e.g. discounts, as well.

**Comment by ry5n** [comment]
We’re currently making improvements to the EASDK that underlies the Polaris resource picker, but we’re not able to tackle the customizable list right now. For that reason, I’m closing this issue as we do for all feature requests in our backlog.

However, **I encourage everyone to keep adding 👍** to the original issue report. We do take your requests into account when we look at what to work on next.

💜
