### ISSUE TITLE
Allow retargeting of Resource List Item after an action

### ISSUE THREAD

**Issue by melissaluu** [Shopify/polaris#3545]
## Feature request summary
When a `ResourceListItem` row click triggers an action that opens a `Sheet` or `Modal`, there's currently not a clean way to retarget the trigger `ResourceListItem` when the overlay component closes. This makes it harder for users to know where they were within the main page flow after interacting with an overlay.

## Rationale
Enabling retargeting of triggered `ResourceListItem` will allows for a better user experience when using keyboard navigation. Also, refocusing on the trigger list item allows users to visually see what they had clicked on previously to open up the overlay.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by yurm04** [comment]
Thanks for the request, @melissaluu. We’re not actively working on this right now, but we’d love for it to make its way into the system. Please feel free to contribute and open a PR!
