### ISSUE TITLE
Add pagination to page component on small screen sizes.

### ISSUE THREAD

**Issue by jessebc** [Shopify/polaris#3553]
Pagination should display at the smallest breakpoints. 
Keyboard shortcuts for pagination (J/K) should also be accepted (currently, they aren't).

Before
![Before](https://user-images.githubusercontent.com/1591075/96899742-419a1e00-145f-11eb-905c-02d5bc9a204e.png)

After
![After](https://user-images.githubusercontent.com/1591075/96899756-465ed200-145f-11eb-8927-21f37e3bed70.png)

**Comment by kyledurand** [comment]
Hey @jessebc / @AdamWhitcroft / @erapago adding pagination could result in breaking layouts on iPhone SE size screens. We should take stock of admin pages that have primary actions and test in different languages like German before shipping this change.

![image](https://screenshot.click/Storybook_2020-10-30_14-33-38.png)

**Comment by jessebc** [comment]
Could we make icons a mandatory prop for primary actions in the page component? If so, we could confidently resize a primary action to just show the icon.

**Comment by kyledurand** [comment]
Yep that's a possibility but with code chill starting Monday it might be tough to cut a new polaris release and also update all of the primary actions in web. This one might have to wait til v6 or maybe later. cc @alex-page do you think we can get this type of change in during the chill?

**Comment by alex-page** [comment]
From my understanding it's a new feature so maybe we can't add it during the code chill. Is there a large UX problem this is addressing? It looks super useful to quickly go through multiple pages on mobile.

**Comment by kyledurand** [comment]
I did a bit more exploration here and it looks like primaryAction can also be a react node. Main reason being that consumers wanted to use the split button variant:

![image](https://screenshot.click/Button_-_Shopify_Polaris_2020-12-16_15-07-52.png)

We could disallow that in V6 but I'm also of the mind that icon buttons just aren't as clear and usable with buttons that have full text.

I'd like to revisit this question from Alex:

> Is there a large UX problem this is addressing?

**Comment by alex-page** [comment]
Closing for now. We can revisit page navigation on mobile another time.
