### ISSUE TITLE
Support for typeahead in text field

### ISSUE THREAD

**Issue by spchuang** [Shopify/polaris#356]
# Feature request summary
Currently there's no obvious ways to add typeahead in the Text Field. 

## Rationale

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 We _are_ accepting issue reports and feature requests<br />
🌟 Feature requests that we can’t get to right away will be closed. However, we track all requests and will use it to set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by tmlayton** [comment]
Thanks for the request, @spchuang. We‘re [currently considering this component under the name Autocomplete](https://polaris.shopify.com/components/component-status).

I’ll close this issue for now, but **we encourage everyone who wants this feature to add a 👍** to the original issue report. We’ll take your collective interest into account when we look at what to work on next.

💜

**Comment by spchuang** [comment]
Thanks! Is there an estimated timeline

**Comment by tmlayton** [comment]
We just moved this to "in development" https://polaris.shopify.com/components/component-status. There are a few decisions we need to make in terms of the API and how much should be handled by the component vs implemented by the consumer – otherwise no estimated timeline at the moment.

**Comment by tmlayton** [comment]
@spchuang we just merged an autocomplete component into our beta branch. Once we do another beta release, you are welcome to use that. Otherwise, depending on testing, this component will be released in one of the upcoming minor versions.

**Comment by Nisthar** [comment]
@tmlayton is there an estimate on this? This feature is really needed for my project.

**Comment by tmlayton** [comment]
@Nisthar no estimate currently, there are a couple outstanding issues that need to be addressed with the component beta.

**Comment by mbriggs** [comment]
@tmlayton month later, any update on when this will be available in some form? <3

**Comment by tmlayton** [comment]
This is available in `v3.0.0-beta.9` and will go out with v3.0.0.
