### ISSUE TITLE
ToolTip Active Bug?

### ISSUE THREAD

**Issue by tktnguyen711** [Shopify/polaris#3577]
## Issue summary
When I set active={false} for the tooltip component, it still shows the tooltip.

## Expected behavior
setting active={false} should hide the tooltip?

## Actual behavior
When I set active={false} for the tooltip component, it still shows the tooltip.

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error while running Polaris.

If you include an animated gif showing your issue, wrapping it in a details tag is also recommended. Gifs usually autoplay, which can cause accessibility issues for people reviewing your PR:

    <details>
      <summary>Summary of your gif(s)</summary>
      <img src="..." alt="Description of what the gif shows">
    </details>

-->

## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by thayannevls** [comment]
Hey @tktnguyen711 I just created a PR fixing the issue, could you take a look? 🙏

**Comment by heming-yuan** [comment]
Any updates? I have same issue.
