### ISSUE TITLE
Country Resource Picker

### ISSUE THREAD

**Issue by ahmadfh** [Shopify/polaris#361]
# Feature request summary
It would be great to have Country Resource Picker, like Products & Collections Resource Picker.
And i think it would be perfect to have the same country picker as the one exists in **Shipping Zones Page**.

## Rationale
It would make our life easier when we are creating apps that rely on customers countries.

**Comment by chloerice** [comment]
Hi @ahmadfh, thanks for raising this. I've added this to our feature request backlog, so I’ll close this issue for now.

We encourage other folks who want this feature to add a 👍to the issue description. Collective need weighs into what we build next 😊.

**Comment by sebastianpisula** [comment]
any updates?

**Comment by boxedcode** [comment]
Has there been a recent consensus on this feature from the Shopify product team?

**Comment by AndrejMazhenkovski** [comment]
Still a much-needed feature, unfortunately I haven't seen any updates to the resource picker to include countries. Any plans to revive this backlog item?

**Comment by boxedcode** [comment]
I ended up implementing my own Country Resource picker, modelled in the same style and functionality as the Shopify one. I'm more than happy to share the component for anyone interested.

**Comment by AndrejMazhenkovski** [comment]
That would be great @boxedcode - thank you!

**Comment by sebastianpisula** [comment]
@boxedcode I'm interest. I think that great place do share the component will be this platform: https://www.polariscomponents.com
