### ISSUE TITLE
[New DL] Badge shape and size is slightly off

### ISSUE THREAD

**Issue by ry5n** [Shopify/polaris#3614]
## Issue summary

With the new design language, badges are slightly the wrong size and shape.

## Expected vs actual behavior

Badges should match the line height of body text (20px) but are 22px tall instead:

![Screen Shot 2020-11-10 at 9 41 13 AM](https://user-images.githubusercontent.com/804014/98711728-36d5f900-233a-11eb-8f0e-e7ea3a31d4a0.png)

Badges should’t be taller than wide, but this can happen:

![Screen Shot 2020-11-10 at 9 41 51 AM](https://user-images.githubusercontent.com/804014/98711967-8d433780-233a-11eb-8a44-79ca0dc83b9b.png)

The small badge variant actually renders larger (taller) than the normal badge! It’s intended to be 18px tall:

![Screen Shot 2020-11-10 at 9 43 33 AM](https://user-images.githubusercontent.com/804014/98712085-afd55080-233a-11eb-9e96-3670ec2801d4.png)

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: whatever Admin is using as of Nov 10, 2020
- Browser: Chrome 86
- Device: Mac
- Operating System: macOS 10.15.7

**Comment by alex-page** [comment]
Badge is 20px 🎊 

![Screen Shot 2022-05-19 at 3 20 52 PM](https://user-images.githubusercontent.com/19199063/169414006-ef970117-d802-411a-be1d-cd56d15d8890.png)
