### ISSUE TITLE
Explanation Wanted of Title + Header Concepts

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/polaris#3623]
We're at Polaris 5 now and I am still confused about some of it. Here are my questions. Anyone care to illuminate me? 

1. If a Card has a title, why would anyone ever use a <TextContainer> in the <Card> to present a <Header>?
2. When I render things in a <Card> without the decoration **sectioned** the content is presented without margins. What is the purpose of this **sectioned** attribute in general? 

Basically every time I try and render nice headings I get crossed up because typically my containers have a title that looks just like the heading, so I am like, why does this even exist? Sometimes too many elements can make for a murky soup. Should I just always use the <Card> title and forget <Heading> elements?

I know someone somewhere inside the Polaris spaceship has some idea of why all this is, and there could very well be an explanation somewhere, but I figure it just easy to ask the questions then spend days spelunking the written words.

**Comment by alex-page** [comment]
Hey @resistorsoftware I'll pass this onto our team. We are currently investigating layout and it definitely is confusing how sectioned components and typography works. I am going to close this issue as we are looking across multiple components. Feel free to reopen it if future releases do not resolve this issue.
