### ISSUE TITLE
Date Picker

### ISSUE THREAD

**Issue by sanchit121** [Shopify/polaris#363]
Hi I am using @shopify/react-utilities": "^1.2.0" ,
I am having issue with range select 
In the read me:
**Set the start date on first click and the end date on second click if a range
is required**
But for me on first and second click start and end date is same.
`export default class FilterDateCard extends Component<Props, State> {
  state = {
    startDate: this.props.dateFilter.startDate || null,
    endDate: this.props.dateFilter.endDate || null
  };

  nextDate = () => {
    let nextDay = new Date();
    nextDay.setDate(new Date().getDate() + 5);
    return nextDay;
  };

  render() {
    let filter: FilterDate = {
      startDate: '',
      endDate: ''
    };
    return (
      <Card>
        <Card.Section>
          <DatePicker
            month={
              this.state.startDate
                ? new Date(this.state.startDate).getMonth()
                : new Date().getMonth()
            }
            year={
              this.state.startDate
                ? new Date(this.state.startDate).getFullYear()
                : new Date().getFullYear()
            }
            multiMonth
            selected={{
              start: this.state.startDate
                ? new Date(this.state.startDate)
                : new Date(),
              end: this.state.startDate
                ? new Date(this.state.endDate)
                : this.nextDate()
            }}
            onChange={value => {
              this.setState({
                startDate: dateFormat(value.start, 'mm/dd/yyyy'),
                endDate: dateFormat(value.end, 'mm/dd/yyyy')
              });
              filter.startDate = this.state.startDate;
              filter.endDate = this.state.endDate;
              this.props.onApplyDate(filter);
              this.props.onCloseFilters;
            }}
          />
        </Card.Section>
      </Card>`
 This is my code.
Note: I cant update this version as per some strict rules we are following. Please help

**Comment by dleroux** [comment]
👋 @sanchit121

Could it be because you are missing the `allowRange={true}` on your Datepicker?

**Comment by sanchit121** [comment]
@dleroux I am using older version which does not have prop called allowRange

**Comment by sanchit121** [comment]
1.11.0

**Comment by dleroux** [comment]
Yes, that was an issue we had before the allowRange. In order to work around some of us did this:

```
// Datepicker doesn't initialize properly when start and end are the same,
// so set them a minute apart.
// Tracking here: https://github.com/Shopify/polaris-react/issues/834
const start = new Date();
const end = new Date();
end.setMinutes(end.getMinutes() + 1);
```

Do you want to give that a shot since you can't upgrade?

**Comment by sanchit121** [comment]
1. Thanks @dleroux for this, but here the link which you mentioned not working (404).
2. I am initializing the date picker with (end date)6 days after start date.
3. problem is when user selects wants to select range.
Hope you understanding my point.

**Comment by dleroux** [comment]
I'm sure why your code isn't working but in setting it up to work in our playground we got it working. Looks like moving the values being evaluated inside the prop to their own variable made it work. Here's my working playground code. Let me know if that helps. Thanks @chloerice for the help on this.

```
import * as React from 'react';
import {Page, DatePicker, Range} from '@shopify/polaris';

interface State {
  startDate: Date,
  endDate: Date,
  selected: Date | Range,
}

export default class Playground extends React.Component<never, State> {

  state: State = {
    startDate: new Date('june 26, 2018'),
    endDate: new Date('june 30, 2018'),
    selected: {
      start: new Date('june 26, 2018'),
      end: new Date('june 30, 2018'),
    }
  }

  nextDate = () => {
    let nextDay = new Date();
    nextDay.setDate(new Date().getDate() + 5);
    return nextDay;
  };

  handleChange = (value) => {
    this.setState({
      selected: value,
      startDate: value.start,
      endDate: value.end,
    });
  }

  render() {
    const {startDate, endDate} = this.state;

    const year = startDate
      ? new Date(startDate).getFullYear()
      : new Date().getFullYear();

    const month = startDate
      ? new Date(startDate).getMonth()
      : new Date().getMonth();

    const start = startDate
      ? new Date(startDate)
      : new Date();

    const end = endDate
      ? new Date(endDate)
      : this.nextDate();

    const selected = this.state.selected
      ? this.state.selected
      : {start, end};

    return (
      <Page title="Playground">
        <DatePicker
            month={month}
            year={year}
            multiMonth
            selected={selected}
            onChange={this.handleChange}
        />
      </Page>
    );
  }
}
```

**Comment by sanchit121** [comment]
@dleroux Yes, even i made it working today morning my time, the key here that i added selected state, thats the only thing i can find, but not sure even now why my code not worked, but anyways thanks for all your support and help. Really appreciating!. Thanks

**Comment by chloerice** [comment]
Hey @sanchit121, initializing state with props can introduce some silent errors and side effects that are difficult to debug. I'd recommend keeping your props out of state, and looking for/using them directly before returning in your render function. If you do want to use props to initialize your state, you'll need to initialize in the constructor.

```jsx
export default class FilterDateCard extends Component<Props, State> {
  constructor(props: Props) {
    super(props)
    this.state = {
      startDate: this.props.dateFilter.startDate || null,
      endDate: this.props.dateFilter.endDate || null
    }
  }

...
```

This is just sudo since I don't have the rest of your app to run, but here's how I'd recommend decoupling your props to initialize your date picker state (tested using the [Polaris playground](https://github.com/Shopify/polaris/blob/master/playground/Playground.tsx)):

<details>
<summary>Click to view collapsed example code</summary>

```jsx
import * as React from 'react';
import {Page, Card} from '@shopify/polaris';
import DatePicker from '../src/components/DatePicker';
import {Months, Year, Range, Props} from '../src/components/DatePicker';

interface State {
  month: Months,
  year: Year,
  selected?: Date | Range,
}

export default class Playground extends React.Component<never, State> {
  constructor(props: Props) {
    super(props)
    this.state = {
      month: 5,
      year: 2018,
      selected: undefined
    }
  }

  handleChange = (date: Range) => {
    this.setState({selected: date})
  }

  handleMonthChange = (month: Months, year: Year) => {
    this.setState({month, year})
  }

  render() {
    const start = this.props.startDate ? this.props.startDate : new Date();
    console.log(start)
    const end = this.props.endDate ? this.props.endDate : new Date(2018, 5, start.getDate() + 2);
    const selected = this.state.selected ? this.state.selected : {start, end}

    return (
      <Page title="Playground">
        <Card>
          <Card.Section>
            <DatePicker
              month={this.state.month}
              year={this.state.year}
              selected={selected}
              onChange={this.handleChange}
              onMonthChange={this.handleMonthChange}
            />
          </Card.Section>
        </Card>
      </Page>
    );
  }
}
```

</details>
