### ISSUE TITLE
page title with newDesignLanguage

### ISSUE THREAD

**Issue by kouloughli-hemza** [Shopify/polaris#3636]
Hello,
i tried to use `newDesignLanguage` , everything works fine , but found little bug in `Page` component 
the title has no styling when using `newDesignLanguage` 
is it an expected behaviour?

**Comment by alex-page** [comment]
Hey @kouloughli-hemza make sure you have the `<CustomProperty>` component included to see the visual styles correctly. Feel free to reopen if this does not resolve your issue.
