### ISSUE TITLE
Dynamic row keys for DataTable

### ISSUE THREAD

**Issue by mattrothenberg** [Shopify/polaris#3648]
## Feature request summary
Currently, `DataTable` row keys are hard coded according to the convention `row-${index}`. [Opinions abound on this subject](https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318) of whether an index should be used as a row key, but I've already run into a few UI issues related to item re-ordering and filtering due to this index convention.

https://github.com/Shopify/polaris-react/blob/master/src/components/DataTable/DataTable.tsx#L382

Would it be possible to expose an optional `rowKey` prop on the `DataTable` component that allows users to customize this index? Something like:

```tsx
rowKey?: (row: TableData[]) => string;
```
Now, users have the ability to return whatever they want, given a particular table row's data 🎊 

## Rationale
I'm making the assumption that the majority of users implementing this component are working with lists of data that have **unique IDs**. To that end, we should allow users to use this fixed, unique value as a key and not ephemeral data like row indices.

**Comment by adithej** [comment]
I am facing this same issue and doesn't seems to be fixed or am I missing anything.
