### ISSUE TITLE
TextField with type="number" allows input of non-digit characters in Firefox.

### ISSUE THREAD

**Issue by meecrobe** [Shopify/polaris#365]
# Issue summary
TextField with type="number" allows to input non-digit characters in Firefox.

## Expected behavior
TextField with type="number" must prevent input of non-digit characters.

## Actual behavior
![screencast 2018-06-25 16-31-43](https://user-images.githubusercontent.com/8003440/41853016-63838bb8-7895-11e8-9622-709ab0952945.gif)

## Specifications

- Are you using the React components? (Y/N): yes
- Polaris version number: 2.0.0
- Browser: Firefox Quantum 60.0.2
- Device: iMac (21.5-inch, Late 2012)
- Operating System: MacOS High Sierra 10.13.3 (17D47)

**Comment by ry5n** [comment]
Currently we’re not doing anything special that `<input type="number">` doesn’t already do. Chrome prevents some alphanumeric input (although notation for exponents like `6.022e24` is allowed) but most other browsers don’t, including Firefox and Safari. We’re still discussing whether we should add additional constraints.

**Comment by ry5n** [comment]
This isn’t at the top of our priority list. Moving to a feature request. Please upvote the original post to help us set priorities. 💜

**Comment by ry5n** [comment]
We’ve fixed this in our pre-release build. It should be available in the next release. Note that we’re matching the spec, which doesn’t allow some characters like `,` which some languages use as separators. We can revisit that as a separate issue, but the current fix is intended to make cross-browser behavior more consistent.

Thanks for the feature request!
