### ISSUE TITLE
Cannot set max of 0 on RangeSlider

### ISSUE THREAD

**Issue by andrewpye** [Shopify/polaris#367]
# Issue summary

A `max` of 0 on the `RangeSlider` component is ignored.

## Expected behavior
Passing `max={0}` should render a `RangeSlider` with a maximum value of 0.

## Actual behavior
The `RangeSlider` renders with a maximum value of 100 because of [this line](https://github.com/Shopify/polaris/blob/master/src/components/RangeSlider/RangeSlider.tsx#L76).

## Steps to reproduce the problem

1. Render a `RangeSlider` component with `max={0}`
2. Check the maximum value the slider will allow.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: v2.2.0
- Browser: Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)
- Device: Macbook Pro
- Operating System: macOS Sierra Version 10.12.6 (16G29)

**Comment by ry5n** [comment]
Thanks for reporting. I’ve added this to our internal bug tracker.

**Comment by ry5n** [comment]
We’re working on a fix for this.

**Comment by andrewpye** [comment]
Awesome, thanks for the update @ry5n!

**Comment by ry5n** [comment]
A fix for this will be available in the next release.

**Comment by chloerice** [comment]
(@andrewpye [v2.3.1](https://github.com/Shopify/polaris/releases/tag/v2.3.1) has shipped with the fix)
