### ISSUE TITLE
RangeSlider divides by zero when min and max are equal

### ISSUE THREAD

**Issue by andrewpye** [Shopify/polaris#368]
# Issue summary
Minor issue, but when the same value is passed to the `RangeSlider` component for both `min` and `max`, [`sliderProgress` is `NaN` due to dividing by zero](https://github.com/Shopify/polaris/blob/master/src/components/RangeSlider/RangeSlider.tsx#L105). This means that the `--Polaris-RangeSlider-progress` style applied to the `div.Polaris-RangeSlider` takes a value of `NaN%`.

## Steps to reproduce the problem

1. Render a `RangeSlider` component, passing the same value for both `min` and `max`.
2. Inspect the styles applied to the `div.Polaris-RangeSlider` element.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: v2.2.0
- Browser: Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)
- Device: Macbook Pro
- Operating System: macOS Sierra Version 10.12.6 (16G29)

**Comment by ry5n** [comment]
Thanks for reporting this; I’ve opened a corresponding issue in our internal bug tracker.

Is there a situation where this could happen in your app? It will help assess priority.

**Comment by ry5n** [comment]
I think this is a case where the developer should guard against min and max being equal, because it’s hard to imaging when the resulting UI would be what you’d want. Please re-open if I’ve missed something.

**Comment by andrewpye** [comment]
@ry5n agreed this is really edge-casey and unlikely to show up in real-world app usage. Just wanted to flag it up in case it was something you guys wanted to handle in the component 🙂

**Comment by ry5n** [comment]
Still good to flag it; thanks. We might yet fix it, it’s just not at the top of the priority list.
