### ISSUE TITLE
[SkeletonPage] Title skeleton should not display if title is set to null

### ISSUE THREAD

**Issue by ivorpad** [Shopify/polaris#3689]
## Feature request summary

When passing `null` to the title prop it should be removed.

<img width="748" alt="Screenshot 2020-12-08 at 13 01 15" src="https://user-images.githubusercontent.com/52452/101481434-77cf2680-3955-11eb-9ad3-8ba8ed16ada2.png">

## Rationale

It should behave as in the `Page` component. 

PS: This is a simple fix so I can submit a PR if permitted.

**Comment by yurm04** [comment]
Thanks for the request, @ivorpad . We’re not actively working on this right now, but we’d love for it to make its way into the system. Please feel free to contribute and open a PR!

**Comment by ivorpad** [comment]
@yurm04, no thanks - Shopify is not friendly towards PRs. The fact that this issue was written in **2020** is proof that contributions sit untouched for a long time.

Additionally, I've tried contributing to [shopify_app](https://github.com/Shopify/shopify_app) without any response. There's no point in wasting my time anymore.
