### ISSUE TITLE
Chrome Autofill yellow background not covering the whole text field

### ISSUE THREAD

**Issue by MateusJabour** [Shopify/polaris#369]
# Issue summary

<img width="594" alt="screen shot 2018-07-03 at 1 12 20 pm" src="https://user-images.githubusercontent.com/11710000/42234615-1f5fbc8e-7ec3-11e8-9e42-0fca62bbd910.png">

Chrome Autofill yellow background not covering the whole text field

## Steps to reproduce the problem

1. Go to a TextField and select an autofill option.
2. The TextField background will become yellow, but it will not cover the whole field.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 2.2.0
- Browser: Chrome
- Device: MacBook Pro
- Operating System: MacOs High Sierra

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 We _are_ accepting issue reports and feature requests<br />
🌟 Feature requests that we can’t get to right away will be closed. However, we track all requests and will use it to set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by ry5n** [comment]
We flagged this issue a little while ago ourselves, and it just to happens that the [latest release](https://github.com/Shopify/polaris/releases/tag/v2.3.0) includes a fix for this issue 🎉 

Feel free to reopen if you run into anything related with the new release.
