### ISSUE TITLE
Need for a Bulk Editor Component

### ISSUE THREAD

**Issue by nemoeric** [Shopify/polaris#370]
# Feature request summary

It would be awesome to get the bulk editor as a Polaris component so we can keep merchant in the same experience when modifying content from our app ! 

I've been looking at the doc and didn't see one mentioned 

Thanks

**Comment by miclovich** [comment]
+1 on this feature.

**Comment by ry5n** [comment]
Thanks for the request @nemoeric. The bulk editor is one of the more complex interfaces in Shopify today. We’re considering adding it to Polaris and thinking about how we would do that. I’ll make an issue to add it to [the component status page](https://polaris.shopify.com/components/component-status#navigation).

As for all feature requests, I’ll close this issue for now, but **we encourage everyone who wants this component to add a 👍** to the original issue report. We’ll take your collective interest into account when we look at what to work on next.

💜

**Comment by mikeyhew** [comment]
The `ResourceList` component support bulk actions, at least that's what it says in the tutorial, so is there something else that is being requested here?

**Comment by sijad** [comment]
@mikeyhew this issue is for "bulk editor" not "bulk actions"

![2019-05-13-09:24:44-screenshot](https://user-images.githubusercontent.com/7693001/57596653-0a80c700-7561-11e9-9bb4-4d51d18a876d.png)

**Comment by pateketu** [comment]
> [@mikeyhew](https://github.com/mikeyhew) this issue is for "bulk editor" not "bulk actions"
> 
> ![2019-05-13-09:24:44-screenshot](https://user-images.githubusercontent.com/7693001/57596653-0a80c700-7561-11e9-9bb4-4d51d18a876d.png)

This looks pretty close to Shopify's Bulk edit screens. Is this available  anywhere?
