### ISSUE TITLE
Polaris  - Shopify Admin - Poor UX Experience

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/polaris#371]
So I am using Polaris to edit a theme in a merchant store. I go to Add a Snippet and the Polaris dialog comes up. I hit a few keys to provide the snippet name but instead I am faced with now editing a new Page??? 

Note how I went from attempting to add a new Snippet in Theme editing to editing a Page. The simple explanation is that no one bothered to hook up the keyboard in Shopify Admin Polaris Modals with text fields. 

It is that kind of bad example that makes the rest of us using Polaris scared. My only point I guess is that if Shopify developers cannot make Polaris do the right thing, the challenge for us outside Shopify is much harder than it should be. 

So my request is for Shopify to enhance Polaris so that it has less options for us to shoot ourselves in the foot. Hooking up keyboard focus on modals and their fields is a good thing and probably a great default for almost all instances of a Modal with fields.

**Comment by lemonmade** [comment]
Do you have other examples beyond the keyboard focus issue you noted that lead to the more generally-critical title? If this is specifically about the issue in question it would be good to hone in on that to avoid the discussion going off in other directions.

(I defer to the Polaris team who will know better, but from my perspective, it is debatable that this is not the correct behavior. Automatically throwing a user to the first input in the modal may leave a screen reader user without enough context to know what they are trying to enter, and this effect should be easy to achieve where appropriate using the autoFocus TextField prop).

**Comment by resistorsoftware** [comment]
I am pointing out an obvious wart on Polaris. I changed my title since it clearly was too abstract to be of use. Funny you mention screen readers and how even in 2018 crackerjack programmers cannot get a simple workflow that support mouse, keyboard and screen readers without janky results. So much for progress since 1996....
