### ISSUE TITLE
Feature Request: Slim and Large input fields

### ISSUE THREAD

**Issue by asacarter** [Shopify/polaris#373]
The buttons have different size padding with `Polaris-Button--sizeLarge` and `Polaris-Button--sizeSlim`.

It would be ideal to have other form fields such text inputs and selects that also have this option. For example: `Polaris-TextField--sizeLarge` and  `Polaris-TextField--sizeSlim`.

**Comment by chloerice** [comment]
Hey @asacarter 👋thanks for the request. We treat all feature requests as part of our backlog, so I’ll close this issue for now and add this to our internal project board. 

**We encourage everyone who wants this feature to add a 👍** to the issue description. Your collective interest is taken into account when we look at what to work on next.

💜
