### ISSUE TITLE
Single column skeleton page

### ISSUE THREAD

**Issue by vladucu** [Shopify/polaris#376]
# Feature request summary

Add support for `singleColumn` property for the skeleton page component.

The `page` component supports a `singleColumn` boolean property which `Decreases the maximum layout width. Intended for single-column layouts`.
Would be great for the skeleton page to have this too, for the cases where a single-column layout is needed.

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 We _are_ accepting issue reports and feature requests<br />
🌟 Feature requests that we can’t get to right away will be closed. However, we track all requests and will use it to set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by ry5n** [comment]
Great point @vladucu. We really should have this, so I’m treating it as a bug rather than a feature request.

**Comment by tmlayton** [comment]
Hey @vladucu, this is fixed in 2.6.0. Thanks again for raising this issue!
