### ISSUE TITLE
A wrong about DropZone's onDrop Event

### ISSUE THREAD

**Issue by w-e-d** [Shopify/polaris#3765]
## Issue summary

I dropped or uploaded .ico images into DropZone which accept is  [image/x-icon].

## Expected behavior
I got the files in the acceptedFiles.

## Actual behavior

I got nothing in onDrop's acceptedFiles, but I can see the files when I unfolded the Array in console.

## Steps to reproduce the problem

1.import DropZone component and set onDrop
1.set 'image/x-icon' on DropZone's accept
1.choose a .ico icon and drop into DropZone and then console log(acceptedFiles)

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by prabureddy** [comment]
Once check this [documentation](https://polaris.shopify.com/components/actions/drop-zone) for DropZone and check everything you did was correct and if the problem persists, open this [codesandbox templete](https://codesandbox.io/s/q82mlq0m26) and write down your code and share the link here. So, it will be easy to inspect the problem.
