### ISSUE TITLE
Request: DateRangePicker component

### ISSUE THREAD

**Issue by vfonic** [Shopify/polaris#377]
It would be great if this library had a date range picker component.

This component could be used for any UI where an app would need to show some data from the past, for certain interval. For example, some analytics/statistics on app usage over time.

The component would behave (and look) similar to the one on Shopify Admin Analytics page:

![screen shot 2018-07-17 at 19 17 20](https://user-images.githubusercontent.com/67437/42834013-143d47f2-89f6-11e8-8130-f11cb286bbb3.jpg)

**Comment by tmlayton** [comment]
Hey @vfonic, we do have a multi-month date picker which allows range selection. Combining this with popover and some form elements would get you most of the way there. Here is a [starting point which combines a popover and a date picker ](https://codesandbox.io/s/r2mmm0x1p).

I’m going to close this issue for now, but please upvote 👍on the issue description if you feel a higher order component which included popover, data picker, and the form elements would be helpful.

**Comment by vfonic** [comment]
@tmlayton oh wow! I didn't know you could achieve this with current `DatePicker` component.

I totally missed the full settings explained below and concluded this is not available based on the single example. Would be great if you could add this codesandbox example to the DatePicker documentation page. Thanks! <3

https://polaris.shopify.com/components/forms/date-picker

**Comment by Azim-Sabbir** [comment]
> Hey @vfonic, we do have a multi-month date picker which allows range selection. Combining this with popover and some form elements would get you most of the way there. Here is a [starting point which combines a popover and a date picker ](https://codesandbox.io/s/r2mmm0x1p).
> 
> I’m going to close this issue for now, but please upvote +1on the issue description if you feel a higher order component which included popover, data picker, and the form elements would be helpful.

please add one asap

**Comment by faridmovsumov** [comment]
@tmlayton Hey Tim, the link you shared is giving an error.

![image](https://github.com/Shopify/polaris/assets/1541412/44b91735-1a61-4ce3-86b4-7825df3c632a)

**Comment by tmlayton** [comment]
Everything you need in terms of docs, code examples, and sandboxes should be here https://polaris.shopify.com/patterns/date-picking/date-range
