### ISSUE TITLE
Embedded alert: state change causes the infinite recursion

### ISSUE THREAD

**Issue by superwhykz** [Shopify/polaris#378]
# Issue summary
I am not sure what is happening but it seems on the `state` change causes the infinite recursion. 

## Expected behavior
The embedded alert should pop up. 

## Actual behavior
<img width="313" alt="modal_issue" src="https://user-images.githubusercontent.com/19716620/42921158-5815e39c-8ae8-11e8-8457-9ca9581e7be1.png">

## Steps to reproduce the problem

From `Page` component

```
handleCreateChange() {
    switch (this.props.tab) {
      case 0:
        if (this.props.list.length === 1) {
          this.props.setDisableCreate(true);
  ...
  ...
  ...
}

...
...
...

     },
        ]}
        primaryAction={{
          content: 'Create Rule',
          onAction: () => this.handleCreateChange(),
        }}
      >
        <Alert
          title="Reached limit"
          open={
            this.props.disableCreate &&
            !this.props.isFetching
          }
          confirmContent="Close"
          onConfirm={() => this.handleCreateChange()}
        >
          <TextContainer>
            <p>
              You can only modify existing set of rules!
            </p>
          </TextContainer>
        </Alert>

```

## Specifications
- Are you using the React components? (Y/N): Yes
- Polaris version number: 2.4.0
- Browser: Chrome Version 67.0.3396.99 (Official Build) (64-bit)
- Device: MacPro
- Operating System: MacOS Sierra 10.12.6

**Comment by dleroux** [comment]
@superwhykz Thanks for letting us know! I'll open an issue internally and keep you posted.

**Comment by superwhykz** [comment]
@dleroux thanks so much!

**Comment by dleroux** [comment]
@superwhykz turns out that for security reasons we can only accept strings in the Alert. Remove the `TextContainer` and the `<p>` and it will be fine. Changing our internal issue to make that more clear in the future. Thanks for reporting this. I'll close this now.

**Comment by superwhykz** [comment]
Ehh ..... thanks so much for quick turn around!
