### ISSUE TITLE
Adding complete support for RTL in Polaris components

### ISSUE THREAD

**Issue by AriaShishegaran** [Shopify/polaris#3795]
## RTL Support to enable right to left languages to also develop apon these components and expand the support for the community further

As i've investigated there is some basic support for this feature via utilizing the CSS rtl features but some components like buttons or drawer menus exhibit faulty behavior such as text overflowing ontop of drawer (down arrow), much more...

## I believe this is a crucial feature to allow more people with more language diversity to use the platform which converts to even more contributors and expantion when people from these countries can use and find bugs as well. plus, it would be the key gateway to allow shopify itself to support new countries in its Account Lnaguage section which currently only supports a handful of languages and most of those are still in Beta.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by cerpinn** [comment]
It'd be great if this was supported. But until then, check this out: https://github.com/alitnk/polaris-react-rtl

**Comment by yurm04** [comment]
Thanks for the request, @AriaShishegaran . We’re not actively working on this right now, but we keep an eye on all feature requests. If you're able to, it would be great to learn more about the specific bugs you've encountered with RTL support in Polaris. This would help us target where we can prioritize a solution. Please feel free to open up new issues and tagging them with the `bug` label.

I’ll close this issue for now, but we encourage everyone who wants this feature to add a 👍 to the original issue report. We’ll take your collective interest into account when we look at what to work on next. 💜
