### ISSUE TITLE
Add sizing options for DropZone

### ISSUE THREAD

**Issue by jejacks0n** [Shopify/polaris#382]
# Feature request summary

It would be nice if DropZone was more style-able or provided the ability to override the size.

## Rationale

I would like to put a DropZone within a form, and have its height be that of a standard form text input, so it could be grouped using FormLayout.Group, for instance.

The benefit would be more flexible options for the DropZone, which currently only rerenders new content on size changes. It would be better if this was purely CSS so the render method could be cleaned up, and it could be more flexible with styling.

**Comment by ry5n** [comment]
@jejacks0n Thanks for logging this, it’s extra helpful, since we’re running into some sizing-related limitations within Shopify. I’m gathering use cases and we’ll look at what can be done to make this more flexible.

**Comment by ry5n** [comment]
We’ve discussed this but we haven’t landed on how flexible this should be, or what the changes/additions to the API should be. It’s clear it needs some more exploration, and we’ve resolved to come back to it as soon as possible. In the meantime, I’ll close this as we do for feature requests that we’re not able to work on right now.

If you get the chance, can you post an image or screenshot of your use case? It will help our designers to understand how the dropzone should adapt.
