### ISSUE TITLE
Survey component needed

### ISSUE THREAD

**Issue by superwhykz** [Shopify/polaris#384]
# Feature request summary

It would be nice to have a survey component.  

Something similar:
https://stackblitz.com/edit/surveyjs-react-stackoverflow45544026

## Rationale
It is hard to work with customers. Out of 10 customers only may be 1 will respond.  It would be nice to add a list of features that you think might work and get some responses. That gives a bit of understanding of what customers need in their day to day work.

**Comment by tmlayton** [comment]
Thanks for the request, @superwhykz. We’re not actively working on this right now, but we treat all feature requests as part of our backlog.

I’ll close this issue for now, but **we encourage everyone who wants this feature to add a 👍** to the original issue report. We’ll take your collective interest into account when we look at what to work on next.

💜
