### ISSUE TITLE
Tabbing out of Popover can give focus on disabled item if it has tabindex

### ISSUE THREAD

**Issue by henryyi** [Shopify/polaris#3866]
## Issue summary

When the Popover closes by keypress (escape or tab until out) it will try to focus on the next focusable item which does not include disabled elements. However if the disable element also has a tabindex then it will try to focus on it but fails.
See this example: https://codesandbox.io/s/magical-moore-4o36qu?file=/index.js

## Expected behavior

Tabbing out of Popover should move to next active focusable element ignoring disabled ones

## Actual behavior

Tabbing out of Popover tries to focus on next element even if it is disabled if it as a tabindex

## Steps to reproduce the problem

1. Go to https://codesandbox.io/s/magical-moore-4o36qu?file=/index.js
1. Open the Popover
1. Press Tab key until Popover closes
1. Focus disappears (goes to body)

## Reduced test case

https://codesandbox.io/s/magical-moore-4o36qu?file=/index.js

## Specifications

- Are you using the React components? (Y):
- Polaris version number: 5.13.1
- Browser: Chrome
- Device: MacBook
- Operating System: MacOS

**Comment by yurm04** [comment]
@henryyi is this issue still relevant? The sandbox link you provided no longer works. If this is still a bug, does this [draft PR](https://github.com/Shopify/polaris/pull/4039) look like a relevant fix?

**Comment by henryyi** [comment]
> @henryyi is this issue still relevant? The sandbox link you provided no longer works. If this is still a bug, does this [draft PR](https://github.com/Shopify/polaris/pull/4039) look like a relevant fix?

@yurm04 looks like the PR should address it since it will avoid disabled elements.

**Comment by henryyi** [comment]
Bug can still be reproduced; I updated the sandbox in the description
