### ISSUE TITLE
Missing Component Request - Reorder / Sortable list

### ISSUE THREAD

**Issue by ccw0505** [Shopify/polaris#388]
# Feature request summary

Wonder if Shopify plans to launch component for reorder / sortable list. Similar experience can be found at `Shopify admin > Product > Collections`?

If there is no such plan, can recommend what's the best approach?

## Rationale

For building B2B app, we often come across requirement to prfioritize a list of items.

## Reference 1 - Shopify admin
<img width="401" alt="screen shot 2018-08-01 at 7 16 36 pm" src="https://user-images.githubusercontent.com/1337797/43518701-7034f102-95bf-11e8-8390-56440ffbb973.png">

**Comment by chloerice** [comment]
Hey @ccw0505, thanks for the feature request! We treat all feature requests as part of our backlog, so I’ll close this issue for now. 

We encourage everyone who wants this component to add a 👍 to the issue description. Your collective need is always considered when plotting out what's next on our roadmap.

**Comment by nuotsu** [comment]
It's been over 5 years... any updates??
