### ISSUE TITLE
ActionList item's onAction submits ancestor form

### ISSUE THREAD

**Issue by andrewpye** [Shopify/polaris#391]
# Issue summary
If an `ActionList` component is used inside a `form` element, selecting any action from the list triggers the form's `onSubmit` handler:

![action-list-bug](https://user-images.githubusercontent.com/5737342/43570028-fbfcb350-9641-11e8-910b-550fde635d75.gif)

Source for the above GIF is [here](https://codesandbox.io/s/w0lyyyn978).

## Expected behavior
Clicking an item should not trigger an ancestor form's `onSubmit` handler.

## Actual behavior
Clicking an item triggers an ancestor form's `onSubmit` handler.

## Steps to reproduce the problem
Demo code [here](https://codesandbox.io/s/w0lyyyn978).

Problem outline:
1. Wrap an `ActionList` in a `form` element with an `onSubmit` handler.
2. Click an item on the `ActionList`.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 2.5.0
- Browser: Chrome Version 67.0.3396.99 (Official Build) (64-bit)
- Device: MacBook Pro
- Operating System: macOS Sierra Version 10.12.6 (16G29)

**Comment by tmlayton** [comment]
Thanks for the issue @andrewpye. I’ll open an internal issue for this.

**Comment by ry5n** [comment]
We’ve fixed this internally and it will be available in the next release

**Comment by tmlayton** [comment]
This is now fixed in 2.6.1
