### ISSUE TITLE
Resource List loading prop

### ISSUE THREAD

**Issue by Garrett-Smith-iq** [Shopify/polaris#393]
# Feature request summary

Add a loading prop to the `ResourceList` component.

## Rationale

It would be nice to give feedback to a user when fetching data. This is already done elsewhere in Shopify but I can't seem to do it with the Polaris components.

![image](https://user-images.githubusercontent.com/20046171/43595849-51bd6798-9643-11e8-96a5-e0bc926b62a6.png)

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 We _are_ accepting issue reports and feature requests<br />
🌟 Feature requests that we can’t get to right away will be closed. However, we track all requests and will use it to set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by tmlayton** [comment]
@Garrett-Smith-iq, thanks for this issue. You’re right, we have a loading prop as part of our Rails implementation which is internal use only.

Usually, we close feature requests and have people upvote on them, but in this case I _think_ it makes sense to add this prop so I’m going to leave this issue open for now. I’m also going to open an internal issue for discussion.

**Comment by menos-inc** [comment]
yes please

**Comment by ry5n** [comment]
We’re currently implementing this, it should be available shortly.

**Comment by ry5n** [comment]
We just merged this in our dev repo and it will be available in the next release.

**Comment by menos-inc** [comment]
Hello, is this released yet? Just checked with v2.8.0 - looks like no loading state yet. Thanks!

**Comment by solonaarmstrong** [comment]
Hi @menos-inc. We apologize, the loading prop didn't make it into this latest release. It should be in the next one. Sorry for the delay.

**Comment by menos-inc** [comment]
Appreciate the update!

**Comment by solonaarmstrong** [comment]
This will be in the 2.9.0 release.

**Comment by menos-inc** [comment]
working as expected. thank you!!!

**Comment by cgenevier** [comment]
@solonaarmstrong @ry5n I'm super excited about this feature. That said, it appears to be working when there are items in the list, but not when the ResourceList is empty (ex: items={[]}). Is this expected behavior? I was hoping that it could also show as loading when the initial items are being retrieved, not just (for example) during a search. Is this expected behavior or should I open a new Issue ? Thanks!

**Comment by solonaarmstrong** [comment]
@cgenevier The loading prop places a spinner over the list of items, so if there are no items, there is nowhere to place the spinner. What would your expectation be for loading when there are no items rendered?

**Comment by solonaarmstrong** [comment]
@cgenevier Thank you. I will open a discussion with the team and get back to you.

**Comment by solonaarmstrong** [comment]
This is fixed in our next release, which should be sometime next week.

**Comment by cgenevier** [comment]
@solonaarmstrong Amazing, thank you so much!

**Comment by cgenevier** [comment]
@solonaarmstrong Was the loading spinner over the empty state ever added? Thanks!
