### ISSUE TITLE
Embedded modal loading={true} does not work

### ISSUE THREAD

**Issue by menos-inc** [Shopify/polaris#395]
# Issue summary

Embedded modal **loading={true}** does not work

## Expected behavior

According to the [docs](https://polaris.shopify.com/components/embedded/embedded-modal):
"loading - boolean
Replaces modal content with a spinner while a background action is being performed (Modal use only)

## Actual behavior

Nothing

## Steps to reproduce the problem

1. Create embedded modal
2. Set loading={true}
3. Open the modal

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 2.5.0
- Browser: Chrome Version 68.0.3440.84 (Official Build) (64-bit)
- Device: Lenovo Yoga 730
- Operating System: Windows 10 Home

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 We _are_ accepting issue reports and feature requests<br />
🌟 Feature requests that we can’t get to right away will be closed. However, we track all requests and will use it to set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by AndrewMusgrave** [comment]
Hi @menos-inc sorry for the confusion. The loading prop does not function within an embedded app. I'm going to close the issue but feel free to reopen it if you have any more questions.

**Comment by menos-inc** [comment]
Hi Andrew, thanks for the reply. The docs for EmbeddedModal list loading as a usable state.

Can we make this a feature request?
