### ISSUE TITLE
How to test components in isolation?

### ISSUE THREAD

**Issue by jjt** [Shopify/polaris#396]
# Issue Summary
I have components split out into separate files that have a render method that look something like 

```
import { Page } from '@shopify/polaris';

export default const HomePage = () => (
  <Page>
    <MyComponent/>
  </Page>
)
```

I'd like to be able to test them using react-testing-library that mounts the component into a DOM:

```
import { render } from 'react-testing-library';
import HomePage from './HomePage';

it("renders without crashing", () => {
  render(<HomePage />);
})
```

## Expected behavior
That my test passes

## Actual behavior
Test fails with message
```
 The <AppProvider> component is required as of v2.0 of Polaris React. See
                https://polaris.shopify.com/components/structure/app-provider for implementation
                instructions.
```
## Steps to reproduce the problem

1. Try to render a `<Page>` element without a surrounding `<AppProvider>` component using react-testing-library

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 2.5.0
- Browser: N/A
- Device: N/A
- Operating System: MacOS 10.14 beta (18A347e)

**Comment by chloerice** [comment]
Hey @jjt, you'll need the app provider context for your tests. The best way to do this without wrapping your tests with the app provider component is to copy over the test `mountWithAppProvider` test utility used in [the create-react-app example](import {mountWithAppProvider} from './utils/enzyme';).

**Comment by lemonmade** [comment]
If you are using react-testing-library, you will need to manually wrap your component under test with the provider, as it does not, AFAIK, support passing down arbitrary context as enzyme does.

An alternative approach that may be more desirable is to stub out the component in question (using something like jest.mock) to just return its children; that way the context problem is circumvented entirely. We use this in Shopify even though we have Enzyme in cases where rendering the component itself is unnecessarily wasteful/ expensive, and where we are testing a component that just composes the one we are mocking our (as you are here).

**Comment by jjt** [comment]
Thanks for the recommendations and example @chloerice and @lemonmade!

Is there documentation for which Polaris components need the context from AppProvider and which don't? I could always trawl through source too I guess, but documentation is nice 🙃

**Comment by chloerice** [comment]
Whichever solution you choose will need to be used in any test that covers or wraps a Polaris component, as all components require app provider context.

**Comment by jjt** [comment]
So even something like [TextContainer](https://polaris.shopify.com/components/titles-and-text/text-container), _relies_ on context from AppProvider? That seems like an odd restriction for what ostensibly should be a presentational component.

**Comment by jjt** [comment]
Like, is there some magic happening here behind the scenes, or am I missing something? Looking at [the source for TextContainer](https://github.com/Shopify/polaris/blob/757af96d4bd440a83288e54050f1dda10a731fd1/src/components/TextContainer/TextContainer.tsx) I can't see any reference to context.

**Comment by lemonmade** [comment]
I think you are safer just assuming all Polaris components need the context. Though they might not technically by their current implementation, we require an `AppProvider` around all Polaris components partially to afford us the flexibility to move things in to that provider as needed, which we would not consider to be a breaking change (but would break your tests, if you were trying to scope the provider only to Polaris components that actually need the context currently).

**Comment by pasim** [comment]
@chloerice Kudos 👍. Your comment inspired me to find a working solution.
The example you provided was outdated, shower I came across the migration and upgrade suggestions - https://github.com/Shopify/polaris-react/blob/main/documentation/guides/migrating-from-v3-to-v4.md.
