### ISSUE TITLE
Is Shopify Polaris indented only for Shopify apps, or is it a general UI libray?

### ISSUE THREAD

**Issue by jimbojetlag** [Shopify/polaris#397]
I was wondering if Polaris is a general UI library comparable to Twitter Bootstrap and Google Material Design. Can it be used to build general responsive web applications not related to Shopify apps?

**Comment by BPScott** [comment]
Hi @jimbojetlag, thanks for asking!

The focus of Polaris is on the Shopify ecosystem. Usage of Polaris outside of Shopify apps is allowed (as per the MIT license) but not supported.

This means that you're free to use Polaris to build apps not related to Shopify but be aware that requests unrelated to the Shopify ecosystem will not be considered. For instance the color palette and font-sizes are based upon the Shopify brand colors and sizings and we will not add the ability to customize them.
