### ISSUE TITLE
Clarify usage of Frame vs. Page

### ISSUE THREAD

**Issue by aaronadamsCA** [Shopify/polaris#3981]
## Feature request summary

I'd like the docs to clarify whether `Frame` should wrap the app in all cases, or if it should only be used to wrap certain elements like `Loading` or when using one of its props like `topBar` or `navigation`.

I'd also like the docs to clarify which elements should vs. should not be wrapped by `Page`.

## Rationale

One of the most common places I keep getting bit in Polaris is when I have the wrong components wrapping (or not wrapping) other components. `EmptyState` looks terrible if you don't wrap it with `Page` (and now `Card`, as it turns out). But `Loading` should only be wrapped with a `Frame` and not a `Page`. And so on.

I've gradually figured it out for myself, but clearer docs here would certainly make things easier.

(In the long run it'd be even better if you used TypeScript to flag an invalid hierarchy, but for now I'd take some light reading instead!)

**Comment by PierreTurnbull** [comment]
This page of documentation have been quite useful for me to understand Frame and Page : https://polaris.shopify.com/foundations/patterns/page-layouts

**Comment by aaronadamsCA** [comment]
@PierreTurnbull Thank you! That page definitely answers some of my questions.

I do think it would be good for many of the other pages to cross-reference this page.
