### ISSUE TITLE
'Resource List (**legacy**)' in Figma vs Official documentation

### ISSUE THREAD

**Issue by petebof** [Shopify/polaris#3982]
At Figma's [Polaris for Admin: Components](https://www.figma.com/community/file/930504625460155381)   the Resource List component is titled as **Legacy**. This does not agree with the [official documentation](https://polaris.shopify.com/components/lists-and-tables/resource-list#navigation). In addition the data table documentation recommends "Not to be used for an actionable list of items that link to details pages. For this functionality, use the resource list component.". 

Should we stop using the resource list comp? What is the alternative? A data table?

**Comment by martenbjork** [comment]
Closing the issue for now. The `Resource List` component is not marked as Legacy in the latest version of the Figma UI Kit. The component is not deprecated.
