### ISSUE TITLE
Rendering a component that returns a ResourceItem should not give a warning.

### ISSUE THREAD

**Issue by martinffx** [Shopify/polaris#3983]
## Issue summary

Rendering a component that returns a `ResourceItem` in the `renderItem` function of  a `ResourceList`, should not give a warning.

 If each `ResourceItem` needs to manage state, it is valid to wrap the `ResourceItem` in a function component to add `useState` to manage that state. This all works, except you get tons of warning errors making the console logs unreadable.

## Expected behavior

Rendering a component that returns a `ResourceItem` in the `renderItem` function of  a `ResourceList`, should not give a warning or should be suppressable

## Actual behavior

See codepen, this is logged in the console for each item.

`<ResourceList /> renderItem function should return a <ResourceItem />. `

## Reduced test case

https://codesandbox.io/s/fervent-haibt-6ndf4?file=/App.js

## Specifications

```bash
System:
    OS: macOS 11.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 557.75 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /var/folders/cw/_r242fhd3rx137z9grp8bnjc0000gn/T/fnm_multishell_2601_1612882054784/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.14.10 - /var/folders/cw/_r242fhd3rx137z9grp8bnjc0000gn/T/fnm_multishell_2601_1612882054784/bin/npm
  Browsers:
    Brave Browser: 88.1.19.92
  npmPackages:
    @shopify/polaris: ^5.10.0 => 5.14.0 
    react: ^16.12.0 => 16.13.1 
    react-dom: ^16.12.0 => 16.13.1 
```

**Comment by amireynoso** [comment]
Experiencing the same on my end. We tend to extract individual resource items into their own components for readability and easier testing.

**Comment by kyledurand** [comment]
Hey all, the idea here is that the resource list renders an unordered list in which the resource list renders list items. They need to be tied very close together to render valid HTML. I think there was also a secondary reason we needed direct control for `last-of-type` `border-radius` when we shipped the new design language.

Is it possible to separate ResourceItem from the component you want to test? I've made a quick sandbox to [show what I mean](https://codesandbox.io/s/nifty-snyder-8dvei?file=/App.js)

**Comment by amireynoso** [comment]
Hey @kyledurand, thanks for looking into this. 

The approach I'm using outputs the same HTML as the one you proposed ([see codesandbox](https://codesandbox.io/s/green-wood-uo20s?file=/App.js)) and it's visually equivalent. Unless I'm missing something...? 🤔 

We could totally do what you propose, but I think it defeats the purpose of separation of concerns, especially when we try to render complex lists.

**Comment by xiaoxipang** [comment]
I have the exactly same problem and PR commit https://github.com/Shopify/services-db/commit/ab2e791d93c2e9952c7ddde0181811267ea64a9e

**Comment by Nedomas** [comment]
This is still a valid issue. It should not be closed.
