### ISSUE TITLE
Cannot use git repo as a dependency

### ISSUE THREAD

**Issue by GhostApps** [Shopify/polaris#3986]
## Issue summary

In npm you can add a git repository and branch as a dependency i.e. `npm install Shopify/polaris-react#main` as a way of using the latest before a release. However this doesn't work, I believe due to a lack of `prepare` statement in `package.json`

## Expected behavior

`npm install Shopify/polaris-react#main` should allow me to use the latest commit in polaris-react main branch

## Actual behavior

npm complains polaris isn't installed

## Steps to reproduce the problem

1. `npm install Shopify/polaris-react#main`

**Comment by GhostApps** [comment]
@AndrewMusgrave

**Comment by AndrewMusgrave** [comment]
Unfortunately, it's not something that's currently supported. However, it would be very useful. @BPScott  was this something you ever looked into when you were on Polaris?

**Comment by BPScott** [comment]
It'd certainly make testing easier  - no need to mess with cutting beta releases to check consuming projects.

@GhostApps is right - we'd want a [prepare step](https://docs.npmjs.com/cli/v6/using-npm/scripts#life-cycle-scripts) that triggers when you install via git. Reading those docs it might be straightforward as replacing [`prepublishonly`](https://github.com/Shopify/polaris-react/blob/a040dea90c5622fce87f8df0bf78677c4871ae10/package.json#L68) with `prepare`.
