### ISSUE TITLE
Allow Button children to accept React.ReactNode

### ISSUE THREAD

**Issue by jessie-JNing** [Shopify/polaris#3992]
## Feature request summary

We are building a plain button, who would be displayed at a polaris Badge, however, the button children does not accept `React.ReactNode` type.

## Rationale

The button we are building is like below:
```typescript
const status =(<Badge status="success">Passing</Badge>);
const activator = (
    <Button plain onClick={togglePopoverActive} disclosure>
      {status}
    </Button>
  );
```
The react typecheck complains `{status}`: `error TS2322: Type 'Element' is not assignable to type 'string | string[] | undefined'`, this is because https://github.com/Shopify/polaris-react/blame/main/src/components/Button/Button.tsx#L25

We think users should be given more flexibility on building their buttons, give more style and etc. 

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by yurm04** [comment]
Thanks for this request, @jessie-JNing! We recently opened [a discussion](https://github.com/Shopify/polaris/discussions/7005) on this topic, but more broadly across all of our components. It would be great if you could add your thoughts and use case in that discussion. It would really help us as we begin reworking some of our components to make them more flexible.

I'm going to close this comment, but please head over to the discussion to share your opinion 🙏

**Comment by claudioc** [comment]
@yurm04 FYI I think I opened the same exact issue here https://github.com/Shopify/polaris/issues/6941
