### ISSUE TITLE
Documentation Suggestion: Color Usage

### ISSUE THREAD

**Issue by fighella** [Shopify/polaris#40]
# Issue summary

It is not entirely clear the *colored circles* in the [Color Usage](https://polaris.shopify.com/visuals/colors#section-color-usage) section of the docs are clickable.

## Expected behavior

Perhaps the circles should change color or a more obvious "link" is used.

**Comment by ry5n** [comment]
Thanks for logging this @fighella. We‘ve logged this and we’ll be looking at a couple ways to make this interaction more obvious in a future release of the styleguide.

**Comment by ry5n** [comment]
We’ve made this a little better by adding an underline to the color blocks. In the future we’ll look at additional improvements to me this clearer.
