### ISSUE TITLE
Where is the dashboards Layout

### ISSUE THREAD

**Issue by zheren2018** [Shopify/polaris#400]
I can not find the layout which displays in Shopify->Dashboards

We are preparing to build an analytics page for our users through Polaris. The page will be ugly if we use the current layout from Shopify, coz there are many cards in our design.

The layout which we want is just like this.
![image](https://user-images.githubusercontent.com/39551669/44070773-4a896d86-9fb8-11e8-9565-a482ac7b22e5.png)

Where can i find this layout

## Steps to reproduce the problem

1.
1.
1.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 We _are_ accepting issue reports and feature requests<br />
🌟 Feature requests that we can’t get to right away will be closed. However, we track all requests and will use it to set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by chloerice** [comment]
Hi @zheren2018, the reports dashboard of the Shopify admin uses a custom flex box layout on large screens that collapses to a single column when the viewport is below 1200px. There is no grid layout component, but a multi-column layout can be achieved by using a layout with multiple `secondary` layout sections. 

```jsx
import React, {Component} from 'react';
import {
  Page,
  AppProvider,
  Layout,
  Card,
  DescriptionList,
} from '@shopify/polaris';

export default class Playground extends Component {
  render() {
    const outerColumnContent = (
      <Card title="Tags" sectioned>
        <DescriptionList
          items={[
            {
              term: 'Logistics',
              description:
                'The management of products or other resources as they travel between a point of origin and a destination.',
            },
            {
              term: 'Sole proprietorship',
              description:
                'A business structure where a single individual both owns and runs the company.',
            },
          ]}
        />
      </Card>
    );

    const innerColumnContent = (
      <Card title="Tags" sectioned>
        <p>Add tags to your order.</p>
        <p>Add tags to your order.</p>
        <p>Add tags to your order.</p>
        <p>Add tags to your order.</p>
        <p>Add tags to your order.</p>
        <p>Add tags to your order.</p>
      </Card>
    );
    return (
      <AppProvider>
        <Page fullWidth title="Playground">
          <Layout>
            <Layout.Section secondary>
              {outerColumnContent}
              {outerColumnContent}
              {outerColumnContent}
            </Layout.Section>
            <Layout.Section secondary>
              {innerColumnContent}
              {innerColumnContent}
              {innerColumnContent}
              {innerColumnContent}
              {innerColumnContent}
            </Layout.Section>
            <Layout.Section secondary>
              {outerColumnContent}
              {outerColumnContent}
              {outerColumnContent}
            </Layout.Section>
          </Layout>
        </Page>
      </AppProvider>
    );
  }
}
```

**Comment by gshaw** [comment]
@chloerice any chance of providing a link to a JSFiddle that shows the markup in that example page?

**Comment by chloerice** [comment]
Hey @gshaw 👋, [here's a CodeSandbox](https://codesandbox.io/s/6z7r480p9r) to play with!
