### ISSUE TITLE
Popover polaris component when used with Action List component displays extra height.

### ISSUE THREAD

**Issue by GuptaAman08** [Shopify/polaris#4002]
## Issue summary
I am using **Popover** Polaris component in combination with the **Action List** component in one of my web applications.  I have observed that Popover component induces an extra height of **56px**  at the end of the last item in the action list. I find no way to fix this. It will be helpful a lot if somebody can help me in resolving this issue.

<img width="509" alt="Screenshot 2021-02-13 at 6 34 30 PM" src="https://user-images.githubusercontent.com/31820923/107850677-2ac27180-6e2a-11eb-83a8-669e846881b1.png">

Screen Shot for proof of the extra **56px height**  is below

<img width="509" alt="Screenshot 2021-02-13 at 6 25 29 PM" src="https://user-images.githubusercontent.com/31820923/107850557-3f523a00-6e29-11eb-97a7-d477627911d7.png">

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number:
- Browser: Chrome
- Device: Mac
- Operating System:

**Comment by skrabakl-shopify** [comment]
Hi @GuptaAman08 I wasn't able to reproduce this, could you share an example code for this case on Codepen?

**Comment by GuptaAman08** [comment]
Hi @happykoder,

The above Issue is arising whenever I change from landscape to portrait inside the browser (**in codesandbpx.io**). But, for me above issue happens right from the very first time when my component loads. The structure of my code is exactly similar to the below code snippet.

`
import React, { useCallback, useState } from "react";
import { Popover, ActionList, Button, Page, Card, Stack } from "@shopify/polaris";

export default function ActionListInPopoverExample() {
  const [active, setActive] = useState(false);

  const toggleActive = useCallback(() => setActive((active) => !active), []);

  const handleImportedAction = useCallback(
    () => console.log("Imported action"),
    []
  );

  const handleExportedAction = useCallback(
    () => console.log("Exported action"),
    []
  );

  const activator = (
    <Button onClick={toggleActive} disclosure>
      More actions
    </Button>
  );

  const handleDataRefetch = () => console.log("Fetching.......");

  return (
    <Page
      title="Orders"
      primaryAction={{ content: "Refresh", onAction: handleDataRefetch }}
      fullWidth
    >
      <Card>
        <Card.Section>
          <Stack>
            <Stack.Item fill>
              Polaris Filter 
            </Stack.Item>
            <Stack.Item>
              Polaris Select  
            </Stack.Item>
            <Stack.Item>
              <Popover active={active} activator={activator} onClose={toggleActive}>
                <ActionList
                  items={[
                    {
                      content: "Import file",
                      onAction: handleImportedAction
                    },
                    {
                      content: "Export file",
                      onAction: handleExportedAction
                    }
                  ]}
                />
              </Popover>
            </Stack.Item>
          </Stack>
        </Card.Section>
      </Card>
    </Page>
  );
}
`
Also, for your reference, I have attached a codesandbox.io code output gif. 
It would really helpful if you can help me in pointing out exactly what is going wrong and how can I fix it.

Output of above code snipped as Screen Recording is attached below


https://user-images.githubusercontent.com/31820923/108518788-f994e600-72ee-11eb-8652-c6c3b6277990.mov

**Comment by h0wardch3ng** [comment]
https://github.com/Shopify/polaris-react/tree/main/src/components/Select

![image](https://user-images.githubusercontent.com/2175497/108842694-a08dc080-7614-11eb-96c5-01691f7abcb9.png)

Two select style, which one is v6.0 standard style?

**Comment by skrabakl-shopify** [comment]
@GuptaAman08 Could you please provide the link to the codesandbox - as the snippet does not reproduce the issue.

**Comment by skrabakl-shopify** [comment]
Hi @h0wardch3ng, the bottom select is Polaris select, the top one is style guide one to select the examples. If you have any further issues feel free to open a separate Issue [here](https://github.com/Shopify/polaris-react/issues/new/choose)

**Comment by GuptaAman08** [comment]
@happykoder you just need to open the output of codesandbox, with the code I have shared earlier, in a new tab. After which, just change to mobile view. After which, change from landscape to portrait and vice-versa. You will be able to produce it
