### ISSUE TITLE
Invalid package.json entry point for @shopify/react-utilities

### ISSUE THREAD

**Issue by kj** [Shopify/polaris#401]
# Issue summary

Polaris won't build correctly with [FuseBox](https://fuse-box.org) because the 'main' field in @shopify/react-utilities/package.json is incorrect. It is set to 'lib/index.js', when it should be set to 'index.js' (there is no 'lib' directory, and I've verified that this change causes the build to succeed). This is true for the version of @shopify/react-utilities which @shopify/polaris depends on, and is still the case in the latest version. I would submit a pull request, but it looks like the repo has been taken down for some reason.

## Expected behavior

Polaris builds with FuseBox.

## Actual behavior

Everything builds correctly, except @shopify/react-utilities is not resolved due to an incorrect 'main' field in package.json.

## The fix

In @shopify/react-utilities package.json, change:

```
- "main": "lib/index.js",
+ "main": "index.js",
```

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 2.5.0
- Browser: Chromium 68
- Device: 
- Operating System: Arch Linux

**Comment by ry5n** [comment]
Thanks for flagging this. I’ve opened an issue on the repo, which is private. For that reason I’ll leave this open until we can resolve it there.

**Comment by ry5n** [comment]
We’ve merged a fix for this and it’ll be available in the next release 🎉

**Comment by BPScott** [comment]
Removing the Fix in progress label as this is now releases
