### ISSUE TITLE
Make docs more obvious that Polaris `onChange` and React's `onChange` handlers have different signatures

### ISSUE THREAD

**Issue by jjt** [Shopify/polaris#402]
I'm implementing a form with [Formik](https://github.com/jaredpalmer/formik) and Polaris components. Formik's [handleChange](https://github.com/jaredpalmer/formik#handlechange-e-reactchangeeventany--void) expects to receive a React event and uses the event target to determine which values to change.

Seeing the Polaris property `onChange`, I just assumed that the function signatures would be the same and I inferred that this should work: `<TextField onChange={formik.handleChange}/>`. but due to the signature mismatch it does not.

I burned a good hour or two trying to figure out why this wasn't working, eventually writing my own TextField component using bare Polaris-styled HTML elements before stumbling upon the mismatch in devtools when working on a custom RadioButton component.

So my suggestion is making it more obvious in the docs that the function signatures differ. If it is obvious and I should have just RTFM more closely, then that's my bad 🙂

**Comment by jjt** [comment]
Yeah, probably on me, looking at it again
![image](https://user-images.githubusercontent.com/399469/44096469-2e3a20ee-9f90-11e8-8b1b-107211e6311a.png)

I'll close this out.

**Comment by faurehu** [comment]
Hey @jjt, I'd love to learn more about how to use Formik with Polaris. Could you tell me more about the custom component you've built? If I understand, it's not a wrapper around polaris inputs, but rather, a polaris input alike built from the ground up?

Thanks.

**Comment by jjt** [comment]
Hey @faurehu, I've mostly wrapped Polaris components with Formik components, and called [`setFieldValue`](https://jaredpalmer.com/formik/docs/api/formik#setfieldvalue-field-string-value-any-shouldvalidate-boolean-void) manually.

**Comment by faurehu** [comment]
Thanks, that's the same solution I found in another thread.
