### ISSUE TITLE
Add space like Tailwind CSS

### ISSUE THREAD

**Issue by webiroha** [Shopify/polaris#4023]
Hello, I am new to Polaris.

## Feature request summary

Thought it might be good if there is a system that we can add space systematically like a Tailwind.

## Rationale

Found a document about spacing.
https://polaris.shopify.com/design/spacing#section-spacing-in-code

Learnt there are two ways to add it.
- Using stylesheets
- Using utility components provided by Polaris React

My understanding is that the second way is limited for now.
It might make our tasks faster.

**Comment by pierreneter** [comment]
You can use https://polaris.shopify.com/components/structure/stack

**Comment by martenbjork** [comment]
You can now use spacing tokens in your CSS file as well: https://polaris.shopify.com/tokens/spacing
