### ISSUE TITLE
footer banner

### ISSUE THREAD

**Issue by huiyuhuihui** [Shopify/polaris#406]
# Issue summary
I wonder know how to achieve footer banner, did Polaris has same component? cause for now, the component of 'Banner' need to put at the top of that page, if i need a footer banner, how to achieve it? is't any chance that you guys will launch footer banner component? 

![image](https://user-images.githubusercontent.com/40648446/44455530-e545d480-a630-11e8-839c-07caa565f4fb.png)

## Steps to reproduce the problem

1.
1.
1.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 We _are_ accepting issue reports and feature requests<br />
🌟 Feature requests that we can’t get to right away will be closed. However, we track all requests and will use it to set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by danrosenthal** [comment]
Duplicate of https://github.com/Shopify/polaris/issues/407
