### ISSUE TITLE
Datatable wrongly says "0 column" when using voiceover tool

### ISSUE THREAD

**Issue by mahmoudmoravej** [Shopify/polaris#4077]
## Issue summary

When using voiceover tool with **arrow keys** (i.e. VO button + arrow keys), it wrongly says "0 columns" when navigating from "column scroller panel" to the table. The reverse navigation is ok. 
Check the following video for more details.
https://screenshot.click/23-40-62bns-0bu69.mp4

## Expected behavior

Says the correct columns count.

## Steps to reproduce the problem

- Turn on your Voice Over tool in Macbook
- Open your chrome
- Goto the Polaris website and open nthe "Data table" component
- Make the screen small to see the column scroller panel on top of the table
- use the VO + arrows to see the error

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: latest on the website
- Browser: Chrome
- Device: Macbook
- Operating System: MacOs

**Comment by metamoni** [comment]
Looks like this issue has been fixed 🙂

https://user-images.githubusercontent.com/22390758/134815911-5d10ef90-5c97-4fec-9cfb-7dc35692e9c8.mov
