### ISSUE TITLE
IndexTable: colSpan, rowSpan support

### ISSUE THREAD

**Issue by ViliamKopecky** [Shopify/polaris#4083]
## Feature request summary

Support `colSpan` and `rowSpan` on table cells for multi-row item data to end with result like this:

<img width="1608" alt="Screenshot 2021-03-24 at 17 11 03" src="https://user-images.githubusercontent.com/316435/112343981-eeedb800-8cc3-11eb-9308-a4429231aaa2.png">

## Rationale

If would provide better possibilities to show complex data.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by yurm04** [comment]
👋 Thanks @ViliamKopecky for this request. I closed the accompanying PR since the branch has gone stale. This isn't something the team can prioritize right now, but please feel free to open up a new PR if this is still something you'd like to contribute
