### ISSUE TITLE
[IndexTable] Example of large list with react virtual or other library

### ISSUE THREAD

**Issue by GhostApps** [Shopify/polaris#4087]
I'm trying to get IndexTable to work with a large amount of data, I'm trying to use react-virtual but have reached the limit of my knowledge of React and am stuck.
Could someone tell me if I'm going down the right track and maybe show me a working example of IndexTable with react-virtual or a different method of loading a large amount of data.

Hoping @AndrewMusgrave or @dfmcphee might be able to help

Thanks

**Comment by hitesh-kc** [comment]
Hello @GhostApps  did you find any solution or another method to render large data
