### ISSUE TITLE
Icon attribute of pages seems to have no effect

### ISSUE THREAD

**Issue by shawnhind** [Shopify/polaris#409]
# Issue summary

## Expected behavior
When adding a url to a CDN to the icon attribute of the Page component the icon should show somewhere in the page header.

## Actual behavior
No icon is shown in the page header, icon attribute doesn't appear to change anything.

## Steps to reproduce the problem

1. Create a page component
1. Define the required fields along with an icon attribute which is a URL to a CDN with an icon image
1. Load page and view header

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: Stable
- Browser: "Edit in sandbox" link of polaris component.
---

**Comment by ry5n** [comment]
Just to clarify, you’re using the [`Page` component in an embedded app](https://polaris.shopify.com/components/embedded/embedded-page), and using the `icon` prop on the Page component itself, correct?

**Comment by chloerice** [comment]
@shawnhind Yes, the icon will be used in the app title bar when the app is embedded in the Shopify admin. There is no icon rendered within the page itself.

**Comment by dfmcphee** [comment]
Going to close this as it is the expected behaviour.
