### ISSUE TITLE
Could you add a double-click event for DatePicker component 

### ISSUE THREAD

**Issue by i7eo** [Shopify/polaris#4102]
When I use the DatePicker component and have `allowRange = {true}` configured, I can't select one day, I can only select a time range.
Maybe I can add a double-click event, and when I double-click on a day, it returns 
```javascript
{
    start: Sun Feb 04 2018 00:00:00 GMT+0800 (中国标准时间)
    end: Sun Feb 04 2018 24:00:00 GMT+0800 (中国标准时间)
}
```

I use the version is `"@shopify/polaris": "^5.11.0",`

**Comment by yurm04** [comment]
Thanks for the request, @i7eo . We’re not actively working on this right now, but we keep an eye on all feature requests.
I’ll close this issue for now, but we encourage everyone who wants this feature to add a 👍 to the original issue report. We’ll take your collective interest into account when we look at what to work on next. 💜
