### ISSUE TITLE
API.appBridge.httpGET - can I use a text field or does it have to be an ID

### ISSUE THREAD

**Issue by HTRomano** [Shopify/polaris#4103]
I have a xref field in our front office that's set to store text vs an ID.  Is it possible to use the appBridge to pull back the data elements from that xref table using text?  I've been able to do it when the field is an ID.

**Comment by martenbjork** [comment]
Sorry about the slow reply, @HTRomano ! This doesn't really seem to be something that the Polaris design system can help with. I think shopify.dev would be a better place to find an answer to this question.
