### ISSUE TITLE
[IndexTable] Performance: unnecessary repaints when selecting/deselecting items

### ISSUE THREAD

**Issue by kaelig** [Shopify/polaris#4105]
## Issue summary

Selecting and deselecting items in Index table unnecessarily triggers other elements to be repainted.

Similarly, hitting "clear" in the "Tagged with" dropdown triggers a lot of repaints, when it might not be necessary.

## Expected behavior

Elements that don't change don't need to be repainted.

## Actual behavior

Elements that don't change still need to be repainted.

## Steps to reproduce the problem

1. Go to https://www.chromatic.com/component?appId=5d559397bae39100201eedc1&name=All+Components%2FIndex+table&buildNumber=8708&specName=IndexTable+with+all+of+its+elements
1. Enable paint flashing in DevTools › Rendering
1. Select / deselect items

In this video, zones of the page that need to be repainted are flashing in green.

https://user-images.githubusercontent.com/85783/113917387-00d85c00-9796-11eb-88d5-658abc19710c.mov

## Reduced test case

https://www.chromatic.com/component?appId=5d559397bae39100201eedc1&name=All+Components%2FIndex+table&buildNumber=8708&specName=IndexTable+with+all+of+its+elements

## Specifications

```
  System:
    OS: macOS 11.2.3
  Browsers:
    Chrome: 89.0.4389.114
```

**Comment by Thomas-Richards-MoHC** [comment]
I believe this behaviour is closely related.

Selecting a row by clicking it causes a lot of repainting and this has the effect of making the text that you highlight disappear and reappear when you toggle selection, even though what you highlighted hasn't changed.

https://user-images.githubusercontent.com/83652444/124567868-46133500-de3c-11eb-9920-c2cd5780b8aa.mp4

For clarity: in the video when I mouseup after highlighting, the row selection immediately toggles. For the rest of the video, I'm just doing single clicks.
