### ISSUE TITLE
what is the alignment rules for the popover in the tags component?

### ISSUE THREAD

**Issue by huiyuhuihui** [Shopify/polaris#411]
# Issue summary
what is the alignment rules for the popover in the tags component?

Regarding tags component, it's centered in Polaris, but in the case of Shopify it's left aligned.

![image](https://user-images.githubusercontent.com/40648446/44761702-b8387b00-ab76-11e8-9e04-6f6145f2d6a8.png)
![image](https://user-images.githubusercontent.com/40648446/44761721-cdada500-ab76-11e8-8a02-30a3e94bc41b.png)

## Steps to reproduce the problem

1.
1.
1.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 We _are_ accepting issue reports and feature requests<br />
🌟 Feature requests that we can’t get to right away will be closed. However, we track all requests and will use it to set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by chloerice** [comment]
Hi @huiyuhuihui, The centered text alignment in the Polaris React action list is correct. The orders list view in the Shopify admin is not currently built in React, so it's still using our internal rails Polaris components. I'll create an issue there, thanks for raising this 👍.
