### ISSUE TITLE
There is no spacing between page header and content(eg. car / resource list / banner)

### ISSUE THREAD

**Issue by huiyuhuihui** [Shopify/polaris#412]
# Issue summary
Polaris seems no default spacing between page header and content
![image](https://user-images.githubusercontent.com/40648446/44909242-36e91000-ad51-11e8-97fc-0030c7171842.png)

## Steps to reproduce the problem

1.
1.
1.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 We _are_ accepting issue reports and feature requests<br />
🌟 Feature requests that we can’t get to right away will be closed. However, we track all requests and will use it to set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by dleroux** [comment]
Hi @huiyuhuihui, can you give us a little more information about this? With the latest release and react components it behaves as expected: https://codesandbox.io/s/52lpw4208n?module=App.js

**Comment by dleroux** [comment]
@huiyuhuihui, since this seems to be working properly I will close this issue. If thats not the case feel free to working code and reopen.
