### ISSUE TITLE
polaris.shopify.com TextField component example duplicates \ on re-render

### ISSUE THREAD

**Issue by runmad** [Shopify/polaris#4130]
## Issue summary

The `TextField` component's example page has a small issue where an escaped characters gets escaped more when changing any of the props on the placeholder text:

![Screen Shot 2021-04-19 at 2 08 34 PM](https://user-images.githubusercontent.com/708741/115303659-bd2c0d80-a118-11eb-88a4-90a77faac030.png)

![Screen Shot 2021-04-19 at 2 12 30 PM](https://user-images.githubusercontent.com/708741/115304047-49d6cb80-a119-11eb-9750-7e6f63003d0f.png)

## Expected behavior

The help text would stay the same.

## Actual behavior

The help text's escaped `\\` characters doubles every time you change a property. It starts out 

## Steps to reproduce the problem

1. Visit https://polaris.shopify.com/components/forms/text-field
2. Choose "Text field with help text"
3. Notice the help text: "We’ll use this address if we need to contact you about your account."
4. Change any prop
5. Help text is now: "We\u2019ll use this address if we need to contact you about your account."
6. Change the same or another prop
7. Help text is now: "We\\u2019ll use this address if we need to contact you about your account."
8. Every time you change the prop the number of backslashes `\` will double

## Reduced test case

Reproducible on https://polaris.shopify.com/components/forms/text-field

## Specifications

This is an issue with both Chrome Safari.

**Comment by martenbjork** [comment]
Closing since changing the props is currently not possible on the new site and it's unlikely that this bug will resurface once we bring back the props editor.
