### ISSUE TITLE
[PageActions] Allow a ref in ComplexAction to be forwarded to a primary/secondary button

### ISSUE THREAD

**Issue by jeromelecomte-shopify** [Shopify/polaris#4144]
## Feature request summary

Use case: When a primary or secondary action opens a Modal component, we'd like to pass a React reference of its button as the activator of the Modal, so the Modal can restore focus to the action's button on close.

e.g.

```
const deleteButtonRef = useRef(null);
...
return (
  <Modal
      activator={deleteButtonRef}
      ...
  />
  <PageActions
     primaryAction={{
        content: 'Delete'
        onAction: () => setDeleteModalVisible(true)
        ref={deleteButtonRef}
     }}
    secondaryActions={[...]}
  />
);
```

## Rationale

This would address an accessibility issue in URL Redirects (`/admin/redirects/:id`) where cancelling the Delete URL Redirects modal puts the focus back at the top of the page instead of the Delete button that was clicked, and disorient/disrupt the navigation flow of merchants using text reader devices.

<img width="1177" alt="Screen Shot 2021-04-28 at 1 20 00 PM" src="https://user-images.githubusercontent.com/72215045/116456652-7e8d0600-a830-11eb-8ade-9cae3d03ca8a.png">

Our current hack consists of passing the entire PageActions component as the activator, because Modal will give focus bak to the first element of the activator  (see PR https://github.com/Shopify/web/pull/42581 for details)
We're lucky that the first element happens to be the Delete button that opened the Modal, but it's extremely fragile should new actions be added before Delete.

```
return (
  <Modal
      activator={
        <PageActions
           primaryAction={{
              content: 'Save',
              onAction: submit
           }},
           secondaryAction={[
             {
                content: 'Delete'
                onAction: () => setDeleteModalVisible(true)
             }
           ]}
        />
      }
      ...
  />
);
```

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by jeromelecomte-shopify** [comment]
My understand is that it would require refactoring PageActions and possibly Button's `buttonsFrom` utility to use React.forwardRef() to forward the reference passed in ComplexAction down to the Button component. I'm not sure what impact it would have on the other Shopify components consuming Button.

**Comment by ShadowRadiance** [comment]
const deleteButtonRef = useRef(null);
const saveButtonRef = useRef(null);
const exportButtonRef = useRef(null);
...
return (
  <Modal
      activator={deleteButtonRef}
      ...
  />
  <PageActions
     primaryAction={
        content: 'Save'
        onAction: onSave
        ref={saveButtonRef}
     }
     secondaryActions={[
       {
          content: 'Delete'
          onAction: () => setDeleteModalVisible(true)
          ref={deleteButtonRef}
        },
        {
          content: 'Export'
          onAction: () => setExportModalVisible(true)
          ref={exportButtonRef}
        },
     ]}
  />
);

**Comment by shannon-shopify** [comment]
This branch has changes that add the ability to pass a ref into primary and secondary actions for both `Page` and `PageActions`. It requires a few components to be able to take forwardRefs, and involves passing `false` to `focusFirstFocusableNode` within Modal.tsx (since otherwise the button is not focused as the button isn't a child of itself). This has been tested, but not extensively and only within Playground. 

https://github.com/Shopify/polaris-react/tree/modal-focus-nonsense

**Comment by PrescilliaA** [comment]
Hi 👋 I am currently running into the same issue, is there any movement on this?
