### ISSUE TITLE
Q: How to prevent navigation when clicking on app title in Shopify Bar?

### ISSUE THREAD

**Issue by jjt** [Shopify/polaris#415]
We have a SPA, routing via React Router to avoid page loads. When clicking on the application title ("USOhHeckYesAPP") in the Shopify Bar in parent window (see image below), it reloads the iframe.

![image](https://user-images.githubusercontent.com/399469/45057108-9f820680-b049-11e8-8be6-6d4b4dc21266.png)

I've got a message listener in our app that picks up on the `Shopify.API.setWindowLocation` postMessage, and can route based on that message. But I need to prevent the iframe from navigating. Is this possible via props on `<AppProvider>` or `<Page>`, or via an EASDK method?

Here is our application structure roughly, with some details (`apiKey`, etc) omitted. Let me know if you need any further details. 

```js
<AppProvider>
  <Router>
    <Route path="/settings" render={(props) => (
      <Page title="Settings"></Page>
    )}/>
  </Router>
</AppProvider>
```

Thanks!

**Comment by dpersing** [comment]
Hi @jjt! Thanks for your question. The behavior you're describing is handled by the EASDK, so take a look at the [Shopify Developers EASDK documentation](https://help.shopify.com/en/api/embedded-apps/embedded-app-sdk) for info on what you can configure in the App Bar.

**Comment by jjt** [comment]
Hi @dpersing, thanks for the response. However I've gone through the docs and there's nothing that I can see that would allow me to specify a callback when the app title is clicked on. The closest thing I can see is `ShopifyApp.Bar.setBreadcrumb()` which states "Pass a button object, or pass undefined to remove it entirely". But passing `undefined` results in a syntax error.

Is it my understanding that there's no way for us to control what happens when a user clicks on the app title (USOHeckYesAPP in my example image)?

**Comment by dpersing** [comment]
Hi @jjt,

I'd recommend reaching out on the [Shopify APIs & SDKs discussion group](https://ecommerce.shopify.com/c/shopify-apis-and-technology). It sounds like there may be an issue with either the documentation or the `ShopifyApp.Bar.setBreadcrumb()` method.

**Comment by jjt** [comment]
Will do, thx!
