### ISSUE TITLE
are PR welcome at this moment?

### ISSUE THREAD

**Issue by raerpo** [Shopify/polaris#417]
# Issue summary
Hi Guys, awesome job on this project. I see in the README this message:

```
🆕 🎉 📰 July 30, 2018 – In the coming weeks, all active development and issue tracking for Polaris React will move to this repository. At that time, we will start accepting pull requests. We look forward to your contributions!
```

But also I see that the issue template says that you are not receiving PR, so i want to know if contributions are welcome at this moment.

Thanks!

**Comment by dleroux** [comment]
Not quite yet but very soon. A few minor issues to iron out and we'll be open source!
