### ISSUE TITLE
Modal component breaks when AppProvider is configured

### ISSUE THREAD

**Issue by phawk** [Shopify/polaris#418]
# Issue summary

I have a polaris app that uses a Modal component with a Modal.Section inside it. When I don't have AppProvider setup it works as expected clicking the modal opens it. When I have AppProvider configured with apiKey and shopOrigin the modal emits an error.

## Expected behavior

Modal should work the same way wether AppProvider is configured or not.

## Actual behavior

Modal emits error message:

```
These required properties are missing from Modal: src
```

## Steps to reproduce the problem

1. Create an app using a Modal with Modal.Section content rather than a `src` attribute
2. Configure AppProvider

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 2.8.0
- Browser: Chrome
- Device: Macbook pro 15"
- Operating System: MacOS

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 We _are_ accepting issue reports and feature requests<br />
🌟 Feature requests that we can’t get to right away will be closed. However, we track all requests and will use it to set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by dleroux** [comment]
Hi @phawk, Sorry for the confusion on this but for security reasons  the `src` prop of [embedded modals](https://polaris-v2.shopify.com/components/embedded/embedded-modal) is required. see issue https://github.com/Shopify/polaris/issues/320.

**Comment by phawk** [comment]
@dleroux thanks for getting back so quickly. What security reasons? I don't want to load an iframe inside of my modal, my modal is just plain react code already present in the DOM. Seems like a very simple use case and a more secure than loading any form of iframe. Or am I misunderstanding?

```jsx
<Modal
  open={this.state.active}
  onClose={this.onClose}
  title="New Section"
  secondaryActions={[
    {
      content: 'Cancel',
      onAction: this.onClose,
    },
  ]}
>
  <Modal.Section>
    <div className="template-selection">
      { templates.map(template => (
        <div className="template" key={`template-${template.id}`} onClick={() => this.handleTemplateSelection(template)}>
          <span className={`previewimg -${template.slug}`}></span>
          <h3>
            {template.title}
            <small>Images: {template.item_count}</small>
          </h3>
        </div>
      ))}
    </div>
  </Modal.Section>
</Modal>
```

**Comment by dleroux** [comment]
The issue is that the embedded apps inside the admin are loaded inside an iframe. However calling a modal to open actually opens the modal outside the iframe and on server meaning the content of the modal is not longer within the app. It's how we manage to get the modal centered with a  backdrop covering the entire page. We are looking at a better solution for this but unfortunately for now the `src` is required.

**Comment by phawk** [comment]
Ah okay, that makes sense, I’ll rework how it's structured thank you!
