### ISSUE TITLE
[Autocomplete] Add multiple section groups on autocompletion list

### ISSUE THREAD

**Issue by lucasfrosty** [Shopify/polaris#4180]
## Feature request summary
The [OptionList](https://polaris.shopify.com/components/lists-and-tables/option-list) component provides a way to group options into multiple sections, as shown on the screenshot above:

<details>
<summary>Screenshot</summary>

<img width="631" alt="Screen Shot 2021-05-06 at 11 14 17 AM" src="https://user-images.githubusercontent.com/15235605/117365936-0f498e80-ae8e-11eb-935c-c2f1d3bf2a94.png">
</details>

However our current [Autocomplete](https://polaris.shopify.com/components/forms/autocomplete) implementation is focused on single sections instead, with the possibility of using a `listTitle` prop to add a title to that single section that is created.

The request is to create the same idea of multiple sections that OptionList has, but in the `Autocomplete` component as well.

Since Autocomplete actually uses [OptionList](https://github.com/Shopify/polaris-react/blob/85aba920dfa9a8882b60dccf8221df5837f6d05c/src/components/Autocomplete/components/ComboBox/ComboBox.tsx#L285-L295) it wouldn't be too hard to implement, however the big challenge sits around how to make the `options` and `listTitle` props API update in a way that won't be a breaking change. I have some ideas but first i'd like to know some thoughts on the UX side and then, if we get a 👍 , we can discuss the API implementation and i'd happily start the implementation of this feature.

Thanks!

cc @luanpy

**Comment by aminick** [comment]
Upvote for this. This is essential.

**Comment by yurm04** [comment]
This change was implemented and is available now in the [`Autocomplete`](https://polaris.shopify.com/components/autocomplete) component. Thanks @lucasfrosty !
