### ISSUE TITLE
Tooltip text doesn't wrap properly for certain length of characters

### ISSUE THREAD

**Issue by posth** [Shopify/polaris#419]
### Issue summary and behavior

When using the [Tooltip](https://polaris.shopify.com/components/overlays/tooltip) component, messages of certain character length passed to `content` doesn't wrap properly and can cause a lot of empty space on the tooltip.

For example, if *This discounts has conversations* is added, the UI looks like:

![screen shot 2018-08-10 at 3 17 03 pm](https://user-images.githubusercontent.com/5506721/45170223-5e1a6400-b1cd-11e8-961d-ad36142c559b.png)

[CodeSandbox example](https://codesandbox.io/s/0y5x0jj17w?module=App.js)

**Comment by chloerice** [comment]
Hi @posth, this text wrapping is expected behavior, as the tooltip content has a max-width of 200px. In this case, the character length of the word  “conversation” is longer than the available space within the max-width so it wraps to the next line.
