### ISSUE TITLE
[Collapsible] Unsetting transition results in `onTransitionEnd` listener not firing

### ISSUE THREAD

**Issue by kyledurand** [Shopify/polaris#4194]
## Issue summary

If we unset the transition for collapsible, i.e.

```jsx
<Collapsible
  id={id}
  open={open}
  transition={{timingFunction: 'unset', duration: '0ms'}}
/>
```

Then `onTransitionEnd={handleCompleteAnimation}` doesn't get triggered. 

This means that collapsible can get stuck in a state where it thinks it's still animating and render a max-height along with overflow hidden when it's fully expanded.

**Comment by brydonm** [comment]
Also experiencing this. Finding that 2nd (and 3rd) sub-nav items get cut off when 2nd sub-nav gets opened along with  being stuck open.

This happens to me while using the Navigation component.
