### ISSUE TITLE
Grammatical errors in documentation

### ISSUE THREAD

**Issue by phlfvry** [Shopify/polaris#421]
# Issue summary

In the final section, **Don't forget about the words**, of the [Designing apps for Shopify page](https://polaris.shopify.com/guides/designing-apps#navigation) exists a grammatical error:

> Vocabulary, including terms like “fulfillment” and “channel” and the _different_ between “log in” and “login”. 

## Expected behavior

The word different should be changed to _difference_.

**Comment by phlfvry** [comment]
https://polaris.shopify.com/design/illustrations#navigation

In the **COMMON PLACES TO USE ILLUSTRATION** section, the content within the parenthesis by Empty states reads _when a a page has no results, or when something goes wrong_

**Comment by solonaarmstrong** [comment]
Thank you for pointing those out. A fix is on the way.
