### ISSUE TITLE
Product name overlaps secondary action buttons

### ISSUE THREAD

**Issue by Lockdayne** [Shopify/polaris#4227]
## Issue summary
Product name overlaps secondary action buttons when the product name is too long

## Expected behavior
The product name adapts if it is too long and does not overlap secondary buttons

## Actual behavior
Product name overlaps secondary action buttons

## Steps to reproduce the problem

1. Create a new product with too long product name
2. Go to the page with the long product name

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 6.4.0 and 6.2.1
- Browser: Google Chrome, version 90.0.4430.212 (Official Build) (x86_64)
- Device: iMac
- Operating System: macOS

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```
**Link to screenshot:** https://drive.google.com/file/d/1Y6KoipTjubR1QOGysIS95N_PI5-8kt49/view?usp=sharing

**Comment by shopi-dori** [comment]
Hi, @Lockdayne , I've requested access to view the linked [screen shot](https://drive.google.com/file/d/1Y6KoipTjubR1QOGysIS95N_PI5-8kt49/view?usp=sharing) as part of this bug's investigation.

I haven't yet been able to reproduce the issue with the test criteria on the latest release of Polaris 7.6.0. If you have more details, please feel free to provide them.  Seeing that this was reported for Polaris 6.*, we do recommend upgrading to the [latest Polaris version](https://polaris.shopify.com/whats-new/whats-new#navigation) to take advantage of all the features and fixes.

If you feel the bug has been resolved as part of the current Polaris 7.* release, please let us know in the comments. Thanks!
