### ISSUE TITLE
Make it possible for DropZone to expand to container height

### ISSUE THREAD

**Issue by pt8o** [Shopify/polaris#4237]
## Feature request summary

Add a prop to `<DropZone>` like `maximizeHeight` which allows the DropZone to expand to fill the height of its container, so that the parent can more easily control the size of the DropZone.

## Rationale

This kind of design was requested from our UX team recently on FilePicker: https://github.com/Shopify/core-issues/issues/25232

It would be nice to be able to allow the parent to have a bit more control over the dropzone's sizing, as if it was just a div. So then the dropzone could resize to fit a variety of containers.

I haven't made a PR for this because I wasn't sure how to tackle it. I was looking into it a bit and I don't see an easy way to implement since the `<DropZone>` component returns this:

```
<Labelled>
  <div>
    {a couple overlays}
    <div>
     {children}
```

In my experiments this required putting a `height:100%` on three different divs, including the one that gets returned by `<Labelled>`, so then we'd need to maybe modify that one to accept a classname from the parent... gets messy quick.

Curious to hear if anyone has any ideas on how to pull this off!

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by yurm04** [comment]
Thanks for the request, @pt8o . We’re not able to work on this right now, but here are some suggestions in case someone is able to jump in:
* convert this issue to a GitHub discussion and label it as `Help Wanted`
* provide a CodeSandbox link with your current approach and the difficulties you're bumping up against

I’ll close this issue for now, but we encourage everyone who wants this feature to add a 👍 to the original issue report. We’ll take your collective interest into account when we look at what to work on next. 💜
