### ISSUE TITLE
is ShopifyApp as part of Polaris?

### ISSUE THREAD

**Issue by superwhykz** [Shopify/polaris#424]
# Issue summary

Not able to import `ShopifyApp` from Polaris.  

```
import ShopifyApp from '@shopify/polaris';
``` 

I am trying to escape `iframe` for redirect.  Per documentaion it seems I can do the following.
https://help.shopify.com/en/api/embedded-apps/embedded-app-sdk/getting-started#oauth

I was thinking something like this. My response will have `URL` which then to redirect.

```
...
...
 headers: {Authorization: props.token},
        })
          .then((res) => {
            if (res.data.url) {
              // console.log('URL: ', res.data.url);
              if (window.top === window.self) {
                window.location.assign(res.data.url);
              } else {
                ShopifyApp.redirect(res.data.url);
              }
            }
          })
          .catch((err) => {
            const message = err.response
              ? err.response.data.error
...
...
...
```

## Expected behavior

Import `ShopifyApp` from Polaris

## Actual behavior

Here is the message:
```
./src/components/..../ChangeTier.js
2:72-82 "export 'default' (imported as 'ShopifyApp') was not found in '@shopify/polaris'
```

## Steps to reproduce the problem
1. Not much just tried to import. 

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: "@shopify/polaris": "^2.8.0"
- Browser: Chrome Version 68.0.3440.106 (Official Build) (64-bit)
- Device: MacPro
- Operating System: macOS Sierra 10.12.6 (16G1114)

**Comment by chloerice** [comment]
Hi @superwhykz, `ShopifyApp` isn't a part of Polaris React, but the `AppProvider` gives your app access to your app's context. Try `this.props.polaris.easdk.redirect(res.data.url)` (or `this.context.easdk.redirect(res.data.url)` if you've set `contextTypes` on your component).

**Comment by superwhykz** [comment]
@chloerice thanks much for quick response. Let me try the first one.  As far as context I will need to setup sort of this way?

```
class MyApp extends React.Component {
  // This line is very important! It tells React to attach the `easdk`
  // object to `this.context` within your component.
  static contextTypes = {
    easdk: PropTypes.object,
  };
```

**Comment by chloerice** [comment]
^Yes, exactly, that was the way context was accessed prior to the v2.0 release and context can still be accessed this way for backwards compatibility.

**Comment by superwhykz** [comment]
@chloericeI end up setting up `context` and it seems working fine now. From an educational perspective does the `this.props.polaris`  should be available globally or I need to set it up?

**Comment by chloerice** [comment]
Yes, `this.props.polaris.easdk` should be available globally thanks to the `AppProvider`.

**Comment by superwhykz** [comment]
hi @chloerice wanted to follow up on this. I just upgraded to https://github.com/facebook/create-react-app/releases/tag/v2.0.3  and they mentioned that 

```
PropTypes definitions are now removed in production

Normally, this shouldn't affect your logic and should make the resulting bundle smaller. However, you may be relying on PropTypes definition for production logic. This is not recommended, and will break now. If a library does it, one possible solution is to file an issue in it with a proposal to use a different field (not propTypes) to signal that the declaration needs to be retained.
```

they way I access is 
```
...
import * as PropTypes from 'prop-types';

const apiHost = process.env.REACT_APP_API_HOST;

class Module extends Component {
  static contextTypes = {
    easdk: PropTypes.object,
  };
...
```

Do you think I am safe on this approach?

**Comment by mbaumbach** [comment]
@superwhykz That's safe. I use it all over the place to work with the EASDK and I'm already using production builds of CRA 2.0.3 and Polaris 2.11.0, if that makes you feel better. :)

They are basically just stripping the `PropTypes` checking to reduce bundle sizes. If you, for example, had a reference to `PropTypes` somewhere in your `render` method, that could be problematic.

**Comment by superwhykz** [comment]
@mbaumbach thank you so much! I am about push production :) but did not see anything in dev.  Thought to check to make sure :)
