### ISSUE TITLE
Filters component is throwing an deprecation warning for Sheet

### ISSUE THREAD

**Issue by pklitscher** [Shopify/polaris#4275]
## Issue summary

`<Filters/>` component is throwing an deprecation warning for `<Sheet/>`
```
Deprecation: <Sheet /> is deprecated. This component might be removed in a future major version of Polaris. Use <Modal /> instead or avoid modal patterns all together. 
```

## Expected behavior

`<Sheet/>` should be removed from component or warning supressed. Developer cannot resolve it's use when using `<Filter/>` as intended

## Actual behavior

Deprecation warning is filling console with expanded warning messages. Sure I could filter them out but then I don't see any warning messages. 

## Steps to reproduce the problem

1. Use `<Filters/>` component

## Reduced test case

https://codesandbox.io/s/cvee8?module=App.js

## Specifications

```
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 1.58 GB / 15.86 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.54)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @shopify/polaris: ^6.5.0 => 6.5.0
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
```

**Comment by youminkim** [comment]
Same bug happens to me

**Comment by ssamkough** [comment]
This is happening to me as well. Fills up my console!

**Comment by alex-page** [comment]
Thanks everyone. This is a duplicate to https://github.com/Shopify/polaris/issues/5749

> Thanks @meganmajewski! This is definitely something on our radar. We hope to replace the filter pattern in the future and remove the sheet entirely from the design system. For now feel free to use it.

**Comment by mcjambi** [comment]
i have same issue, please fixed it soon!

**Comment by mcjambi** [comment]
i have the same issue
