### ISSUE TITLE
Handle onClick event with event object for Item of `Navigation.Section`

### ISSUE THREAD

**Issue by pierreneter** [Shopify/polaris#4277]
## Feature request summary

- `Item` of `Navigation` (https://github.com/Shopify/polaris-react/blob/main/src/components/Navigation/components/Item/Item.tsx#L57) has `onClick` event but we can't handle the event object made by this event.
- The `SubNavigationItem` has pass event object to the function: `event: MouseEvent<HTMLElement>` (https://github.com/Shopify/polaris-react/blob/main/src/components/Navigation/components/Item/Item.tsx#L37)
- But that `SubNavigationItem` use `Item` for render:
```ts
 {subNavigationItems.map((item) => {
            const {label, ...rest} = item;
            return (
              <Item
// ...
```
https://github.com/Shopify/polaris-react/blob/main/src/components/Navigation/components/Item/Item.tsx#L249-L252
- And the `onClick` event of SubItem at https://github.com/Shopify/polaris-react/blob/main/src/components/Navigation/components/Item/Item.tsx#L253 has been replaced by `onClick={onNavigationDismiss}` https://github.com/Shopify/polaris-react/blob/main/src/components/Navigation/components/Item/Item.tsx#L257

So, the event object pass through the param doesn't work for `Item`.
And `onClick` of `SubNavigationItem` not working at all

## Rationale

By can handle this event, event object. I can make the browser change path without reloading the page, for example:

```ts
import { useLocation, useNavigate } from "react-router-dom"; // (v6)
// ...
const location = useLocation();
const navigate = useNavigate();
///...
<Navigation location={location.pathname}>
  <Navigation.Section
// ...
    items={[
      {
        url: "/test/cms/posts",
        label: "Posts",
        onClick: (e) => {
          e.preventDefault();
          navigate("/test/cms/posts");
        },
      }

// ...
```

Or maybe we can improve with a prop to make `a` does not load page

**Comment by yurm04** [comment]
Thanks for the request, @pierreneter . We’re not actively working on this right now, but we keep an eye on all feature requests.

I’ll close this issue for now, but we encourage everyone who wants this feature to add a 👍 to the original issue report. We’ll take your collective interest into account when we look at what to work on next. 💜
