### ISSUE TITLE
Expose Checkbox change event in onChange handler parameters

### ISSUE THREAD

**Issue by L42y** [Shopify/polaris#4282]
## Feature request summary

Expose Checkbox change event in onChange handler parameters

``` typescript
<Checkbox onChange={(
  checked,
  id,
  event // add this parameter
) => {
}} 
/>
```

## Rationale

Sometimes we might need to access the change event from `<input type="checkbox" />`

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by yurm04** [comment]
Thanks for the request, @L42y. We’re not actively working on this right now, but we’d love for it to make its way into the system. Please feel free to contribute and open a PR!
