### ISSUE TITLE
Card header actions misaligned in 2.10.0

### ISSUE THREAD

**Issue by mbaumbach** [Shopify/polaris#429]
# Issue summary

Since upgrading to Polaris 2.10.0, `Card` header actions appear to be misaligned due to extra padding around the button component.

## Expected behavior

The header actions are aligned with the title of the `Card`.

## Actual behavior

The `Card` header actions are slightly lower (below the baseline) than the title. See example screenshots of 2.9.0 and 2.10.0:

![2.9.0](https://i.imgur.com/5xgIGyp.png)

![2.10.0](https://i.imgur.com/rVlA8F1.png)

## Steps to reproduce the problem

1. Visit the example "Card with header actions" and make sure the Polaris version is either "latest" or "2.10.0" in the package.json. https://codesandbox.io/s/3xm4n4y6vp?module=App.js

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 2.10.0
- Browser: Chrome 69.0.3497.100
- Device: MacBook Pro
- Operating System: macOS High Sierra 10.13.6

**Comment by dleroux** [comment]
Thanks @mbaumbach. This will be in the next release.
