### ISSUE TITLE
Number field spinner not working in CSS mode

### ISSUE THREAD

**Issue by paulcanning** [Shopify/polaris#432]
I am writing some template partials using the CSS Polaris library only.

I have copied the code shown here, https://polaris.shopify.com/components/forms/text-field, for the number field template, but the spinner controls do not work for me.

Do I need to include the JS library even if I'm not using it specifically?

**Comment by solonaarmstrong** [comment]
Hi @paulcanning are you using the React or the HTML version?

**Comment by solonaarmstrong** [comment]
I tried it with the HTML version and I am able to reproduce it. I will open an internal issue. Thank you for bringing it to our attention.

**Comment by ry5n** [comment]
Hi Paul, I was looking into this today. If you’re writing your own HTML and using only Polaris CSS, you need to write your own JS for most interactive components. This is one of the advantages of using React. However, even with the CSS-only approach, you can use the Polaris website to see how the component behaves, and even review the React code to see how things were implemented.

I’ve opened a [feature request issue](https://github.com/Shopify/polaris/issues/437) where you can vote for a more fully-featured framework-agnostic implementation of Polaris.
