### ISSUE TITLE
HTML only Select doesn't work

### ISSUE THREAD

**Issue by paulcanning** [Shopify/polaris#434]
Using the HTML + CSS only version, the select dropdown does not change the value when you pick a new option.

Copy and paste the HTML from the box provided here, https://polaris.shopify.com/components/forms/select and then change the select option.

The value does not change.

As with https://github.com/Shopify/polaris/issues/432, I am thinking that a JS file must be required to make some of these controls work properly, yet the documentation does not say anything about that.

**Comment by markiiikram** [comment]
Hi @paulcanning, thanks for the issue. If you are using the static HTML and CSS you are responsible for wiring up your own JS to make it interactive. That being said, we recommend using the react package for these components. I'll let the Polaris team know that it could be beneficial of saying this explicitly in the docs.

**Comment by paulcanning** [comment]
I would say it is 100% beneficial. It's a crucial part of getting it to work.

**Comment by markiiikram** [comment]
Hi @paulcanning, A PR was created, "Note if you’re using CSS-only you’ll need to provide your own JavaScript." will be added to the Get Started > CSS components section in our next release.
