### ISSUE TITLE
Using `data-primary-link` only works once when not redirecting to a different page

### ISSUE THREAD

**Issue by Brydom** [Shopify/polaris#4345]
## Issue summary

The index table `data-primary-link` prop does not trigger a click/redirect after the first time. We think this is because of the `isNavigating.current` assignment on l101 of `Row.tsx`.

I'm not entirely sure of what the purpose is with `isNavigating`, but, it looks like it could almost be removed? Alternatively, it may just be able to be moved down below l110 after the if/else.

## Expected behavior

It should keep triggering after the first click.

## Actual behavior

It does not work after the first click.

## Steps to reproduce the problem

1. Use `data-primary-link` setup in `IndexTable`
2. Click the link to add a URL param or use an `onClick` handler to stay on the same page
3. Link no longer works

## Reduced test case

https://codesandbox.io/s/unselectable-index-table-forked-utd6z

**Comment by Brydom** [comment]
@chloerice if you would be so kind to have a look at this when you have some time! 🥳

**Comment by alex-page** [comment]
Hey @Brydom thanks for bringing this up. Do you have time to create a pull request? Our team is busy with a lot of new work and is supporting this project with pull request reviews.

**Comment by alex-page** [comment]
Legend. Thank you @Brydom ✨

**Comment by TheSecurityDev** [comment]
Is there any workaround for this yet?

**Comment by chloerice** [comment]
Still an issue.

**Comment by JetLua** [comment]
Should reopen
