### ISSUE TITLE
IndexTable deselection after selected resource removal

### ISSUE THREAD

**Issue by CameronGorrie** [Shopify/polaris#4346]
## Feature request summary
If you have a bulk action that deletes a resource from an index table, the list of selected resources is not updated when using the [`useIndexResourceState` hook](https://github.com/Shopify/polaris-react/blob/main/src/utilities/use-index-resource-state.ts). It would be nice to expose a callback that could be used to reset or provide a new selection state after some action.

## Rationale
Perhaps there's an established pattern for doing this that I've missed. My naive approach might look something like this:

```tsx
import {useState, useCallback} from 'react';
...
export function useIndexResourceState<T extends Record<string, unknown>>(
  resources: T[],
  {
    selectedResources: initSelectedResources = [],
    allResourcesSelected: initAllResourcesSelected = false,
    resourceIDResolver = defaultResourceIDResolver,
  }: {
    selectedResources?: string[];
    allResourcesSelected?: boolean;
    resourceIDResolver?: ResourceIDResolver<T>;
  } = {
    selectedResources: [],
    allResourcesSelected: false,
    resourceIDResolver: defaultResourceIDResolver,
  },
) {
  const [selectedResources, setSelectedResources] = useState(
    initSelectedResources,
  );
  const [allResourcesSelected, setAllResourcesSelected] = useState(
    initAllResourcesSelected,
  );

  const handleSelectionReset = (selectedResources: string[] = []) => {
    setSelectedResources(selectedResources);
    setAllResourcesSelected(false);
  };

  ...

  return {
    selectedResources,
    allResourcesSelected,
    handleSelectionChange,
    handleSelectionReset,
  };
}

```

**Comment by ko-lem** [comment]
Looking at the implementation of [handleSelectionChange](https://github.com/Shopify/polaris-react/blob/main/src/utilities/use-index-resource-state.ts#L47), I wonder if something like `handleSelectionChange('all', false)` would do the trick.

**Comment by pinoytech** [comment]
The `setSelectedResources` could be exposed to update the selection.

**Comment by CameronGorrie** [comment]
> handleSelectionChange('all', false) would do the trick.

Yeah this would work fine. The [`SelectionType`](https://github.com/Shopify/polaris-react/blob/main/src/utilities/use-index-resource-state.ts#L3-L8) should be exposed in that case.

**Comment by AndrewMusgrave** [comment]
If we wanted to keep the logic encapsulated useIndexResourceState could run an effect when the resources change that filters selected id's that don't exist anymore.
