### ISSUE TITLE
Popovers disappear/don't appear when vertical height is limited

### ISSUE THREAD

**Issue by mbaumbach** [Shopify/polaris#435]
# Issue summary

When there's not a lot of vertical viewport height in the browser, popovers will not appear (or will disappear as viewport height is reduced). This can be especially noticeable in embedded apps, as there's the Shopify header and app header which takes up additional vertical height.

## Expected behavior

The popover will be displayed regardless of viewport height, but the content area will scroll to make the content accessible.

## Actual behavior

If there's not enough viewport height when the popover `open` prop is toggled to `true`, the popover won't display at all. If the browser window height is reduced while the popover is already visible, it will disappear if it's reduced enough.

## Steps to reproduce the problem

1. Create a popover with content that takes up a decent amount of vertical space (Good examples are `ColorPicker` and `DatePicker` components)
1. Open the popover using the defined `activator`.
1. Reduce the height of the browser window and eventually it'll disappear.
1. Increase the height of the browser and it'll reappear.

An example of this happening can be seen in the GIF below and the code is available on [this sandbox](https://codesandbox.io/s/7z7kxz2jr6). This particular example is of the popover disappearing when the height is reduced manually, because it's the easiest to reproduce. The other problem where the popover simply doesn't seem to appear at all is the same problem. Once you've found the height where the popover doesn't appear, you can toggle the activator and never see the popover.

![Popover disappearing](https://camo.githubusercontent.com/d5cec71b4367c5979e68859bba92beaae83db95e/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f506f45456a4975356a6b78586f355847417a2f67697068792e676966)

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 2.10.0
- Browser: Chrome (though this happens on all)
- Device: MacBook Pro
- Operating System: macOS High Sierra

**Comment by katiedavis** [comment]
Hello @mbaumbach I just wanted to let you know that the wild behaviour of the popover is being addressed internally!

**Comment by solonaarmstrong** [comment]
I've fixed it and it will be in the next release.

**Comment by mbaumbach** [comment]
@katiedavis @solonaarmstrong Confirmed this is fixed! Thanks!
