### ISSUE TITLE
Error when using Choice list

### ISSUE THREAD

**Issue by sadilegend** [Shopify/polaris#4366]
When i used choice list component in multiple child component. I had this issues

![Screenshot at Aug 09 11-54-16](https://user-images.githubusercontent.com/65278766/128661688-0e5eed5f-4d77-44c1-ba33-2e5f9dabdeed.png)
It's reset ID radio in choice list.
Can I customize ID in this issues? Or can you update ID custom for each radio or checkbox when it has same ID?

**Comment by alex-page** [comment]
@sadilegend I am going to close this issue as I cannot replicate it with the image provided. If you have some React code or a codesandbox to share I would be happy to take a look.
