### ISSUE TITLE
Broken image URLs in README.md component example images

### ISSUE THREAD

**Issue by lonroth** [Shopify/polaris#4384]
## Issue summary

When visiting the `README.md` for a component that has example images such as [Badge](https://github.com/Shopify/polaris-react/blob/main/src/components/Badge/README.md) or [Select](https://github.com/Shopify/polaris-react/blob/main/src/components/Select/README.md) example images are not shown and their URLs are broken (throws 404s). Could be that the URL has been changed but the `README.md` hasn't been updated?

## Expected behavior

Example images should show for components in the `README.md` if they are present (not all `README.md` includes them).

## Actual behavior

Component examples images for `Badge` are broken (404) and doesn't show in the `README.md`:
![image](https://user-images.githubusercontent.com/240931/129046446-eae9e057-7087-4a4f-b7b6-404abbb81d6a.png)

Example pages (several pages seems to be affected by broken image URLs):
https://github.com/Shopify/polaris-react/blob/main/src/components/Select/README.md
https://github.com/Shopify/polaris-react/blob/main/src/components/Badge/README.md

## Steps to reproduce the problem

1. Visit https://github.com/Shopify/polaris-react/blob/main/src/components/Badge/README.md#examples
1. Look at the example images for the component (showing as a broken image)
1. Click the image to get to the 404 page for the image (for eg. https://github.com/Shopify/polaris-react/blob/main/public_images/components/Badge/android/default@2x.png)

**Comment by alex-page** [comment]
Hey @lonroth, this is currently how we render out our documentation for polaris.shopify.com it's definitely unintuitive. We are replatforming the website and I will pass on the feedback as the images should work for both the README files and the website.
