### ISSUE TITLE
UI not working properly on Chrome on IndexTable

### ISSUE THREAD

**Issue by zilehuda** [Shopify/polaris#4396]
Please have a look at the screenshot (https://imgur.com/AWvUylM)

On chrome, IndexTable cut down the border on the first two columns but working fine on Firefox.

Link: https://codesandbox.io/s/yckod?module=App.js

**Comment by brendanrygus** [comment]
Hi @zilehuda , this should be resolved in the next release by https://github.com/Shopify/polaris-react/pull/4150

**Comment by kelliekumasaka** [comment]
Hi @brendanrygus ,

Has this been changed in all media queries as well? This particular media query still contains `box-shadow` and `position: sticky` properties, even while fullscreen on 13-inch MBP. Can this also be changed to `drop-shadow`? 


<img width="518" alt="Screen Shot 2022-03-18 at 10 40 05 AM" src="https://user-images.githubusercontent.com/74799430/159057668-d0409141-db62-42e3-afcb-5740841490cf.png">

<img width="381" alt="Screen Shot 2022-03-18 at 10 54 49 AM" src="https://user-images.githubusercontent.com/74799430/159057672-1d0b9694-b1fc-43b9-a5f4-4b9a7e9d1d79.png">

**Comment by brendanrygus** [comment]
I believe there have been further adjustments to the Index Table in more recent versions of Polaris. 

It would be best to create a new ticket and specify the exact issue you are experiencing as well as the Polaris version used.
