### ISSUE TITLE
Allow onClick handlers in <Link> to use `Event`

### ISSUE THREAD

**Issue by skparkk** [Shopify/polaris#4399]
#### Context

In the editor, we want to wrap links to Shopify's admin with a window provider so that the editor can auto-refresh with updated content. When using `<Link>`, `event.preventDefault()` needs to be used to prevent the browser from opening 2 windows/tabs to the same link.

#### Problem

Currently, polaris defines [`onClick` type to be `(): void`](https://github.com/Shopify/polaris-react/blob/main/src/components/Link/Link.tsx#L26) and throws a type error when the `event` parameter is passed.

Example type error: `Type '(event: React.MouseEvent<HTMLAnchorElement>) => void' is not assignable to type '() => void'.`

## Rationale

Since the link is navigating to new page, we still need `<Link>` to render `<a>` for accessibility purposes. By updating the type, developers will be able to use the `Event` web api.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris-react/blob/main/.github/CONTRIBUTING.md) for more information.

**Comment by alex-page** [comment]
Hey @skparkk as of now we don't allow event flexibility in the components. I will bring this up with the team as we are looking at ways to make the components more flexible.
