### ISSUE TITLE
Conflict with create react app 2.0.3

### ISSUE THREAD

**Issue by fchienvuhoang** [Shopify/polaris#440]
# Issue summary

https://www.evernote.com/l/AXCr4d5Nm4JK7pMWk070_aFpbX-gffta7SQ

## Steps to reproduce the problem

1.
1.
1.

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number:
- Browser:
- Device:
- Operating System:

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 We _are_ accepting issue reports and feature requests<br />
🌟 Feature requests that we can’t get to right away will be closed. However, we track all requests and will use it to set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by paul-phan** [comment]
Actually, it might be a conflict with postcss, btw, it recommended to include Polaris CSS via a link:

```html
<link rel="stylesheet" href="https://sdks.shopifycdn.com/polaris/2.10.0/polaris.min.css" />
```

[Ref: Polaris](https://polaris.shopify.com/components/get-started)

**Comment by fchienvuhoang** [comment]
@paul-phan ok thanks 👯‍♂️

**Comment by solonaarmstrong** [comment]
Hi @fchienvuhoang. Did importing the CSS in your HTML file fix the issue?

**Comment by solonaarmstrong** [comment]
Great! I will close this issue.
