### ISSUE TITLE
How to use the Lists and Tables -> Section Header

### ISSUE THREAD

**Issue by rbmdotdev** [Shopify/polaris#4410]
## Issue summary

I am looking at the docs for 'Section Header' [here](https://polaris.shopify.com/components/lists-and-tables/section-header#navigation).

I am immediately struck by the fact that there is no example code however the example screenshots do look like what I am trying to achieve in my Resource List.  When I look for a component called SectionHeader in polaris-react I can only find the markdown for this very documentation.

What am I missing about this component?  Is there a clue in the fact the docs show ios and android examples only?

## Expected behavior

The fact that it is listed in the docs as a component I would expect it to be an actual component that can be imported and used

## Actual behavior

Just a vague doc page referring to something I can't use?

**Comment by youminkim** [comment]
+1

**Comment by alex-page** [comment]
Hey @rbmdotdev I agree that we need to do a better job here. Currently this is how we do our documentation for mobile components. There isn't any code that comes along with it. I will close this issue for now and share the feedback with the team.
