### ISSUE TITLE
SkeletonPage is missing property for additionalNavigation

### ISSUE THREAD

**Issue by sander-m** [Shopify/polaris#4439]
## Feature request summary

The [SkeletonPage](https://polaris.shopify.com/components/feedback-indicators/skeleton-page) is a great way to improve the loading experience of pages. However, I'm using the skeleton for a [`Page`](https://polaris.shopify.com/components/structure/page) with the `additionalNavigation` property. The Skeleton does not  have a matching layout property for this - which causes the content of the page to shift after loading completes.

## Rationale
Implementing placeholder content using `additionalNavigation` in the `SkeletonPage` would provide a better loading experience, and would be a logical addition to the existing component properties.

Example of `additionalNavigation` content (`CD`):
<img width="874" alt="Screen Shot 2021-08-25 at 3 26 26 PM" src="https://user-images.githubusercontent.com/2933650/130852611-120a7e4b-6a97-4af5-9d18-61d9e5f8b720.png">

Example of non-matching SkeletonPage:
<img width="867" alt="Screen Shot 2021-08-25 at 3 26 38 PM" src="https://user-images.githubusercontent.com/2933650/130852605-d77b3487-9322-4c42-892e-13c6a25cd8a5.png">

**Comment by alex-page** [comment]
@sander-m this makes a lot of sense to me. We are not actively making changes to the skeleton page right now as we want to make broader layout changes. I am going to close this issue but if you want to make a PR you are welcome to.
