### ISSUE TITLE
Unable to import InlineError

### ISSUE THREAD

**Issue by shawnhind** [Shopify/polaris#444]
# Issue summary

Can't import inline error from @shopify/polaris

## Expected behavior
Importing this should succeed without any problems

## Actual behavior
I receive a warning during build that "export default InlineError could not be found in '@shopify/polaris'.

## Steps to reproduce the problem

1.Try importing inline error using import {InlineError} from '@shopify/polaris'

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 2.5
- Browser: N/A
- Device: N/A
- Operating System: OpenSuse

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 We _are_ accepting issue reports and feature requests<br />
🌟 Feature requests that we can’t get to right away will be closed. However, we track all requests and will use it to set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by shawnhind** [comment]
@katiedavis thanks, yes it looks like it was fixed in the newer version.  For some reason I was thinking in my head that 2.5 was a higher version than 2.11

**Comment by katiedavis** [comment]
@shawnhind hurray! glad to hear it's working now :)
