### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by aekinkjet2561** [Shopify/polaris#445]
# Feature request summary

## Rationale

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 We _are_ accepting issue reports and feature requests<br />
🌟 Feature requests that we can’t get to right away will be closed. However, we track all requests and will use it to set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by tmlayton** [comment]
Hi @aekinkjet2561, closing this issue for now because it is missing all details. Feel free to update the title and description with specifics about the feature requests and reopen the issue.
