### ISSUE TITLE
TextField autofocus not working when used in a Popover

### ISSUE THREAD

**Issue by rmaspoch** [Shopify/polaris#446]
# Issue summary
When using a Popover component that contains a TextField with the autofocus property set to true the TextField does not receives the focus when the Popover is displayed. 

## Expected behavior
The TextField component with autofocus set to true should received the focus when the Popover is displayed.

## Actual behavior
The TextField does not get the focus.

## Steps to reproduce the problem
1. Create a Popover component with a TextField component as a child.
2. Set the TextField autofocus property to true.
3. Activate the Popover.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 2.8
- Browser: Chrome Version 69.0.3497.100
- Device: Desktop computer
- Operating System: Windows 10

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 We _are_ accepting issue reports and feature requests<br />
🌟 Feature requests that we can’t get to right away will be closed. However, we track all requests and will use it to set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by 8bitmatt** [comment]
+1 
I'm seeing this issue with the latest 2.12.1 also. 
Upgraded a project from 2.5.0 this morning and the auto focus no longer works for Textfield inside a Popover.

I also tried setting the Popover's `preventAutofocus={false}` , still does not work

**Comment by dleroux** [comment]
Hi @8bitmatt 

In [2.6.0](https://github.com/Shopify/polaris/releases/tag/v2.6.1) we changed the primary focus target of an activated popover from the first focusable child to the popover itself. However if you do what you suggested, setting the Popover's `preventAutofocus={false}`, it should focus whatever you set autoFocus to in the popover.  See this code sandbox: https://codesandbox.io/s/31w2y3j2wp

In your summary you mention `autofocus` as oppose to `autoFocus`. Is it possible it's a case issue? Let us know.

**Comment by rmaspoch** [comment]
After upgrading to Polaris 2.12, the issue seems resolved.

**Comment by alefiyaV** [comment]
> In [2.6.0](https://github.com/Shopify/polaris/releases/tag/v2.6.1) we changed the primary focus target of an activated popover from the first focusable child to the popover itself. However if you do what you suggested, setting the Popover's `preventAutofocus={false}`, it should focus whatever you set autoFocus to in the popover. See this code sandbox: https://codesandbox.io/s/31w2y3j2wp

Hello! Slightly unrelated, but in this form, I am attempting for the Textfield to save the value (aka provide the action that the 'Add Filter' button does) when the user hits 'Enter'

Any suggestions?
