### ISSUE TITLE
TextField maxLength property does not work for number type

### ISSUE THREAD

**Issue by jt274** [Shopify/polaris#4468]
## Issue summary

When using the `TextField` component, the `maxLength` property does not work when the `type` property is set to `number`.

## Expected behavior

Behavior should be the same for all `type`s. A `maxLength` of 3 with the `type` set to number should not allow the input of `1234`.

## Actual behavior

There is no limit to the amount of numbers that can be input.

## Steps to reproduce the problem

```
<TextField
  label="Type a number"
  value={value}
  onChange={handleChange}
  maxLength={3}
  type="number"
  showCharacterCount={true}
/>
```

![textfield](https://user-images.githubusercontent.com/47506129/132285351-2e0e8d21-1514-4cfe-afc4-6d746a4b7479.png)

**Comment by NgocLe1001** [comment]
same issue

**Comment by yvan-sevic** [comment]
This is still an issue.

**Comment by EliottPal** [comment]
November 2024 and this is still an issue...

**Comment by ashok-essence** [comment]
As of February 10, 2025, the issue still persists. However, I was able to make it work in my case by using the `onChange` event.
