### ISSUE TITLE
ColorPicker throws error when rendered inside function component

### ISSUE THREAD

**Issue by vfonic** [Shopify/polaris#4469]
## Issue summary

I'm using Shopify Polaris with React 17 (17.0.2). I noticed that every time that I render `ColorPicker`, I get the following error:

<details><summary>
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
</summary>

![ColorPicker](https://user-images.githubusercontent.com/67437/132463969-78b31308-fced-4e97-a83a-1537472fe6b0.png)

</details>

## Expected behavior

No error should be raised.

## Steps to reproduce the problem

1. Create new React app with latest stable React release
1. Render `ColorPicker` component

## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

It would be great if the CodeSandbox template was upgraded to the latest version of Shopify Polaris. I tried, but failed to get it updated.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 6.6.0
- Browser: /
- Device: /
- Operating System: /

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by benhickson** [comment]
I'm experiencing the same error, but intermittently. Hard to reproduce on-demand. I see it maybe 3x a day, most recently in the PositionedOverlay component.
