### ISSUE TITLE
Add more attributes to Input tag

### ISSUE THREAD

**Issue by khiconit** [Shopify/polaris#448]
# Feature request summary
I think that Polaris should allow adding more attributes to the Input tag

In some case, I want to add more adding the attributes to the input field but I can't do it.
Hope Polaris can update it
(Sorry for my bad English )
## Rationale

---

⚓️ We’re not accepting pull requests at this time<br />
🗒 We _are_ accepting issue reports and feature requests<br />
🌟 Feature requests that we can’t get to right away will be closed. However, we track all requests and will use it to set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by BPScott** [comment]
Hi @khiconit 

Can you please be more specific? In which component do you want to make this change?

**Comment by khiconit** [comment]
All input form components
Sometimes I want to add some attributes to a input but Polaris doesn't allow it.
i think that you should add all prop of component to input 
Thanks

**Comment by BPScott** [comment]
A key benefit of components is encapsulation. By being strict with what we allow to be configured we can be confident about creating a consistent experience. Allowing arbitrary modification of components destroys our ability to ensure this consistency. Being able to add arbitrary attributes is dangerous as it makes it ensuring backwards compatibility impossible - any change that we make may potentially conflict with any additional attributes you add. This would make it very hard to upgrade to newer Polaris versions as any change may inadvertently break something in your application. It should be easy and safe to update between minor versions of Polaris and your proposed change would not allow that.

For this reason we will not add the ability to add arbitrary attributes.

If you have a particular use-case that the current components do not address - something more specific than "I want to add some attributes" - then we could look into adding additional functionality to components in a controlled way.
