### ISSUE TITLE
Media card forces images to have rounded corners while the card has no rounded corners (small screens)

### ISSUE THREAD

**Issue by MuratDikmen** [Shopify/polaris#4486]
## Issue summary
I recently worked with the Media card component on small screen sizes, and noticed that the image inside the MediaCard is forced to have rounded corners, while the card itself does have sharper corners. This results in misalignment of image borders and card borders.

## Expected behavior

The image should have the same (top) border-radius as the card (or vice versa).

## Actual behavior

The top corners of the card stick out.

## Steps to reproduce the problem

The issue can be seen in the [official documentation](https://polaris.shopify.com/components/structure/media-card) if you resize the card using the vertical handle:
<img width="383" alt="media-card-corner-issue" src="https://user-images.githubusercontent.com/9023733/134276052-5992b838-5bb4-4ee4-ab88-c380ffdf6c7a.png">

Is this the intended behavior? If so, is there a recommended solution to align the corners? I had to override the `--p-border-radius-wide` variable to make sure the image "fits" perfectly to the top of the card.

**Comment by alex-page** [comment]
This should be fixed with https://github.com/Shopify/polaris/pull/5828
