### ISSUE TITLE
Component to create sidebar?

### ISSUE THREAD

**Issue by jtreminio** [Shopify/polaris#453]
This comment (https://github.com/Shopify/polaris/issues/53#issue-228056600) touches on it; If I want to create a sidebar that works as the one found in the documentation, is there a Component I can use, or will this require custom HTML/CSS to implement?

**Comment by BPScott** [comment]
Hi @jtreminio, We've been working on a sidebar component over the past few months and shall be be including it in version 3.0, which we're hoping to release within the next few weeks.
