### ISSUE TITLE
Liquid editor

### ISSUE THREAD

**Issue by travishaynes** [Shopify/polaris#454]
# Feature request summary

It would be nice to have a Liquid editor as a component in Polaris. Ideally as a form component.

I realize this would be a very sophisticated thing to build from scratch. Fortunately there are already components for it. [Ace](https://ace.c9.io/) being the first one that comes to mind. There's already a [React Component](https://github.com/securingsincity/react-ace) for Ace that could be used as the boilerplate for the Polaris implementation.

## Rationale

Shopify users are already familiar with Liquid code. It's an excellent tool to use if your Shopify app has any content that can be customized. Having this built into Polaris would make it very easy for developers to add that feature to their app without having to customize something else to fit the Polaris theme, and it's a lot more professional than just using a textarea.

**Comment by dpersing** [comment]
Thanks for the request, @travishaynes! We’re not actively working on this right now, but we treat all feature requests as part of our backlog.

I’ll close this issue for now, but **we encourage everyone who wants this feature to add a 👍** to the original issue report here. We’ll take your collective interest into account when we look at what to work on next.

💜
