### ISSUE TITLE
Left align destructible buttons in modal

### ISSUE THREAD

**Issue by james-prado** [Shopify/polaris#458]
# Feature request summary

Left align destructible secondaryActions in Modal element

From: 
<img width="674" alt="screen shot 2018-10-23 at 11 54 14 pm" src="https://user-images.githubusercontent.com/13836920/47405473-abbc4300-d71f-11e8-8032-1d81f559cdc9.png">

To: 
<img width="644" alt="screen shot 2018-10-24 at 12 01 54 am" src="https://user-images.githubusercontent.com/13836920/47405600-55033900-d720-11e8-82a9-248b051d6963.png">

## Rationale

It would be nice to match the same pattern of having destructible items on the left seen throughout the shopify admin panel

<img width="1072" alt="screen shot 2018-10-23 at 11 54 25 pm" src="https://user-images.githubusercontent.com/13836920/47405475-ae1e9d00-d71f-11e8-86fc-adc11a2f5fbb.png">
<img width="1053" alt="screen shot 2018-10-24 at 12 08 12 am" src="https://user-images.githubusercontent.com/13836920/47405776-2cc80a00-d721-11e8-88d4-d72947556fe3.png">
<img width="1051" alt="screen shot 2018-10-24 at 12 05 45 am" src="https://user-images.githubusercontent.com/13836920/47405777-2cc80a00-d721-11e8-9c44-24e7fad7f2a5.png">

**Comment by chloerice** [comment]
Hey @james-prado, thanks for raising this! I've added this to our feature request backlog, so I’ll close this issue for now.

We encourage other folks who want this feature to add a 👍to the issue description. Collective need weighs into what we enhance next 😊.
