### ISSUE TITLE
Allow Select options to pass `disabled` prop.

### ISSUE THREAD

**Issue by sogko** [Shopify/polaris#68]
# Issue summary

Feature request: Allow `<Select>` component's options to be set as disabled.

Currently, the only props available for Select's options:
- value
- label

<img width="213" alt="screen shot 2017-05-26 at 5 49 19 pm" src="https://cloud.githubusercontent.com/assets/78585/26489861/ab4dde44-423b-11e7-9134-fd5777339d74.png">

## Specifications

- Polaris version: 1.0.3
- React version: NA
- Browser: NA
- Device: NA
- Operating System: NA

Cheers!

**Comment by lemonmade** [comment]
Thanks for the issue, @sogko. I put up a fix for this just now in our internal repo, so it should be part of the next release in a few days.

**Comment by lemonmade** [comment]
Should be fixed by v1.1.0
