### ISSUE TITLE
[a11y][Modal] Manage focus to first focusable element when available

### ISSUE THREAD

**Issue by dpersing** [Shopify/polaris#788]
## Issue

When the [Modal](https://polaris.shopify.com/components/overlays/modal#navigation) component opens, focus goes to the modal container by default. This is the most content-agnostic focus management approach, and it works great for modals that have primarily text-based content. However, the experience for modals that primarily contain form fields or other interactive controls could be improved. Currently:

- Users must <key>tab</key> to or click into the first field or control to start interacting. Products that use Polaris often have modals that contain only a form, or even a single form field, so this extra interaction slows users down.
- Sighted keyboard-only users may not be 100% sure that focus is in the modal since it isn't visible on the modal container.

See https://github.com/Shopify/polaris-ux/issues/193 for additional discussion.

See the [ARIA 1.1 authoring practices for modals](https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal), which recommends a more targeted focus approach.

## Recommendation

Dynamically manage focus based on the content of the modal.

- If the first element in a modal's main content (`Polaris-Modal__BodyWrapper`) is natively focusable, send focus to it. (This will almost always be a form field.)
- If the first element in a modal's main content is natively non-focusable content (text), fall back to our current standard of sending focus to the modal container.

**Comment by ry5n** [comment]
Just reviewed the proposal here in light of https://github.com/Shopify/polaris-ux/issues/237, and I think it’s a great complement to that issue. If we do this proposal, and give modals (and popovers) a visible focus state when interacted with via the keyboard, we’ll be in good shape!
