### ISSUE TITLE
Proposal: Using semantic versioning (semver)

### ISSUE THREAD

**Issue by buggy** [Shopify/polaris#87]
@lemonmade Looking at https://github.com/Shopify/polaris/issues/83 made me wonder if Polaris will be using [semantic versioning](http://semver.org/)? It might feel wrong to increment the major version in successive releases but it helps developers understand what impact upgrading a package will have.

**Comment by lemonmade** [comment]
Yes, we do plan on following semver, with some slightly unusual definitions of what leads to what kinds of changes (required by having both CSS-only and React ways of consuming). You can see some of our thoughts around this here: https://github.com/Shopify/polaris/blob/master/documentation/Versioning%20and%20changelog.md
