### ISSUE TITLE
Box properties

### ISSUE THREAD

**Issue by kyledurand** [Shopify/polaris#87]
### Discussed in https://github.com/Shopify/polaris/discussions/49

<div type='discussions-op-text'>

<sup>Originally posted by **kyledurand** June 21, 2021</sup>
Right now we have margin as the only available box property. How deep down the properties rabbit hole do we want to go?

Should we add flex / grid if we have flex / grid element components? I'm thinking these can be used inside of the Box component to create layouts.

What are some sensible defaults for this component?

### Possibilities:

**Box does everything: spacing, flex, and grid properties** 
* This makes for less markup
* Potentially more confusing for consumers. Will they find this component intuitive? Will they intrinsically reach for the box component to build layouts? This makes things even more confusing when introducing Flex and Grid components.

**Box does wrapper like things**
* Think [Text container](https://polaris.shopify.com/components/titles-and-text/text-container)
* Margin, padding, text align, ??

## Purpose

The current use-case of `Box` is for building layout. With its current functionality, it can be used to apply margin and padding directly to an element.

The purpose of `Box` could be expanded to be a more flexible low-level primitive. This would function as a bridge between HTML elements and our design tokens. The Box could be a simple extension of an HTML element (`div` by default) that provides access to themed atomic styles using a prop-based interface.
</div>

**Comment by samrose3** [comment]
It would be interesting to try and use the `Box` as a component-version reflection of the `atoms.css.ts`. This would essentially make the Box a styling mechanism that would be capable of all system atomic styles :atom:

**Comment by samrose3** [comment]
Now that Box is just a reflection of the atoms defined in `atoms.css.ts`, I think we can close this issue.

We may need to add and remove atomic styles as we build out other components, but going to resolve this issue for now. Feel free to reopen 📨
